.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
dlabel D_JP_8026F680
/* 16B440 8026F680 3FC999999999999A */ .double 0.200000000000000011
/* 16B448 8026F688 0000000000000000 */ .double 0
.size D_JP_8026F680, . - D_JP_8026F680


.section .text
/* Generated by spimdisasm 1.20.0 */

glabel pause_badges_draw_contents
/* 142968 80246BA8 27BDFF40 */  addiu     $sp, $sp, -0xC0
/* 14296C 80246BAC 240A0001 */  addiu     $t2, $zero, 0x1
/* 142970 80246BB0 3C028027 */  lui       $v0, %hi(gPauseBadgesCurrentPage)
/* 142974 80246BB4 8C42F940 */  lw        $v0, %lo(gPauseBadgesCurrentPage)($v0)
/* 142978 80246BB8 3C038027 */  lui       $v1, %hi(gPauseBadgesPages)
/* 14297C 80246BBC 2463F948 */  addiu     $v1, $v1, %lo(gPauseBadgesPages)
/* 142980 80246BC0 AFBF00BC */  sw        $ra, 0xBC($sp)
/* 142984 80246BC4 AFBE00B8 */  sw        $fp, 0xB8($sp)
/* 142988 80246BC8 AFB700B4 */  sw        $s7, 0xB4($sp)
/* 14298C 80246BCC AFB600B0 */  sw        $s6, 0xB0($sp)
/* 142990 80246BD0 AFB500AC */  sw        $s5, 0xAC($sp)
/* 142994 80246BD4 AFB400A8 */  sw        $s4, 0xA8($sp)
/* 142998 80246BD8 AFB300A4 */  sw        $s3, 0xA4($sp)
/* 14299C 80246BDC AFB200A0 */  sw        $s2, 0xA0($sp)
/* 1429A0 80246BE0 AFB1009C */  sw        $s1, 0x9C($sp)
/* 1429A4 80246BE4 AFB00098 */  sw        $s0, 0x98($sp)
/* 1429A8 80246BE8 AFA500C4 */  sw        $a1, 0xC4($sp)
/* 1429AC 80246BEC AFA600C8 */  sw        $a2, 0xC8($sp)
/* 1429B0 80246BF0 AFA700CC */  sw        $a3, 0xCC($sp)
/* 1429B4 80246BF4 AFA00070 */  sw        $zero, 0x70($sp)
/* 1429B8 80246BF8 AFA00074 */  sw        $zero, 0x74($sp)
/* 1429BC 80246BFC AFAA0064 */  sw        $t2, 0x64($sp)
/* 1429C0 80246C00 01428004 */  sllv      $s0, $v0, $t2
/* 1429C4 80246C04 02028021 */  addu      $s0, $s0, $v0
/* 1429C8 80246C08 00108080 */  sll       $s0, $s0, 2
/* 1429CC 80246C0C 0C090FEC */  jal       pause_get_total_equipped_bp_cost
/* 1429D0 80246C10 02038021 */   addu     $s0, $s0, $v1
/* 1429D4 80246C14 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 1429D8 80246C18 92090002 */  lbu       $t1, 0x2($s0)
/* 1429DC 80246C1C 8FAA00CC */  lw        $t2, 0xCC($sp)
/* 1429E0 80246C20 25660054 */  addiu     $a2, $t3, 0x54
/* 1429E4 80246C24 8FAB00D0 */  lw        $t3, 0xD0($sp)
/* 1429E8 80246C28 2543FFAC */  addiu     $v1, $t2, -0x54
/* 1429EC 80246C2C AFA30014 */  sw        $v1, 0x14($sp)
/* 1429F0 80246C30 240300FF */  addiu     $v1, $zero, 0xFF
/* 1429F4 80246C34 AFA3001C */  sw        $v1, 0x1C($sp)
/* 1429F8 80246C38 24030140 */  addiu     $v1, $zero, 0x140
/* 1429FC 80246C3C AFA30044 */  sw        $v1, 0x44($sp)
/* 142A00 80246C40 240300F0 */  addiu     $v1, $zero, 0xF0
/* 142A04 80246C44 AFA30048 */  sw        $v1, 0x48($sp)
/* 142A08 80246C48 3C038027 */  lui       $v1, %hi(gPauseBadgesSelectedIndex)
/* 142A0C 80246C4C 8C63FA38 */  lw        $v1, %lo(gPauseBadgesSelectedIndex)($v1)
/* 142A10 80246C50 AFAB0018 */  sw        $t3, 0x18($sp)
/* 142A14 80246C54 15200002 */  bnez      $t1, .LJP_80246C60
/* 142A18 80246C58 0069001A */   div      $zero, $v1, $t1
/* 142A1C 80246C5C 0007000D */  break     7
.LJP_80246C60:
/* 142A20 80246C60 2401FFFF */  addiu     $at, $zero, -0x1
/* 142A24 80246C64 15210004 */  bne       $t1, $at, .LJP_80246C78
/* 142A28 80246C68 3C018000 */   lui      $at, (0x80000000 >> 16)
/* 142A2C 80246C6C 14610002 */  bne       $v1, $at, .LJP_80246C78
/* 142A30 80246C70 00000000 */   nop
/* 142A34 80246C74 0006000D */  break     6
.LJP_80246C78:
/* 142A38 80246C78 00005012 */  mflo      $t2
/* 142A3C 80246C7C 00005810 */  mfhi      $t3
/* 142A40 80246C80 24040004 */  addiu     $a0, $zero, 0x4
/* 142A44 80246C84 8FA700C8 */  lw        $a3, 0xC8($sp)
/* 142A48 80246C88 3C088011 */  lui       $t0, %hi(gPlayerData + 0x8)
/* 142A4C 80246C8C 8108F458 */  lb        $t0, %lo(gPlayerData + 0x8)($t0)
/* 142A50 80246C90 3C058027 */  lui       $a1, %hi(gPauseWS_15)
/* 142A54 80246C94 24A5F318 */  addiu     $a1, $a1, %lo(gPauseWS_15)
/* 142A58 80246C98 AFA00010 */  sw        $zero, 0x10($sp)
/* 142A5C 80246C9C AFA00020 */  sw        $zero, 0x20($sp)
/* 142A60 80246CA0 AFA00024 */  sw        $zero, 0x24($sp)
/* 142A64 80246CA4 AFA00028 */  sw        $zero, 0x28($sp)
/* 142A68 80246CA8 AFA0002C */  sw        $zero, 0x2C($sp)
/* 142A6C 80246CAC AFA00030 */  sw        $zero, 0x30($sp)
/* 142A70 80246CB0 AFA00034 */  sw        $zero, 0x34($sp)
/* 142A74 80246CB4 AFA00038 */  sw        $zero, 0x38($sp)
/* 142A78 80246CB8 AFA0003C */  sw        $zero, 0x3C($sp)
/* 142A7C 80246CBC AFA00040 */  sw        $zero, 0x40($sp)
/* 142A80 80246CC0 AFA0004C */  sw        $zero, 0x4C($sp)
/* 142A84 80246CC4 01024023 */  subu      $t0, $t0, $v0
/* 142A88 80246CC8 AFA8006C */  sw        $t0, 0x6C($sp)
/* 142A8C 80246CCC AFAA0060 */  sw        $t2, 0x60($sp)
/* 142A90 80246CD0 0C03D51C */  jal       draw_box
/* 142A94 80246CD4 AFAB005C */   sw       $t3, 0x5C($sp)
/* 142A98 80246CD8 3C108027 */  lui       $s0, %hi(gPauseBadgesIconIDs)
/* 142A9C 80246CDC 2610FA68 */  addiu     $s0, $s0, %lo(gPauseBadgesIconIDs)
/* 142AA0 80246CE0 8FAA00C4 */  lw        $t2, 0xC4($sp)
/* 142AA4 80246CE4 8E040050 */  lw        $a0, 0x50($s0)
/* 142AA8 80246CE8 8FAB00C8 */  lw        $t3, 0xC8($sp)
/* 142AAC 80246CEC 254500D7 */  addiu     $a1, $t2, 0xD7
/* 142AB0 80246CF0 0C05268D */  jal       hud_element_set_render_pos
/* 142AB4 80246CF4 2566000B */   addiu    $a2, $t3, 0xB
/* 142AB8 80246CF8 8E040050 */  lw        $a0, 0x50($s0)
/* 142ABC 80246CFC 240A000A */  addiu     $t2, $zero, 0xA
/* 142AC0 80246D00 0C052624 */  jal       hud_element_draw_without_clipping
/* 142AC4 80246D04 AFAA0068 */   sw       $t2, 0x68($sp)
/* 142AC8 80246D08 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 142ACC 80246D0C 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 142AD0 80246D10 2546000E */  addiu     $a2, $t2, 0xE
/* 142AD4 80246D14 8FAA00CC */  lw        $t2, 0xCC($sp)
/* 142AD8 80246D18 25640001 */  addiu     $a0, $t3, 0x1
/* 142ADC 80246D1C 016A1021 */  addu      $v0, $t3, $t2
/* 142AE0 80246D20 8FAB00C8 */  lw        $t3, 0xC8($sp)
/* 142AE4 80246D24 8FAA00D0 */  lw        $t2, 0xD0($sp)
/* 142AE8 80246D28 2447FFFF */  addiu     $a3, $v0, -0x1
/* 142AEC 80246D2C 016A1021 */  addu      $v0, $t3, $t2
/* 142AF0 80246D30 1C800002 */  bgtz      $a0, .LJP_80246D3C
/* 142AF4 80246D34 2448FFF7 */   addiu    $t0, $v0, -0x9
/* 142AF8 80246D38 24040001 */  addiu     $a0, $zero, 0x1
.LJP_80246D3C:
/* 142AFC 80246D3C 58C00001 */  blezl     $a2, .LJP_80246D44
/* 142B00 80246D40 24060001 */   addiu    $a2, $zero, 0x1
.LJP_80246D44:
/* 142B04 80246D44 18E0058E */  blez      $a3, .LJP_80248380
/* 142B08 80246D48 00000000 */   nop
/* 142B0C 80246D4C 1900058C */  blez      $t0, .LJP_80248380
/* 142B10 80246D50 2882013F */   slti     $v0, $a0, 0x13F
/* 142B14 80246D54 1040058A */  beqz      $v0, .LJP_80248380
/* 142B18 80246D58 28C200EF */   slti     $v0, $a2, 0xEF
/* 142B1C 80246D5C 10400588 */  beqz      $v0, .LJP_80248380
/* 142B20 80246D60 28E2013F */   slti     $v0, $a3, 0x13F
/* 142B24 80246D64 50400001 */  beql      $v0, $zero, .LJP_80246D6C
/* 142B28 80246D68 2407013F */   addiu    $a3, $zero, 0x13F
.LJP_80246D6C:
/* 142B2C 80246D6C 290200EF */  slti      $v0, $t0, 0xEF
/* 142B30 80246D70 50400001 */  beql      $v0, $zero, .LJP_80246D78
/* 142B34 80246D74 240800EF */   addiu    $t0, $zero, 0xEF
.LJP_80246D78:
/* 142B38 80246D78 3C03800A */  lui       $v1, %hi(gMainGfxPos)
/* 142B3C 80246D7C 2463A64C */  addiu     $v1, $v1, %lo(gMainGfxPos)
/* 142B40 80246D80 44841000 */  mtc1      $a0, $f2
/* 142B44 80246D84 00000000 */  nop
/* 142B48 80246D88 468010A0 */  cvt.s.w   $f2, $f2
/* 142B4C 80246D8C 44860000 */  mtc1      $a2, $f0
/* 142B50 80246D90 00000000 */  nop
/* 142B54 80246D94 46800020 */  cvt.s.w   $f0, $f0
/* 142B58 80246D98 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 142B5C 80246D9C 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 142B60 80246DA0 3C014080 */  lui       $at, (0x40800000 >> 16)
/* 142B64 80246DA4 44812000 */  mtc1      $at, $f4
/* 142B68 80246DA8 3C04ED00 */  lui       $a0, (0xED000000 >> 16)
/* 142B6C 80246DAC AFA00058 */  sw        $zero, 0x58($sp)
/* 142B70 80246DB0 AFA00054 */  sw        $zero, 0x54($sp)
/* 142B74 80246DB4 256B0077 */  addiu     $t3, $t3, 0x77
/* 142B78 80246DB8 46041082 */  mul.s     $f2, $f2, $f4
/* 142B7C 80246DBC 00000000 */  nop
/* 142B80 80246DC0 254A0011 */  addiu     $t2, $t2, 0x11
/* 142B84 80246DC4 AFAB007C */  sw        $t3, 0x7C($sp)
/* 142B88 80246DC8 AFAA0080 */  sw        $t2, 0x80($sp)
/* 142B8C 80246DCC 8C620000 */  lw        $v0, 0x0($v1)
/* 142B90 80246DD0 46040002 */  mul.s     $f0, $f0, $f4
/* 142B94 80246DD4 00000000 */  nop
/* 142B98 80246DD8 0040282D */  daddu     $a1, $v0, $zero
/* 142B9C 80246DDC 24420008 */  addiu     $v0, $v0, 0x8
/* 142BA0 80246DE0 AC620000 */  sw        $v0, 0x0($v1)
/* 142BA4 80246DE4 4600118D */  trunc.w.s $f6, $f2
/* 142BA8 80246DE8 44023000 */  mfc1      $v0, $f6
/* 142BAC 80246DEC 00000000 */  nop
/* 142BB0 80246DF0 30420FFF */  andi      $v0, $v0, 0xFFF
/* 142BB4 80246DF4 00021300 */  sll       $v0, $v0, 12
/* 142BB8 80246DF8 4600018D */  trunc.w.s $f6, $f0
/* 142BBC 80246DFC 44033000 */  mfc1      $v1, $f6
/* 142BC0 80246E00 44871000 */  mtc1      $a3, $f2
/* 142BC4 80246E04 00000000 */  nop
/* 142BC8 80246E08 468010A0 */  cvt.s.w   $f2, $f2
/* 142BCC 80246E0C 46041082 */  mul.s     $f2, $f2, $f4
/* 142BD0 80246E10 00000000 */  nop
/* 142BD4 80246E14 30630FFF */  andi      $v1, $v1, 0xFFF
/* 142BD8 80246E18 00641825 */  or        $v1, $v1, $a0
/* 142BDC 80246E1C 00431025 */  or        $v0, $v0, $v1
/* 142BE0 80246E20 44880000 */  mtc1      $t0, $f0
/* 142BE4 80246E24 00000000 */  nop
/* 142BE8 80246E28 46800020 */  cvt.s.w   $f0, $f0
/* 142BEC 80246E2C 46040002 */  mul.s     $f0, $f0, $f4
/* 142BF0 80246E30 00000000 */  nop
/* 142BF4 80246E34 ACA20000 */  sw        $v0, 0x0($a1)
/* 142BF8 80246E38 4600118D */  trunc.w.s $f6, $f2
/* 142BFC 80246E3C 44023000 */  mfc1      $v0, $f6
/* 142C00 80246E40 00000000 */  nop
/* 142C04 80246E44 30420FFF */  andi      $v0, $v0, 0xFFF
/* 142C08 80246E48 00021300 */  sll       $v0, $v0, 12
/* 142C0C 80246E4C 4600018D */  trunc.w.s $f6, $f0
/* 142C10 80246E50 44033000 */  mfc1      $v1, $f6
/* 142C14 80246E54 00000000 */  nop
/* 142C18 80246E58 30630FFF */  andi      $v1, $v1, 0xFFF
/* 142C1C 80246E5C 00431025 */  or        $v0, $v0, $v1
/* 142C20 80246E60 ACA20004 */  sw        $v0, 0x4($a1)
.LJP_80246E64:
/* 142C24 80246E64 AFA00050 */  sw        $zero, 0x50($sp)
.LJP_80246E68:
/* 142C28 80246E68 8FAB0050 */  lw        $t3, 0x50($sp)
/* 142C2C 80246E6C 3C028027 */  lui       $v0, %hi(gPauseBadgesPages)
/* 142C30 80246E70 2442F948 */  addiu     $v0, $v0, %lo(gPauseBadgesPages)
/* 142C34 80246E74 000B1840 */  sll       $v1, $t3, 1
/* 142C38 80246E78 006B1821 */  addu      $v1, $v1, $t3
/* 142C3C 80246E7C 00031880 */  sll       $v1, $v1, 2
/* 142C40 80246E80 00621821 */  addu      $v1, $v1, $v0
/* 142C44 80246E84 AFA30078 */  sw        $v1, 0x78($sp)
/* 142C48 80246E88 90620000 */  lbu       $v0, 0x0($v1)
/* 142C4C 80246E8C 10400259 */  beqz      $v0, .LJP_802477F4
/* 142C50 80246E90 0160202D */   daddu    $a0, $t3, $zero
/* 142C54 80246E94 0C091A02 */  jal       pause_badges_get_pos_y
/* 142C58 80246E98 0000282D */   daddu    $a1, $zero, $zero
/* 142C5C 80246E9C 8FAA0078 */  lw        $t2, 0x78($sp)
/* 142C60 80246EA0 8D420008 */  lw        $v0, 0x8($t2)
/* 142C64 80246EA4 1840024E */  blez      $v0, .LJP_802477E0
/* 142C68 80246EA8 0000B82D */   daddu    $s7, $zero, $zero
/* 142C6C 80246EAC 3C0BE3E3 */  lui       $t3, (0xE3E3E3FF >> 16)
/* 142C70 80246EB0 356BE3FF */  ori       $t3, $t3, (0xE3E3E3FF & 0xFFFF)
/* 142C74 80246EB4 AFAB0090 */  sw        $t3, 0x90($sp)
/* 142C78 80246EB8 3C0A6666 */  lui       $t2, (0x66666667 >> 16)
/* 142C7C 80246EBC 354A6667 */  ori       $t2, $t2, (0x66666667 & 0xFFFF)
/* 142C80 80246EC0 AFAA0094 */  sw        $t2, 0x94($sp)
.LJP_80246EC4:
/* 142C84 80246EC4 8FAB0078 */  lw        $t3, 0x78($sp)
/* 142C88 80246EC8 3C118011 */  lui       $s1, %hi(gPlayerData + 0x208)
/* 142C8C 80246ECC 2631F658 */  addiu     $s1, $s1, %lo(gPlayerData + 0x208)
/* 142C90 80246ED0 AFA00084 */  sw        $zero, 0x84($sp)
/* 142C94 80246ED4 8D620004 */  lw        $v0, 0x4($t3)
/* 142C98 80246ED8 24037FFF */  addiu     $v1, $zero, 0x7FFF
/* 142C9C 80246EDC AFA0008C */  sw        $zero, 0x8C($sp)
/* 142CA0 80246EE0 00571021 */  addu      $v0, $v0, $s7
/* 142CA4 80246EE4 00021040 */  sll       $v0, $v0, 1
/* 142CA8 80246EE8 3C108027 */  lui       $s0, %hi(gPauseBadgesItemIds)
/* 142CAC 80246EEC 02028021 */  addu      $s0, $s0, $v0
/* 142CB0 80246EF0 8610F840 */  lh        $s0, %lo(gPauseBadgesItemIds)($s0)
/* 142CB4 80246EF4 3C138027 */  lui       $s3, %hi(gPauseBadgesItemIds)
/* 142CB8 80246EF8 02629821 */  addu      $s3, $s3, $v0
/* 142CBC 80246EFC 9673F840 */  lhu       $s3, %lo(gPauseBadgesItemIds)($s3)
/* 142CC0 80246F00 12030231 */  beq       $s0, $v1, .LJP_802477C8
/* 142CC4 80246F04 0000F02D */   daddu    $fp, $zero, $zero
/* 142CC8 80246F08 8FA40050 */  lw        $a0, 0x50($sp)
/* 142CCC 80246F0C 0C0919EB */  jal       pause_badges_get_pos_x
/* 142CD0 80246F10 02E0282D */   daddu    $a1, $s7, $zero
/* 142CD4 80246F14 02E0282D */  daddu     $a1, $s7, $zero
/* 142CD8 80246F18 8FA40050 */  lw        $a0, 0x50($sp)
/* 142CDC 80246F1C 0C091A02 */  jal       pause_badges_get_pos_y
/* 142CE0 80246F20 0040B02D */   daddu    $s6, $v0, $zero
/* 142CE4 80246F24 0040A82D */  daddu     $s5, $v0, $zero
/* 142CE8 80246F28 3A027FFE */  xori      $v0, $s0, 0x7FFE
/* 142CEC 80246F2C 2C420001 */  sltiu     $v0, $v0, 0x1
/* 142CF0 80246F30 03C0902D */  daddu     $s2, $fp, $zero
/* 142CF4 80246F34 0200182D */  daddu     $v1, $s0, $zero
/* 142CF8 80246F38 AFA20088 */  sw        $v0, 0x88($sp)
.LJP_80246F3C:
/* 142CFC 80246F3C 86220000 */  lh        $v0, 0x0($s1)
/* 142D00 80246F40 1062007D */  beq       $v1, $v0, .LJP_80247138
/* 142D04 80246F44 26520001 */   addiu    $s2, $s2, 0x1
/* 142D08 80246F48 2A420040 */  slti      $v0, $s2, 0x40
/* 142D0C 80246F4C 1440FFFB */  bnez      $v0, .LJP_80246F3C
/* 142D10 80246F50 26310002 */   addiu    $s1, $s1, 0x2
.LJP_80246F54:
/* 142D14 80246F54 3C038027 */  lui       $v1, %hi(gPauseMenuCurrentTab)
/* 142D18 80246F58 8063F7A4 */  lb        $v1, %lo(gPauseMenuCurrentTab)($v1)
/* 142D1C 80246F5C 24020002 */  addiu     $v0, $zero, 0x2
/* 142D20 80246F60 14620029 */  bne       $v1, $v0, .LJP_80247008
/* 142D24 80246F64 24020001 */   addiu    $v0, $zero, 0x1
/* 142D28 80246F68 3C038027 */  lui       $v1, %hi(gPauseBadgesLevel)
/* 142D2C 80246F6C 8C63FA58 */  lw        $v1, %lo(gPauseBadgesLevel)($v1)
/* 142D30 80246F70 14620025 */  bne       $v1, $v0, .LJP_80247008
/* 142D34 80246F74 00000000 */   nop
/* 142D38 80246F78 8FA40050 */  lw        $a0, 0x50($sp)
/* 142D3C 80246F7C 0C091A1E */  jal       pause_badges_get_column
/* 142D40 80246F80 02E0282D */   daddu    $a1, $s7, $zero
/* 142D44 80246F84 8FAA005C */  lw        $t2, 0x5C($sp)
/* 142D48 80246F88 144A001F */  bne       $v0, $t2, .LJP_80247008
/* 142D4C 80246F8C 00000000 */   nop
/* 142D50 80246F90 8FA40050 */  lw        $a0, 0x50($sp)
/* 142D54 80246F94 0C091A30 */  jal       pause_badges_get_row
/* 142D58 80246F98 02E0282D */   daddu    $a1, $s7, $zero
/* 142D5C 80246F9C 8FAB0060 */  lw        $t3, 0x60($sp)
/* 142D60 80246FA0 144B0019 */  bne       $v0, $t3, .LJP_80247008
/* 142D64 80246FA4 00131400 */   sll      $v0, $s3, 16
/* 142D68 80246FA8 241E0001 */  addiu     $fp, $zero, 0x1
/* 142D6C 80246FAC 8FAA0088 */  lw        $t2, 0x88($sp)
/* 142D70 80246FB0 1540002A */  bnez      $t2, .LJP_8024705C
/* 142D74 80246FB4 00021403 */   sra      $v0, $v0, 16
/* 142D78 80246FB8 00021140 */  sll       $v0, $v0, 5
/* 142D7C 80246FBC 3C0B8008 */  lui       $t3, %hi(gItemTable)
/* 142D80 80246FC0 256B78B0 */  addiu     $t3, $t3, %lo(gItemTable)
/* 142D84 80246FC4 004B1021 */  addu      $v0, $v0, $t3
/* 142D88 80246FC8 3C0A8009 */  lui       $t2, %hi(gMoveTable)
/* 142D8C 80246FCC 254AF030 */  addiu     $t2, $t2, %lo(gMoveTable)
/* 142D90 80246FD0 9043001A */  lbu       $v1, 0x1A($v0)
/* 142D94 80246FD4 8FAB0084 */  lw        $t3, 0x84($sp)
/* 142D98 80246FD8 00031080 */  sll       $v0, $v1, 2
/* 142D9C 80246FDC 00431021 */  addu      $v0, $v0, $v1
/* 142DA0 80246FE0 00021080 */  sll       $v0, $v0, 2
/* 142DA4 80246FE4 004A1021 */  addu      $v0, $v0, $t2
/* 142DA8 80246FE8 80420012 */  lb        $v0, 0x12($v0)
/* 142DAC 80246FEC 15600006 */  bnez      $t3, .LJP_80247008
/* 142DB0 80246FF0 AFA20070 */   sw       $v0, 0x70($sp)
/* 142DB4 80246FF4 8FAA006C */  lw        $t2, 0x6C($sp)
/* 142DB8 80246FF8 0142102A */  slt       $v0, $t2, $v0
/* 142DBC 80246FFC 14400002 */  bnez      $v0, .LJP_80247008
/* 142DC0 80247000 03C0582D */   daddu    $t3, $fp, $zero
/* 142DC4 80247004 AFAB0074 */  sw        $t3, 0x74($sp)
.LJP_80247008:
/* 142DC8 80247008 8FAA0088 */  lw        $t2, 0x88($sp)
/* 142DCC 8024700C 15400014 */  bnez      $t2, .LJP_80247060
/* 142DD0 80247010 0000902D */   daddu    $s2, $zero, $zero
/* 142DD4 80247014 00131400 */  sll       $v0, $s3, 16
/* 142DD8 80247018 000212C3 */  sra       $v0, $v0, 11
/* 142DDC 8024701C 3C0B8008 */  lui       $t3, %hi(gItemTable)
/* 142DE0 80247020 256B78B0 */  addiu     $t3, $t3, %lo(gItemTable)
/* 142DE4 80247024 004B1021 */  addu      $v0, $v0, $t3
/* 142DE8 80247028 3C0A8009 */  lui       $t2, %hi(gMoveTable)
/* 142DEC 8024702C 254AF030 */  addiu     $t2, $t2, %lo(gMoveTable)
/* 142DF0 80247030 9043001A */  lbu       $v1, 0x1A($v0)
/* 142DF4 80247034 8FAB006C */  lw        $t3, 0x6C($sp)
/* 142DF8 80247038 00031080 */  sll       $v0, $v1, 2
/* 142DFC 8024703C 00431021 */  addu      $v0, $v0, $v1
/* 142E00 80247040 00021080 */  sll       $v0, $v0, 2
/* 142E04 80247044 004A1021 */  addu      $v0, $v0, $t2
/* 142E08 80247048 80420012 */  lb        $v0, 0x12($v0)
/* 142E0C 8024704C 0162102A */  slt       $v0, $t3, $v0
/* 142E10 80247050 10400003 */  beqz      $v0, .LJP_80247060
/* 142E14 80247054 240A0001 */   addiu    $t2, $zero, 0x1
/* 142E18 80247058 AFAA008C */  sw        $t2, 0x8C($sp)
.LJP_8024705C:
/* 142E1C 8024705C 0000902D */  daddu     $s2, $zero, $zero
.LJP_80247060:
/* 142E20 80247060 13C00003 */  beqz      $fp, .LJP_80247070
/* 142E24 80247064 0240A02D */   daddu    $s4, $s2, $zero
/* 142E28 80247068 2412FFFF */  addiu     $s2, $zero, -0x1
/* 142E2C 8024706C 0240A02D */  daddu     $s4, $s2, $zero
.LJP_80247070:
/* 142E30 80247070 8FAB0054 */  lw        $t3, 0x54($sp)
/* 142E34 80247074 15600037 */  bnez      $t3, .LJP_80247154
/* 142E38 80247078 240A0001 */   addiu    $t2, $zero, 0x1
/* 142E3C 8024707C 240B000A */  addiu     $t3, $zero, 0xA
/* 142E40 80247080 AFAA0064 */  sw        $t2, 0x64($sp)
/* 142E44 80247084 13C00003 */  beqz      $fp, .LJP_80247094
/* 142E48 80247088 AFAB0068 */   sw       $t3, 0x68($sp)
/* 142E4C 8024708C 240A0009 */  addiu     $t2, $zero, 0x9
/* 142E50 80247090 AFAA0064 */  sw        $t2, 0x64($sp)
.LJP_80247094:
/* 142E54 80247094 8FAB0084 */  lw        $t3, 0x84($sp)
/* 142E58 80247098 1160002A */  beqz      $t3, .LJP_80247144
/* 142E5C 8024709C 00000000 */   nop
/* 142E60 802470A0 0C091A52 */  jal       pause_badges_scroll_offset_x
/* 142E64 802470A4 02C0202D */   daddu    $a0, $s6, $zero
/* 142E68 802470A8 8FAA007C */  lw        $t2, 0x7C($sp)
/* 142E6C 802470AC 02A0202D */  daddu     $a0, $s5, $zero
/* 142E70 802470B0 01428021 */  addu      $s0, $t2, $v0
/* 142E74 802470B4 0C091A4E */  jal       pause_badges_scroll_offset_y
/* 142E78 802470B8 2610FFEC */   addiu    $s0, $s0, -0x14
/* 142E7C 802470BC 24040004 */  addiu     $a0, $zero, 0x4
/* 142E80 802470C0 3C058027 */  lui       $a1, %hi(gPauseWS_14)
/* 142E84 802470C4 24A5F2E0 */  addiu     $a1, $a1, %lo(gPauseWS_14)
/* 142E88 802470C8 8FAB00C8 */  lw        $t3, 0xC8($sp)
/* 142E8C 802470CC 0200302D */  daddu     $a2, $s0, $zero
/* 142E90 802470D0 AFA00010 */  sw        $zero, 0x10($sp)
/* 142E94 802470D4 AFA00020 */  sw        $zero, 0x20($sp)
/* 142E98 802470D8 AFA00024 */  sw        $zero, 0x24($sp)
/* 142E9C 802470DC AFA00028 */  sw        $zero, 0x28($sp)
/* 142EA0 802470E0 AFA0002C */  sw        $zero, 0x2C($sp)
/* 142EA4 802470E4 AFA00030 */  sw        $zero, 0x30($sp)
/* 142EA8 802470E8 AFA00034 */  sw        $zero, 0x34($sp)
/* 142EAC 802470EC AFA00038 */  sw        $zero, 0x38($sp)
/* 142EB0 802470F0 AFA0003C */  sw        $zero, 0x3C($sp)
/* 142EB4 802470F4 AFA00040 */  sw        $zero, 0x40($sp)
/* 142EB8 802470F8 AFA0004C */  sw        $zero, 0x4C($sp)
/* 142EBC 802470FC 01621021 */  addu      $v0, $t3, $v0
/* 142EC0 80247100 24470011 */  addiu     $a3, $v0, 0x11
/* 142EC4 80247104 240200C8 */  addiu     $v0, $zero, 0xC8
/* 142EC8 80247108 AFA20014 */  sw        $v0, 0x14($sp)
/* 142ECC 8024710C 2402000D */  addiu     $v0, $zero, 0xD
/* 142ED0 80247110 AFA20018 */  sw        $v0, 0x18($sp)
/* 142ED4 80247114 240200FF */  addiu     $v0, $zero, 0xFF
/* 142ED8 80247118 AFA2001C */  sw        $v0, 0x1C($sp)
/* 142EDC 8024711C 24020140 */  addiu     $v0, $zero, 0x140
/* 142EE0 80247120 AFA20044 */  sw        $v0, 0x44($sp)
/* 142EE4 80247124 240200F0 */  addiu     $v0, $zero, 0xF0
/* 142EE8 80247128 0C03D51C */  jal       draw_box
/* 142EEC 8024712C AFA20048 */   sw       $v0, 0x48($sp)
/* 142EF0 80247130 08091C55 */  j         .LJP_80247154
/* 142EF4 80247134 00000000 */   nop
.LJP_80247138:
/* 142EF8 80247138 240A0001 */  addiu     $t2, $zero, 0x1
/* 142EFC 8024713C 08091BD5 */  j         .LJP_80246F54
/* 142F00 80247140 AFAA0084 */   sw       $t2, 0x84($sp)
.LJP_80247144:
/* 142F04 80247144 8FAB008C */  lw        $t3, 0x8C($sp)
/* 142F08 80247148 11600002 */  beqz      $t3, .LJP_80247154
/* 142F0C 8024714C 240A000B */   addiu    $t2, $zero, 0xB
/* 142F10 80247150 AFAA0068 */  sw        $t2, 0x68($sp)
.LJP_80247154:
/* 142F14 80247154 0C091A44 */  jal       pause_badges_is_visible
/* 142F18 80247158 02A0202D */   daddu    $a0, $s5, $zero
/* 142F1C 8024715C 1040019A */  beqz      $v0, .LJP_802477C8
/* 142F20 80247160 00000000 */   nop
/* 142F24 80247164 8FAB0054 */  lw        $t3, 0x54($sp)
/* 142F28 80247168 15600058 */  bnez      $t3, .LJP_802472CC
/* 142F2C 8024716C 24020001 */   addiu    $v0, $zero, 0x1
/* 142F30 80247170 8FAA0088 */  lw        $t2, 0x88($sp)
/* 142F34 80247174 11400018 */  beqz      $t2, .LJP_802471D8
/* 142F38 80247178 00131400 */   sll      $v0, $s3, 16
/* 142F3C 8024717C 0C09396C */  jal       pause_get_menu_msg
/* 142F40 80247180 24040045 */   addiu    $a0, $zero, 0x45
/* 142F44 80247184 02C0202D */  daddu     $a0, $s6, $zero
/* 142F48 80247188 0C091A52 */  jal       pause_badges_scroll_offset_x
/* 142F4C 8024718C 0040882D */   daddu    $s1, $v0, $zero
/* 142F50 80247190 8FAB007C */  lw        $t3, 0x7C($sp)
/* 142F54 80247194 02A0202D */  daddu     $a0, $s5, $zero
/* 142F58 80247198 01628021 */  addu      $s0, $t3, $v0
/* 142F5C 8024719C 0C091A4E */  jal       pause_badges_scroll_offset_y
/* 142F60 802471A0 02128021 */   addu     $s0, $s0, $s2
/* 142F64 802471A4 0220202D */  daddu     $a0, $s1, $zero
/* 142F68 802471A8 0200282D */  daddu     $a1, $s0, $zero
/* 142F6C 802471AC 240700FF */  addiu     $a3, $zero, 0xFF
/* 142F70 802471B0 8FAA0080 */  lw        $t2, 0x80($sp)
/* 142F74 802471B4 8FAB0068 */  lw        $t3, 0x68($sp)
/* 142F78 802471B8 01421021 */  addu      $v0, $t2, $v0
/* 142F7C 802471BC 8FAA0064 */  lw        $t2, 0x64($sp)
/* 142F80 802471C0 00543021 */  addu      $a2, $v0, $s4
/* 142F84 802471C4 AFAB0010 */  sw        $t3, 0x10($sp)
/* 142F88 802471C8 0C04ADC4 */  jal       draw_msg
/* 142F8C 802471CC AFAA0014 */   sw       $t2, 0x14($sp)
/* 142F90 802471D0 08091CB1 */  j         .LJP_802472C4
/* 142F94 802471D4 00000000 */   nop
.LJP_802471D8:
/* 142F98 802471D8 000212C3 */  sra       $v0, $v0, 11
/* 142F9C 802471DC 3C0B8008 */  lui       $t3, %hi(gItemTable)
/* 142FA0 802471E0 256B78B0 */  addiu     $t3, $t3, %lo(gItemTable)
/* 142FA4 802471E4 004B8821 */  addu      $s1, $v0, $t3
/* 142FA8 802471E8 8E220000 */  lw        $v0, 0x0($s1)
/* 142FAC 802471EC 10400015 */  beqz      $v0, .LJP_80247244
/* 142FB0 802471F0 00000000 */   nop
/* 142FB4 802471F4 18400013 */  blez      $v0, .LJP_80247244
/* 142FB8 802471F8 00000000 */   nop
/* 142FBC 802471FC 0C091A52 */  jal       pause_badges_scroll_offset_x
/* 142FC0 80247200 02C0202D */   daddu    $a0, $s6, $zero
/* 142FC4 80247204 8FAA007C */  lw        $t2, 0x7C($sp)
/* 142FC8 80247208 02A0202D */  daddu     $a0, $s5, $zero
/* 142FCC 8024720C 01428021 */  addu      $s0, $t2, $v0
/* 142FD0 80247210 0C091A4E */  jal       pause_badges_scroll_offset_y
/* 142FD4 80247214 02128021 */   addu     $s0, $s0, $s2
/* 142FD8 80247218 0200282D */  daddu     $a1, $s0, $zero
/* 142FDC 8024721C 8FAB0080 */  lw        $t3, 0x80($sp)
/* 142FE0 80247220 8FAA0068 */  lw        $t2, 0x68($sp)
/* 142FE4 80247224 01621021 */  addu      $v0, $t3, $v0
/* 142FE8 80247228 8FAB0064 */  lw        $t3, 0x64($sp)
/* 142FEC 8024722C 240700FF */  addiu     $a3, $zero, 0xFF
/* 142FF0 80247230 AFAA0010 */  sw        $t2, 0x10($sp)
/* 142FF4 80247234 AFAB0014 */  sw        $t3, 0x14($sp)
/* 142FF8 80247238 8E240000 */  lw        $a0, 0x0($s1)
/* 142FFC 8024723C 0C04ADC4 */  jal       draw_msg
/* 143000 80247240 00543021 */   addu     $a2, $v0, $s4
.LJP_80247244:
/* 143004 80247244 0C091A52 */  jal       pause_badges_scroll_offset_x
/* 143008 80247248 02C0202D */   daddu    $a0, $s6, $zero
/* 14300C 8024724C 02A0202D */  daddu     $a0, $s5, $zero
/* 143010 80247250 8FAA00C4 */  lw        $t2, 0xC4($sp)
/* 143014 80247254 245000D3 */  addiu     $s0, $v0, 0xD3
/* 143018 80247258 0C091A4E */  jal       pause_badges_scroll_offset_y
/* 14301C 8024725C 01508021 */   addu     $s0, $t2, $s0
/* 143020 80247260 0200282D */  daddu     $a1, $s0, $zero
/* 143024 80247264 24420011 */  addiu     $v0, $v0, 0x11
/* 143028 80247268 00131C00 */  sll       $v1, $s3, 16
/* 14302C 8024726C 00031AC3 */  sra       $v1, $v1, 11
/* 143030 80247270 3C0B8008 */  lui       $t3, %hi(gItemTable)
/* 143034 80247274 256B78B0 */  addiu     $t3, $t3, %lo(gItemTable)
/* 143038 80247278 006B1821 */  addu      $v1, $v1, $t3
/* 14303C 8024727C 3C0B8009 */  lui       $t3, %hi(gMoveTable)
/* 143040 80247280 256BF030 */  addiu     $t3, $t3, %lo(gMoveTable)
/* 143044 80247284 24070001 */  addiu     $a3, $zero, 0x1
/* 143048 80247288 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 14304C 8024728C 9063001A */  lbu       $v1, 0x1A($v1)
/* 143050 80247290 01423021 */  addu      $a2, $t2, $v0
/* 143054 80247294 00031080 */  sll       $v0, $v1, 2
/* 143058 80247298 00431021 */  addu      $v0, $v0, $v1
/* 14305C 8024729C 00021080 */  sll       $v0, $v0, 2
/* 143060 802472A0 004B1021 */  addu      $v0, $v0, $t3
/* 143064 802472A4 80440012 */  lb        $a0, 0x12($v0)
/* 143068 802472A8 8FAA0068 */  lw        $t2, 0x68($sp)
/* 14306C 802472AC 240200FF */  addiu     $v0, $zero, 0xFF
/* 143070 802472B0 AFA20014 */  sw        $v0, 0x14($sp)
/* 143074 802472B4 24020003 */  addiu     $v0, $zero, 0x3
/* 143078 802472B8 AFA20018 */  sw        $v0, 0x18($sp)
/* 14307C 802472BC 0C04B22C */  jal       draw_number
/* 143080 802472C0 AFAA0010 */   sw       $t2, 0x10($sp)
.LJP_802472C4:
/* 143084 802472C4 8FAB0054 */  lw        $t3, 0x54($sp)
/* 143088 802472C8 24020001 */  addiu     $v0, $zero, 0x1
.LJP_802472CC:
/* 14308C 802472CC 15620060 */  bne       $t3, $v0, .LJP_80247450
/* 143090 802472D0 3C052000 */   lui      $a1, (0x20000000 >> 16)
/* 143094 802472D4 8FAA0058 */  lw        $t2, 0x58($sp)
/* 143098 802472D8 000A1080 */  sll       $v0, $t2, 2
/* 14309C 802472DC 3C0B8027 */  lui       $t3, %hi(gPauseBadgesIconIDs)
/* 1430A0 802472E0 256BFA68 */  addiu     $t3, $t3, %lo(gPauseBadgesIconIDs)
/* 1430A4 802472E4 004B1021 */  addu      $v0, $v0, $t3
/* 1430A8 802472E8 8C510000 */  lw        $s1, 0x0($v0)
/* 1430AC 802472EC 0C0526B7 */  jal       hud_element_clear_flags
/* 1430B0 802472F0 0220202D */   daddu    $a0, $s1, $zero
/* 1430B4 802472F4 0220202D */  daddu     $a0, $s1, $zero
/* 1430B8 802472F8 0C0526AC */  jal       hud_element_set_flags
/* 1430BC 802472FC 34058000 */   ori      $a1, $zero, 0x8000
/* 1430C0 80247300 8FAA0088 */  lw        $t2, 0x88($sp)
/* 1430C4 80247304 11400005 */  beqz      $t2, .LJP_8024731C
/* 1430C8 80247308 00000000 */   nop
/* 1430CC 8024730C 3C118027 */  lui       $s1, %hi(D_8026FABC)
/* 1430D0 80247310 8E31FABC */  lw        $s1, %lo(D_8026FABC)($s1)
/* 1430D4 80247314 08091CF9 */  j         .LJP_802473E4
/* 1430D8 80247318 00000000 */   nop
.LJP_8024731C:
/* 1430DC 8024731C 13C00010 */  beqz      $fp, .LJP_80247360
/* 1430E0 80247320 0220202D */   daddu    $a0, $s1, $zero
/* 1430E4 80247324 0C0526AC */  jal       hud_element_set_flags
/* 1430E8 80247328 3C052000 */   lui      $a1, (0x20000000 >> 16)
/* 1430EC 8024732C 00131400 */  sll       $v0, $s3, 16
/* 1430F0 80247330 000212C3 */  sra       $v0, $v0, 11
/* 1430F4 80247334 3C0B8008 */  lui       $t3, %hi(gItemTable)
/* 1430F8 80247338 256B78B0 */  addiu     $t3, $t3, %lo(gItemTable)
/* 1430FC 8024733C 004B1021 */  addu      $v0, $v0, $t3
/* 143100 80247340 84420004 */  lh        $v0, 0x4($v0)
/* 143104 80247344 3C0A8009 */  lui       $t2, %hi(gItemHudScripts)
/* 143108 80247348 254AA650 */  addiu     $t2, $t2, %lo(gItemHudScripts)
/* 14310C 8024734C 000210C0 */  sll       $v0, $v0, 3
/* 143110 80247350 004A1021 */  addu      $v0, $v0, $t2
/* 143114 80247354 8C420000 */  lw        $v0, 0x0($v0)
/* 143118 80247358 3C018027 */  lui       $at, %hi(gPauseCurrentDescIconScript)
/* 14311C 8024735C AC22F79C */  sw        $v0, %lo(gPauseCurrentDescIconScript)($at)
.LJP_80247360:
/* 143120 80247360 8FAB0084 */  lw        $t3, 0x84($sp)
/* 143124 80247364 1560000F */  bnez      $t3, .LJP_802473A4
/* 143128 80247368 00131400 */   sll      $v0, $s3, 16
/* 14312C 8024736C 8FAA008C */  lw        $t2, 0x8C($sp)
/* 143130 80247370 1140000B */  beqz      $t2, .LJP_802473A0
/* 143134 80247374 000212C3 */   sra      $v0, $v0, 11
/* 143138 80247378 3C0B8008 */  lui       $t3, %hi(gItemTable)
/* 14313C 8024737C 256B78B0 */  addiu     $t3, $t3, %lo(gItemTable)
/* 143140 80247380 004B1021 */  addu      $v0, $v0, $t3
/* 143144 80247384 84420004 */  lh        $v0, 0x4($v0)
/* 143148 80247388 3C0A8009 */  lui       $t2, %hi(gItemHudScripts)
/* 14314C 8024738C 254AA650 */  addiu     $t2, $t2, %lo(gItemHudScripts)
/* 143150 80247390 000210C0 */  sll       $v0, $v0, 3
/* 143154 80247394 004A1021 */  addu      $v0, $v0, $t2
/* 143158 80247398 08091CF3 */  j         .LJP_802473CC
/* 14315C 8024739C 8C450004 */   lw       $a1, 0x4($v0)
.LJP_802473A0:
/* 143160 802473A0 00131400 */  sll       $v0, $s3, 16
.LJP_802473A4:
/* 143164 802473A4 000212C3 */  sra       $v0, $v0, 11
/* 143168 802473A8 3C0B8008 */  lui       $t3, %hi(gItemTable)
/* 14316C 802473AC 256B78B0 */  addiu     $t3, $t3, %lo(gItemTable)
/* 143170 802473B0 004B1021 */  addu      $v0, $v0, $t3
/* 143174 802473B4 84420004 */  lh        $v0, 0x4($v0)
/* 143178 802473B8 3C0A8009 */  lui       $t2, %hi(gItemHudScripts)
/* 14317C 802473BC 254AA650 */  addiu     $t2, $t2, %lo(gItemHudScripts)
/* 143180 802473C0 000210C0 */  sll       $v0, $v0, 3
/* 143184 802473C4 004A1021 */  addu      $v0, $v0, $t2
/* 143188 802473C8 8C450000 */  lw        $a1, 0x0($v0)
.LJP_802473CC:
/* 14318C 802473CC 0C05262B */  jal       hud_element_set_script
/* 143190 802473D0 0220202D */   daddu    $a0, $s1, $zero
/* 143194 802473D4 3C053F2B */  lui       $a1, (0x3F2BBA99 >> 16)
/* 143198 802473D8 34A5BA99 */  ori       $a1, $a1, (0x3F2BBA99 & 0xFFFF)
/* 14319C 802473DC 0C052734 */  jal       hud_element_set_scale
/* 1431A0 802473E0 0220202D */   daddu    $a0, $s1, $zero
.LJP_802473E4:
/* 1431A4 802473E4 0C091A52 */  jal       pause_badges_scroll_offset_x
/* 1431A8 802473E8 02C0202D */   daddu    $a0, $s6, $zero
/* 1431AC 802473EC 02A0202D */  daddu     $a0, $s5, $zero
/* 1431B0 802473F0 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 1431B4 802473F4 2450006B */  addiu     $s0, $v0, 0x6B
/* 1431B8 802473F8 01708021 */  addu      $s0, $t3, $s0
/* 1431BC 802473FC 0C091A4E */  jal       pause_badges_scroll_offset_y
/* 1431C0 80247400 02128021 */   addu     $s0, $s0, $s2
/* 1431C4 80247404 0220202D */  daddu     $a0, $s1, $zero
/* 1431C8 80247408 0200282D */  daddu     $a1, $s0, $zero
/* 1431CC 8024740C 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 1431D0 80247410 24420017 */  addiu     $v0, $v0, 0x17
/* 1431D4 80247414 01421021 */  addu      $v0, $t2, $v0
/* 1431D8 80247418 0C05268D */  jal       hud_element_set_render_pos
/* 1431DC 8024741C 00543021 */   addu     $a2, $v0, $s4
/* 1431E0 80247420 8FAB0058 */  lw        $t3, 0x58($sp)
/* 1431E4 80247424 15600005 */  bnez      $t3, .LJP_8024743C
/* 1431E8 80247428 00000000 */   nop
/* 1431EC 8024742C 0C052624 */  jal       hud_element_draw_without_clipping
/* 1431F0 80247430 0220202D */   daddu    $a0, $s1, $zero
/* 1431F4 80247434 08091D11 */  j         .LJP_80247444
/* 1431F8 80247438 00000000 */   nop
.LJP_8024743C:
/* 1431FC 8024743C 0C05261D */  jal       hud_element_draw_next
/* 143200 80247440 0220202D */   daddu    $a0, $s1, $zero
.LJP_80247444:
/* 143204 80247444 8FAA0058 */  lw        $t2, 0x58($sp)
/* 143208 80247448 254A0001 */  addiu     $t2, $t2, 0x1
/* 14320C 8024744C AFAA0058 */  sw        $t2, 0x58($sp)
.LJP_80247450:
/* 143210 80247450 8FAB0054 */  lw        $t3, 0x54($sp)
/* 143214 80247454 24020002 */  addiu     $v0, $zero, 0x2
/* 143218 80247458 156200DB */  bne       $t3, $v0, .LJP_802477C8
/* 14321C 8024745C 00000000 */   nop
/* 143220 80247460 8FAA0088 */  lw        $t2, 0x88($sp)
/* 143224 80247464 154000D8 */  bnez      $t2, .LJP_802477C8
/* 143228 80247468 00131400 */   sll      $v0, $s3, 16
/* 14322C 8024746C 000212C3 */  sra       $v0, $v0, 11
/* 143230 80247470 3C0B8008 */  lui       $t3, %hi(gItemTable)
/* 143234 80247474 256B78B0 */  addiu     $t3, $t3, %lo(gItemTable)
/* 143238 80247478 004B1021 */  addu      $v0, $v0, $t3
/* 14323C 8024747C 9043001A */  lbu       $v1, 0x1A($v0)
/* 143240 80247480 3C0A8009 */  lui       $t2, %hi(gMoveTable)
/* 143244 80247484 254AF030 */  addiu     $t2, $t2, %lo(gMoveTable)
/* 143248 80247488 00031080 */  sll       $v0, $v1, 2
/* 14324C 8024748C 00431021 */  addu      $v0, $v0, $v1
/* 143250 80247490 00021080 */  sll       $v0, $v0, 2
/* 143254 80247494 004A1021 */  addu      $v0, $v0, $t2
/* 143258 80247498 80530012 */  lb        $s3, 0x12($v0)
/* 14325C 8024749C 2A62000B */  slti      $v0, $s3, 0xB
/* 143260 802474A0 10400002 */  beqz      $v0, .LJP_802474AC
/* 143264 802474A4 24140001 */   addiu    $s4, $zero, 0x1
/* 143268 802474A8 24140004 */  addiu     $s4, $zero, 0x4
.LJP_802474AC:
/* 14326C 802474AC 3C04E300 */  lui       $a0, (0xE3001201 >> 16)
/* 143270 802474B0 34841201 */  ori       $a0, $a0, (0xE3001201 & 0xFFFF)
/* 143274 802474B4 3C05800A */  lui       $a1, %hi(gMainGfxPos)
/* 143278 802474B8 8CA5A64C */  lw        $a1, %lo(gMainGfxPos)($a1)
/* 14327C 802474BC 3C02DE00 */  lui       $v0, (0xDE000000 >> 16)
/* 143280 802474C0 00A0182D */  daddu     $v1, $a1, $zero
/* 143284 802474C4 24A50008 */  addiu     $a1, $a1, 0x8
/* 143288 802474C8 AC620000 */  sw        $v0, 0x0($v1)
/* 14328C 802474CC 3C028027 */  lui       $v0, %hi(PauseGfxOrbs)
/* 143290 802474D0 2442EA68 */  addiu     $v0, $v0, %lo(PauseGfxOrbs)
/* 143294 802474D4 AC620004 */  sw        $v0, 0x4($v1)
/* 143298 802474D8 24A20008 */  addiu     $v0, $a1, 0x8
/* 14329C 802474DC 3C01800A */  lui       $at, %hi(gMainGfxPos)
/* 1432A0 802474E0 AC25A64C */  sw        $a1, %lo(gMainGfxPos)($at)
/* 1432A4 802474E4 3C01800A */  lui       $at, %hi(gMainGfxPos)
/* 1432A8 802474E8 AC22A64C */  sw        $v0, %lo(gMainGfxPos)($at)
/* 1432AC 802474EC 24022000 */  addiu     $v0, $zero, 0x2000
/* 1432B0 802474F0 ACA40000 */  sw        $a0, 0x0($a1)
/* 1432B4 802474F4 ACA20004 */  sw        $v0, 0x4($a1)
/* 1432B8 802474F8 8FAB0084 */  lw        $t3, 0x84($sp)
/* 1432BC 802474FC 1560007B */  bnez      $t3, .LJP_802476EC
/* 1432C0 80247500 0000F02D */   daddu    $fp, $zero, $zero
/* 1432C4 80247504 1A60002F */  blez      $s3, .LJP_802475C4
/* 1432C8 80247508 03C0902D */   daddu    $s2, $fp, $zero
.LJP_8024750C:
/* 1432CC 8024750C 3C02800A */  lui       $v0, %hi(gMainGfxPos)
/* 1432D0 80247510 8C42A64C */  lw        $v0, %lo(gMainGfxPos)($v0)
/* 1432D4 80247514 02C0202D */  daddu     $a0, $s6, $zero
/* 1432D8 80247518 0040182D */  daddu     $v1, $v0, $zero
/* 1432DC 8024751C 3C0AFA00 */  lui       $t2, (0xFA000000 >> 16)
/* 1432E0 80247520 AC6A0000 */  sw        $t2, 0x0($v1)
/* 1432E4 80247524 8FAB0090 */  lw        $t3, 0x90($sp)
/* 1432E8 80247528 24420008 */  addiu     $v0, $v0, 0x8
/* 1432EC 8024752C 3C01800A */  lui       $at, %hi(gMainGfxPos)
/* 1432F0 80247530 AC22A64C */  sw        $v0, %lo(gMainGfxPos)($at)
/* 1432F4 80247534 0C091A52 */  jal       pause_badges_scroll_offset_x
/* 1432F8 80247538 AC6B0004 */   sw       $t3, 0x4($v1)
/* 1432FC 8024753C 8FAA0094 */  lw        $t2, 0x94($sp)
/* 143300 80247540 02A0202D */  daddu     $a0, $s5, $zero
/* 143304 80247544 024A0018 */  mult      $s2, $t2
/* 143308 80247548 245100D3 */  addiu     $s1, $v0, 0xD3
/* 14330C 8024754C 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 143310 80247550 001217C3 */  sra       $v0, $s2, 31
/* 143314 80247554 01718821 */  addu      $s1, $t3, $s1
/* 143318 80247558 00005010 */  mfhi      $t2
/* 14331C 8024755C 000A8083 */  sra       $s0, $t2, 2
/* 143320 80247560 02028023 */  subu      $s0, $s0, $v0
/* 143324 80247564 00101880 */  sll       $v1, $s0, 2
/* 143328 80247568 00701821 */  addu      $v1, $v1, $s0
/* 14332C 8024756C 00031840 */  sll       $v1, $v1, 1
/* 143330 80247570 02431823 */  subu      $v1, $s2, $v1
/* 143334 80247574 00031040 */  sll       $v0, $v1, 1
/* 143338 80247578 00431021 */  addu      $v0, $v0, $v1
/* 14333C 8024757C 00021040 */  sll       $v0, $v0, 1
/* 143340 80247580 24420001 */  addiu     $v0, $v0, 0x1
/* 143344 80247584 0C091A4E */  jal       pause_badges_scroll_offset_y
/* 143348 80247588 02228821 */   addu     $s1, $s1, $v0
/* 14334C 8024758C 0000202D */  daddu     $a0, $zero, $zero
/* 143350 80247590 0220282D */  daddu     $a1, $s1, $zero
/* 143354 80247594 24420011 */  addiu     $v0, $v0, 0x11
/* 143358 80247598 001030C0 */  sll       $a2, $s0, 3
/* 14335C 8024759C 8FAB00C8 */  lw        $t3, 0xC8($sp)
/* 143360 802475A0 00D03023 */  subu      $a2, $a2, $s0
/* 143364 802475A4 01621021 */  addu      $v0, $t3, $v0
/* 143368 802475A8 00541021 */  addu      $v0, $v0, $s4
/* 14336C 802475AC 0C091ABE */  jal       pause_badges_draw_bp_orbs
/* 143370 802475B0 00463021 */   addu     $a2, $v0, $a2
/* 143374 802475B4 26520001 */  addiu     $s2, $s2, 0x1
/* 143378 802475B8 0253102A */  slt       $v0, $s2, $s3
/* 14337C 802475BC 1440FFD3 */  bnez      $v0, .LJP_8024750C
/* 143380 802475C0 00000000 */   nop
.LJP_802475C4:
/* 143384 802475C4 3C06E200 */  lui       $a2, (0xE200001C >> 16)
/* 143388 802475C8 34C6001C */  ori       $a2, $a2, (0xE200001C & 0xFFFF)
/* 14338C 802475CC 3C050050 */  lui       $a1, (0x504340 >> 16)
/* 143390 802475D0 34A54340 */  ori       $a1, $a1, (0x504340 & 0xFFFF)
/* 143394 802475D4 0000902D */  daddu     $s2, $zero, $zero
/* 143398 802475D8 3C02E700 */  lui       $v0, (0xE7000000 >> 16)
/* 14339C 802475DC 3C04800A */  lui       $a0, %hi(gMainGfxPos)
/* 1433A0 802475E0 8C84A64C */  lw        $a0, %lo(gMainGfxPos)($a0)
/* 1433A4 802475E4 240B00FF */  addiu     $t3, $zero, 0xFF
/* 1433A8 802475E8 0080182D */  daddu     $v1, $a0, $zero
/* 1433AC 802475EC 24840008 */  addiu     $a0, $a0, 0x8
/* 1433B0 802475F0 AC620000 */  sw        $v0, 0x0($v1)
/* 1433B4 802475F4 24820008 */  addiu     $v0, $a0, 0x8
/* 1433B8 802475F8 3C01800A */  lui       $at, %hi(gMainGfxPos)
/* 1433BC 802475FC AC24A64C */  sw        $a0, %lo(gMainGfxPos)($at)
/* 1433C0 80247600 3C01800A */  lui       $at, %hi(gMainGfxPos)
/* 1433C4 80247604 AC22A64C */  sw        $v0, %lo(gMainGfxPos)($at)
/* 1433C8 80247608 24820010 */  addiu     $v0, $a0, 0x10
/* 1433CC 8024760C AC600004 */  sw        $zero, 0x4($v1)
/* 1433D0 80247610 3C0AFA00 */  lui       $t2, (0xFA000000 >> 16)
/* 1433D4 80247614 3C01800A */  lui       $at, %hi(gMainGfxPos)
/* 1433D8 80247618 AC22A64C */  sw        $v0, %lo(gMainGfxPos)($at)
/* 1433DC 8024761C 000B1400 */  sll       $v0, $t3, 16
/* 1433E0 80247620 AC8A0008 */  sw        $t2, 0x8($a0)
/* 1433E4 80247624 240A0064 */  addiu     $t2, $zero, 0x64
/* 1433E8 80247628 000A1A00 */  sll       $v1, $t2, 8
/* 1433EC 8024762C 00431025 */  or        $v0, $v0, $v1
/* 1433F0 80247630 34420080 */  ori       $v0, $v0, 0x80
/* 1433F4 80247634 AC860000 */  sw        $a2, 0x0($a0)
/* 1433F8 80247638 AC850004 */  sw        $a1, 0x4($a0)
/* 1433FC 8024763C 1A600062 */  blez      $s3, .LJP_802477C8
/* 143400 80247640 AC82000C */   sw       $v0, 0xC($a0)
.LJP_80247644:
/* 143404 80247644 8FAB006C */  lw        $t3, 0x6C($sp)
/* 143408 80247648 024B102A */  slt       $v0, $s2, $t3
/* 14340C 8024764C 50400022 */  beql      $v0, $zero, .LJP_802476D8
/* 143410 80247650 26520001 */   addiu    $s2, $s2, 0x1
/* 143414 80247654 0C091A52 */  jal       pause_badges_scroll_offset_x
/* 143418 80247658 02C0202D */   daddu    $a0, $s6, $zero
/* 14341C 8024765C 8FAA0094 */  lw        $t2, 0x94($sp)
/* 143420 80247660 02A0202D */  daddu     $a0, $s5, $zero
/* 143424 80247664 024A0018 */  mult      $s2, $t2
/* 143428 80247668 245100D3 */  addiu     $s1, $v0, 0xD3
/* 14342C 8024766C 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 143430 80247670 001217C3 */  sra       $v0, $s2, 31
/* 143434 80247674 01718821 */  addu      $s1, $t3, $s1
/* 143438 80247678 00005010 */  mfhi      $t2
/* 14343C 8024767C 000A8083 */  sra       $s0, $t2, 2
/* 143440 80247680 02028023 */  subu      $s0, $s0, $v0
/* 143444 80247684 00101880 */  sll       $v1, $s0, 2
/* 143448 80247688 00701821 */  addu      $v1, $v1, $s0
/* 14344C 8024768C 00031840 */  sll       $v1, $v1, 1
/* 143450 80247690 02431823 */  subu      $v1, $s2, $v1
/* 143454 80247694 00031040 */  sll       $v0, $v1, 1
/* 143458 80247698 00431021 */  addu      $v0, $v0, $v1
/* 14345C 8024769C 00021040 */  sll       $v0, $v0, 1
/* 143460 802476A0 24420001 */  addiu     $v0, $v0, 0x1
/* 143464 802476A4 0C091A4E */  jal       pause_badges_scroll_offset_y
/* 143468 802476A8 02228821 */   addu     $s1, $s1, $v0
/* 14346C 802476AC 24040001 */  addiu     $a0, $zero, 0x1
/* 143470 802476B0 0220282D */  daddu     $a1, $s1, $zero
/* 143474 802476B4 24420011 */  addiu     $v0, $v0, 0x11
/* 143478 802476B8 001030C0 */  sll       $a2, $s0, 3
/* 14347C 802476BC 8FAB00C8 */  lw        $t3, 0xC8($sp)
/* 143480 802476C0 00D03023 */  subu      $a2, $a2, $s0
/* 143484 802476C4 01621021 */  addu      $v0, $t3, $v0
/* 143488 802476C8 00541021 */  addu      $v0, $v0, $s4
/* 14348C 802476CC 0C091ABE */  jal       pause_badges_draw_bp_orbs
/* 143490 802476D0 00463021 */   addu     $a2, $v0, $a2
/* 143494 802476D4 26520001 */  addiu     $s2, $s2, 0x1
.LJP_802476D8:
/* 143498 802476D8 0253102A */  slt       $v0, $s2, $s3
/* 14349C 802476DC 1440FFD9 */  bnez      $v0, .LJP_80247644
/* 1434A0 802476E0 00000000 */   nop
/* 1434A4 802476E4 08091DF2 */  j         .LJP_802477C8
/* 1434A8 802476E8 00000000 */   nop
.LJP_802476EC:
/* 1434AC 802476EC 3C0300FF */  lui       $v1, (0xFF64FF >> 16)
/* 1434B0 802476F0 346364FF */  ori       $v1, $v1, (0xFF64FF & 0xFFFF)
/* 1434B4 802476F4 0000902D */  daddu     $s2, $zero, $zero
/* 1434B8 802476F8 24A20010 */  addiu     $v0, $a1, 0x10
/* 1434BC 802476FC 3C0AFA00 */  lui       $t2, (0xFA000000 >> 16)
/* 1434C0 80247700 3C01800A */  lui       $at, %hi(gMainGfxPos)
/* 1434C4 80247704 AC22A64C */  sw        $v0, %lo(gMainGfxPos)($at)
/* 1434C8 80247708 ACAA0008 */  sw        $t2, 0x8($a1)
/* 1434CC 8024770C 1A600025 */  blez      $s3, .LJP_802477A4
/* 1434D0 80247710 ACA3000C */   sw       $v1, 0xC($a1)
.LJP_80247714:
/* 1434D4 80247714 0C091A52 */  jal       pause_badges_scroll_offset_x
/* 1434D8 80247718 02C0202D */   daddu    $a0, $s6, $zero
/* 1434DC 8024771C 8FAA0094 */  lw        $t2, 0x94($sp)
/* 1434E0 80247720 02A0202D */  daddu     $a0, $s5, $zero
/* 1434E4 80247724 024A0018 */  mult      $s2, $t2
/* 1434E8 80247728 245100D3 */  addiu     $s1, $v0, 0xD3
/* 1434EC 8024772C 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 1434F0 80247730 001217C3 */  sra       $v0, $s2, 31
/* 1434F4 80247734 01718821 */  addu      $s1, $t3, $s1
/* 1434F8 80247738 00005010 */  mfhi      $t2
/* 1434FC 8024773C 000A8083 */  sra       $s0, $t2, 2
/* 143500 80247740 02028023 */  subu      $s0, $s0, $v0
/* 143504 80247744 00101880 */  sll       $v1, $s0, 2
/* 143508 80247748 00701821 */  addu      $v1, $v1, $s0
/* 14350C 8024774C 00031840 */  sll       $v1, $v1, 1
/* 143510 80247750 02431823 */  subu      $v1, $s2, $v1
/* 143514 80247754 00031040 */  sll       $v0, $v1, 1
/* 143518 80247758 00431021 */  addu      $v0, $v0, $v1
/* 14351C 8024775C 00021040 */  sll       $v0, $v0, 1
/* 143520 80247760 24420001 */  addiu     $v0, $v0, 0x1
/* 143524 80247764 0C091A4E */  jal       pause_badges_scroll_offset_y
/* 143528 80247768 02228821 */   addu     $s1, $s1, $v0
/* 14352C 8024776C 24040002 */  addiu     $a0, $zero, 0x2
/* 143530 80247770 0220282D */  daddu     $a1, $s1, $zero
/* 143534 80247774 24420011 */  addiu     $v0, $v0, 0x11
/* 143538 80247778 001030C0 */  sll       $a2, $s0, 3
/* 14353C 8024777C 8FAB00C8 */  lw        $t3, 0xC8($sp)
/* 143540 80247780 00D03023 */  subu      $a2, $a2, $s0
/* 143544 80247784 01621021 */  addu      $v0, $t3, $v0
/* 143548 80247788 00541021 */  addu      $v0, $v0, $s4
/* 14354C 8024778C 0C091ABE */  jal       pause_badges_draw_bp_orbs
/* 143550 80247790 00463021 */   addu     $a2, $v0, $a2
/* 143554 80247794 26520001 */  addiu     $s2, $s2, 0x1
/* 143558 80247798 0253102A */  slt       $v0, $s2, $s3
/* 14355C 8024779C 1440FFDD */  bnez      $v0, .LJP_80247714
/* 143560 802477A0 00000000 */   nop
.LJP_802477A4:
/* 143564 802477A4 3C02800A */  lui       $v0, %hi(gMainGfxPos)
/* 143568 802477A8 8C42A64C */  lw        $v0, %lo(gMainGfxPos)($v0)
/* 14356C 802477AC 0040182D */  daddu     $v1, $v0, $zero
/* 143570 802477B0 24420008 */  addiu     $v0, $v0, 0x8
/* 143574 802477B4 3C01800A */  lui       $at, %hi(gMainGfxPos)
/* 143578 802477B8 AC22A64C */  sw        $v0, %lo(gMainGfxPos)($at)
/* 14357C 802477BC 3C02E700 */  lui       $v0, (0xE7000000 >> 16)
/* 143580 802477C0 AC620000 */  sw        $v0, 0x0($v1)
/* 143584 802477C4 AC600004 */  sw        $zero, 0x4($v1)
.LJP_802477C8:
/* 143588 802477C8 8FAA0078 */  lw        $t2, 0x78($sp)
/* 14358C 802477CC 8D420008 */  lw        $v0, 0x8($t2)
/* 143590 802477D0 26F70001 */  addiu     $s7, $s7, 0x1
/* 143594 802477D4 02E2102A */  slt       $v0, $s7, $v0
/* 143598 802477D8 1440FDBA */  bnez      $v0, .LJP_80246EC4
/* 14359C 802477DC 00000000 */   nop
.LJP_802477E0:
/* 1435A0 802477E0 8FAB0050 */  lw        $t3, 0x50($sp)
/* 1435A4 802477E4 256B0001 */  addiu     $t3, $t3, 0x1
/* 1435A8 802477E8 29620014 */  slti      $v0, $t3, 0x14
/* 1435AC 802477EC 1440FD9E */  bnez      $v0, .LJP_80246E68
/* 1435B0 802477F0 AFAB0050 */   sw       $t3, 0x50($sp)
.LJP_802477F4:
/* 1435B4 802477F4 8FAA0054 */  lw        $t2, 0x54($sp)
/* 1435B8 802477F8 254A0001 */  addiu     $t2, $t2, 0x1
/* 1435BC 802477FC 29420003 */  slti      $v0, $t2, 0x3
/* 1435C0 80247800 1440FD98 */  bnez      $v0, .LJP_80246E64
/* 1435C4 80247804 AFAA0054 */   sw       $t2, 0x54($sp)
/* 1435C8 80247808 3C09800A */  lui       $t1, %hi(gMainGfxPos)
/* 1435CC 8024780C 2529A64C */  addiu     $t1, $t1, %lo(gMainGfxPos)
/* 1435D0 80247810 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 1435D4 80247814 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 1435D8 80247818 8D250000 */  lw        $a1, 0x0($t1)
/* 1435DC 8024781C 25640001 */  addiu     $a0, $t3, 0x1
/* 1435E0 80247820 25460001 */  addiu     $a2, $t2, 0x1
/* 1435E4 80247824 00A0182D */  daddu     $v1, $a1, $zero
/* 1435E8 80247828 8FAA00CC */  lw        $t2, 0xCC($sp)
/* 1435EC 8024782C 24A50008 */  addiu     $a1, $a1, 0x8
/* 1435F0 80247830 016A1021 */  addu      $v0, $t3, $t2
/* 1435F4 80247834 8FAB00C8 */  lw        $t3, 0xC8($sp)
/* 1435F8 80247838 8FAA00D0 */  lw        $t2, 0xD0($sp)
/* 1435FC 8024783C 2447FFFF */  addiu     $a3, $v0, -0x1
/* 143600 80247840 016A1021 */  addu      $v0, $t3, $t2
/* 143604 80247844 2448FFFF */  addiu     $t0, $v0, -0x1
/* 143608 80247848 3C02E700 */  lui       $v0, (0xE7000000 >> 16)
/* 14360C 8024784C AD250000 */  sw        $a1, 0x0($t1)
/* 143610 80247850 AC620000 */  sw        $v0, 0x0($v1)
/* 143614 80247854 1C800002 */  bgtz      $a0, .LJP_80247860
/* 143618 80247858 AC600004 */   sw       $zero, 0x4($v1)
/* 14361C 8024785C 24040001 */  addiu     $a0, $zero, 0x1
.LJP_80247860:
/* 143620 80247860 58C00001 */  blezl     $a2, .LJP_80247868
/* 143624 80247864 24060001 */   addiu    $a2, $zero, 0x1
.LJP_80247868:
/* 143628 80247868 18E002C5 */  blez      $a3, .LJP_80248380
/* 14362C 8024786C 00000000 */   nop
/* 143630 80247870 190002C3 */  blez      $t0, .LJP_80248380
/* 143634 80247874 2882013F */   slti     $v0, $a0, 0x13F
/* 143638 80247878 104002C1 */  beqz      $v0, .LJP_80248380
/* 14363C 8024787C 28C200EF */   slti     $v0, $a2, 0xEF
/* 143640 80247880 104002BF */  beqz      $v0, .LJP_80248380
/* 143644 80247884 28E2013F */   slti     $v0, $a3, 0x13F
/* 143648 80247888 50400001 */  beql      $v0, $zero, .LJP_80247890
/* 14364C 8024788C 2407013F */   addiu    $a3, $zero, 0x13F
.LJP_80247890:
/* 143650 80247890 290200EF */  slti      $v0, $t0, 0xEF
/* 143654 80247894 50400001 */  beql      $v0, $zero, .LJP_8024789C
/* 143658 80247898 240800EF */   addiu    $t0, $zero, 0xEF
.LJP_8024789C:
/* 14365C 8024789C 3C014080 */  lui       $at, (0x40800000 >> 16)
/* 143660 802478A0 44812000 */  mtc1      $at, $f4
/* 143664 802478A4 44840000 */  mtc1      $a0, $f0
/* 143668 802478A8 00000000 */  nop
/* 14366C 802478AC 46800020 */  cvt.s.w   $f0, $f0
/* 143670 802478B0 46040002 */  mul.s     $f0, $f0, $f4
/* 143674 802478B4 00000000 */  nop
/* 143678 802478B8 24A20008 */  addiu     $v0, $a1, 0x8
/* 14367C 802478BC 44861000 */  mtc1      $a2, $f2
/* 143680 802478C0 00000000 */  nop
/* 143684 802478C4 468010A0 */  cvt.s.w   $f2, $f2
/* 143688 802478C8 3C04ED00 */  lui       $a0, (0xED000000 >> 16)
/* 14368C 802478CC 46041082 */  mul.s     $f2, $f2, $f4
/* 143690 802478D0 00000000 */  nop
/* 143694 802478D4 AD220000 */  sw        $v0, 0x0($t1)
/* 143698 802478D8 4600018D */  trunc.w.s $f6, $f0
/* 14369C 802478DC 44023000 */  mfc1      $v0, $f6
/* 1436A0 802478E0 00000000 */  nop
/* 1436A4 802478E4 30420FFF */  andi      $v0, $v0, 0xFFF
/* 1436A8 802478E8 00021300 */  sll       $v0, $v0, 12
/* 1436AC 802478EC 4600118D */  trunc.w.s $f6, $f2
/* 1436B0 802478F0 44033000 */  mfc1      $v1, $f6
/* 1436B4 802478F4 44871000 */  mtc1      $a3, $f2
/* 1436B8 802478F8 00000000 */  nop
/* 1436BC 802478FC 468010A0 */  cvt.s.w   $f2, $f2
/* 1436C0 80247900 46041082 */  mul.s     $f2, $f2, $f4
/* 1436C4 80247904 00000000 */  nop
/* 1436C8 80247908 30630FFF */  andi      $v1, $v1, 0xFFF
/* 1436CC 8024790C 00641825 */  or        $v1, $v1, $a0
/* 1436D0 80247910 00431025 */  or        $v0, $v0, $v1
/* 1436D4 80247914 44880000 */  mtc1      $t0, $f0
/* 1436D8 80247918 00000000 */  nop
/* 1436DC 8024791C 46800020 */  cvt.s.w   $f0, $f0
/* 1436E0 80247920 46040002 */  mul.s     $f0, $f0, $f4
/* 1436E4 80247924 00000000 */  nop
/* 1436E8 80247928 ACA20000 */  sw        $v0, 0x0($a1)
/* 1436EC 8024792C 4600118D */  trunc.w.s $f6, $f2
/* 1436F0 80247930 44023000 */  mfc1      $v0, $f6
/* 1436F4 80247934 00000000 */  nop
/* 1436F8 80247938 30420FFF */  andi      $v0, $v0, 0xFFF
/* 1436FC 8024793C 00021300 */  sll       $v0, $v0, 12
/* 143700 80247940 4600018D */  trunc.w.s $f6, $f0
/* 143704 80247944 44033000 */  mfc1      $v1, $f6
/* 143708 80247948 00000000 */  nop
/* 14370C 8024794C 30630FFF */  andi      $v1, $v1, 0xFFF
/* 143710 80247950 00431025 */  or        $v0, $v0, $v1
/* 143714 80247954 3C038027 */  lui       $v1, %hi(gPauseMenuCurrentTab)
/* 143718 80247958 8063F7A4 */  lb        $v1, %lo(gPauseMenuCurrentTab)($v1)
/* 14371C 8024795C ACA20004 */  sw        $v0, 0x4($a1)
/* 143720 80247960 24020002 */  addiu     $v0, $zero, 0x2
/* 143724 80247964 1462002A */  bne       $v1, $v0, .LJP_80247A10
/* 143728 80247968 24020001 */   addiu    $v0, $zero, 0x1
/* 14372C 8024796C 3C038027 */  lui       $v1, %hi(gPauseBadgesLevel)
/* 143730 80247970 8C63FA58 */  lw        $v1, %lo(gPauseBadgesLevel)($v1)
/* 143734 80247974 14620026 */  bne       $v1, $v0, .LJP_80247A10
/* 143738 80247978 00000000 */   nop
/* 14373C 8024797C 3C118027 */  lui       $s1, %hi(gPauseBadgesCurrentPage)
/* 143740 80247980 2631F940 */  addiu     $s1, $s1, %lo(gPauseBadgesCurrentPage)
/* 143744 80247984 8E220000 */  lw        $v0, 0x0($s1)
/* 143748 80247988 1840000E */  blez      $v0, .LJP_802479C4
/* 14374C 8024798C 24420001 */   addiu    $v0, $v0, 0x1
/* 143750 80247990 3C108027 */  lui       $s0, %hi(gPauseBadgesIconIDs)
/* 143754 80247994 2610FA68 */  addiu     $s0, $s0, %lo(gPauseBadgesIconIDs)
/* 143758 80247998 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 14375C 8024799C 8E040044 */  lw        $a0, 0x44($s0)
/* 143760 802479A0 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 143764 802479A4 25650116 */  addiu     $a1, $t3, 0x116
/* 143768 802479A8 0C05268D */  jal       hud_element_set_render_pos
/* 14376C 802479AC 2546000E */   addiu    $a2, $t2, 0xE
/* 143770 802479B0 8E040044 */  lw        $a0, 0x44($s0)
/* 143774 802479B4 0C052624 */  jal       hud_element_draw_without_clipping
/* 143778 802479B8 00000000 */   nop
/* 14377C 802479BC 8E220000 */  lw        $v0, 0x0($s1)
/* 143780 802479C0 24420001 */  addiu     $v0, $v0, 0x1
.LJP_802479C4:
/* 143784 802479C4 00021840 */  sll       $v1, $v0, 1
/* 143788 802479C8 00621821 */  addu      $v1, $v1, $v0
/* 14378C 802479CC 00031880 */  sll       $v1, $v1, 2
/* 143790 802479D0 3C028027 */  lui       $v0, %hi(gPauseBadgesPages)
/* 143794 802479D4 00431021 */  addu      $v0, $v0, $v1
/* 143798 802479D8 9042F948 */  lbu       $v0, %lo(gPauseBadgesPages)($v0)
/* 14379C 802479DC 1040000C */  beqz      $v0, .LJP_80247A10
/* 1437A0 802479E0 00000000 */   nop
/* 1437A4 802479E4 3C108027 */  lui       $s0, %hi(gPauseBadgesIconIDs)
/* 1437A8 802479E8 2610FA68 */  addiu     $s0, $s0, %lo(gPauseBadgesIconIDs)
/* 1437AC 802479EC 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 1437B0 802479F0 8E040048 */  lw        $a0, 0x48($s0)
/* 1437B4 802479F4 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 1437B8 802479F8 25650116 */  addiu     $a1, $t3, 0x116
/* 1437BC 802479FC 0C05268D */  jal       hud_element_set_render_pos
/* 1437C0 80247A00 25460092 */   addiu    $a2, $t2, 0x92
/* 1437C4 80247A04 8E040048 */  lw        $a0, 0x48($s0)
/* 1437C8 80247A08 0C052624 */  jal       hud_element_draw_without_clipping
/* 1437CC 80247A0C 00000000 */   nop
.LJP_80247A10:
/* 1437D0 80247A10 3C108027 */  lui       $s0, %hi(gPauseBadgesIconIDs)
/* 1437D4 80247A14 2610FA68 */  addiu     $s0, $s0, %lo(gPauseBadgesIconIDs)
/* 1437D8 80247A18 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 1437DC 80247A1C 8E040040 */  lw        $a0, 0x40($s0)
/* 1437E0 80247A20 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 1437E4 80247A24 2565002B */  addiu     $a1, $t3, 0x2B
/* 1437E8 80247A28 0C05268D */  jal       hud_element_set_render_pos
/* 1437EC 80247A2C 25460051 */   addiu    $a2, $t2, 0x51
/* 1437F0 80247A30 8E040040 */  lw        $a0, 0x40($s0)
/* 1437F4 80247A34 0C052624 */  jal       hud_element_draw_without_clipping
/* 1437F8 80247A38 2413000A */   addiu    $s3, $zero, 0xA
/* 1437FC 80247A3C 0C09396C */  jal       pause_get_menu_msg
/* 143800 80247A40 24040046 */   addiu    $a0, $zero, 0x46
/* 143804 80247A44 0040202D */  daddu     $a0, $v0, $zero
/* 143808 80247A48 240700FF */  addiu     $a3, $zero, 0xFF
/* 14380C 80247A4C 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 143810 80247A50 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 143814 80247A54 24020001 */  addiu     $v0, $zero, 0x1
/* 143818 80247A58 AFB30010 */  sw        $s3, 0x10($sp)
/* 14381C 80247A5C AFA20014 */  sw        $v0, 0x14($sp)
/* 143820 80247A60 25650010 */  addiu     $a1, $t3, 0x10
/* 143824 80247A64 2550004A */  addiu     $s0, $t2, 0x4A
/* 143828 80247A68 0C04ADC4 */  jal       draw_msg
/* 14382C 80247A6C 0200302D */   daddu    $a2, $s0, $zero
/* 143830 80247A70 0200302D */  daddu     $a2, $s0, $zero
/* 143834 80247A74 24070001 */  addiu     $a3, $zero, 0x1
/* 143838 80247A78 241500FF */  addiu     $s5, $zero, 0xFF
/* 14383C 80247A7C 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 143840 80247A80 3C048011 */  lui       $a0, %hi(gPlayerData + 0x8)
/* 143844 80247A84 8084F458 */  lb        $a0, %lo(gPlayerData + 0x8)($a0)
/* 143848 80247A88 24140003 */  addiu     $s4, $zero, 0x3
/* 14384C 80247A8C AFB30010 */  sw        $s3, 0x10($sp)
/* 143850 80247A90 AFB50014 */  sw        $s5, 0x14($sp)
/* 143854 80247A94 AFB40018 */  sw        $s4, 0x18($sp)
/* 143858 80247A98 0C04B22C */  jal       draw_number
/* 14385C 80247A9C 25650045 */   addiu    $a1, $t3, 0x45
/* 143860 80247AA0 0C090FEC */  jal       pause_get_total_equipped_bp_cost
/* 143864 80247AA4 0000902D */   daddu    $s2, $zero, $zero
/* 143868 80247AA8 3C056666 */  lui       $a1, (0x66666667 >> 16)
/* 14386C 80247AAC 3C048011 */  lui       $a0, %hi(gPlayerData + 0x8)
/* 143870 80247AB0 8084F458 */  lb        $a0, %lo(gPlayerData + 0x8)($a0)
/* 143874 80247AB4 34A56667 */  ori       $a1, $a1, (0x66666667 & 0xFFFF)
/* 143878 80247AB8 2483FFFF */  addiu     $v1, $a0, -0x1
/* 14387C 80247ABC 00650018 */  mult      $v1, $a1
/* 143880 80247AC0 00828823 */  subu      $s1, $a0, $v0
/* 143884 80247AC4 00031FC3 */  sra       $v1, $v1, 31
/* 143888 80247AC8 00005010 */  mfhi      $t2
/* 14388C 80247ACC 000A1083 */  sra       $v0, $t2, 2
/* 143890 80247AD0 00431023 */  subu      $v0, $v0, $v1
/* 143894 80247AD4 02828004 */  sllv      $s0, $v0, $s4
/* 143898 80247AD8 0233102A */  slt       $v0, $s1, $s3
/* 14389C 80247ADC 54400001 */  bnel      $v0, $zero, .LJP_80247AE4
/* 1438A0 80247AE0 2412FFFC */   addiu    $s2, $zero, -0x4
.LJP_80247AE4:
/* 1438A4 80247AE4 24040007 */  addiu     $a0, $zero, 0x7
/* 1438A8 80247AE8 26100064 */  addiu     $s0, $s0, 0x64
/* 1438AC 80247AEC 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 1438B0 80247AF0 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 1438B4 80247AF4 2565000F */  addiu     $a1, $t3, 0xF
/* 1438B8 80247AF8 01508021 */  addu      $s0, $t2, $s0
/* 1438BC 80247AFC 0C093971 */  jal       pause_draw_menu_label
/* 1438C0 80247B00 0200302D */   daddu    $a2, $s0, $zero
/* 1438C4 80247B04 0220202D */  daddu     $a0, $s1, $zero
/* 1438C8 80247B08 2645003E */  addiu     $a1, $s2, 0x3E
/* 1438CC 80247B0C 0200302D */  daddu     $a2, $s0, $zero
/* 1438D0 80247B10 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 1438D4 80247B14 24070001 */  addiu     $a3, $zero, 0x1
/* 1438D8 80247B18 AFB30010 */  sw        $s3, 0x10($sp)
/* 1438DC 80247B1C AFB50014 */  sw        $s5, 0x14($sp)
/* 1438E0 80247B20 AFB40018 */  sw        $s4, 0x18($sp)
/* 1438E4 80247B24 0C04B22C */  jal       draw_number
/* 1438E8 80247B28 01652821 */   addu     $a1, $t3, $a1
/* 1438EC 80247B2C 3C05E300 */  lui       $a1, (0xE3001201 >> 16)
/* 1438F0 80247B30 34A51201 */  ori       $a1, $a1, (0xE3001201 & 0xFFFF)
/* 1438F4 80247B34 3C06800A */  lui       $a2, %hi(gMainGfxPos)
/* 1438F8 80247B38 24C6A64C */  addiu     $a2, $a2, %lo(gMainGfxPos)
/* 1438FC 80247B3C 0000882D */  daddu     $s1, $zero, $zero
/* 143900 80247B40 3C02DE00 */  lui       $v0, (0xDE000000 >> 16)
/* 143904 80247B44 0220B02D */  daddu     $s6, $s1, $zero
/* 143908 80247B48 8CC30000 */  lw        $v1, 0x0($a2)
/* 14390C 80247B4C 241700FF */  addiu     $s7, $zero, 0xFF
/* 143910 80247B50 0060202D */  daddu     $a0, $v1, $zero
/* 143914 80247B54 24630008 */  addiu     $v1, $v1, 0x8
/* 143918 80247B58 ACC30000 */  sw        $v1, 0x0($a2)
/* 14391C 80247B5C 3C108011 */  lui       $s0, %hi(gPlayerData + 0x8)
/* 143920 80247B60 8210F458 */  lb        $s0, %lo(gPlayerData + 0x8)($s0)
/* 143924 80247B64 241E0064 */  addiu     $fp, $zero, 0x64
/* 143928 80247B68 AC820000 */  sw        $v0, 0x0($a0)
/* 14392C 80247B6C 3C028027 */  lui       $v0, %hi(PauseGfxOrbs)
/* 143930 80247B70 2442EA68 */  addiu     $v0, $v0, %lo(PauseGfxOrbs)
/* 143934 80247B74 AC820004 */  sw        $v0, 0x4($a0)
/* 143938 80247B78 24620008 */  addiu     $v0, $v1, 0x8
/* 14393C 80247B7C ACC20000 */  sw        $v0, 0x0($a2)
/* 143940 80247B80 24022000 */  addiu     $v0, $zero, 0x2000
/* 143944 80247B84 AC650000 */  sw        $a1, 0x0($v1)
/* 143948 80247B88 1A000026 */  blez      $s0, .LJP_80247C24
/* 14394C 80247B8C AC620004 */   sw       $v0, 0x4($v1)
/* 143950 80247B90 00C0902D */  daddu     $s2, $a2, $zero
/* 143954 80247B94 3C15FA00 */  lui       $s5, (0xFA000000 >> 16)
/* 143958 80247B98 3C14E3E3 */  lui       $s4, (0xE3E3E3FF >> 16)
/* 14395C 80247B9C 3694E3FF */  ori       $s4, $s4, (0xE3E3E3FF & 0xFFFF)
/* 143960 80247BA0 3C136666 */  lui       $s3, (0x66666667 >> 16)
/* 143964 80247BA4 36736667 */  ori       $s3, $s3, (0x66666667 & 0xFFFF)
/* 143968 80247BA8 0000202D */  daddu     $a0, $zero, $zero
.LJP_80247BAC:
/* 14396C 80247BAC 8E420000 */  lw        $v0, 0x0($s2)
/* 143970 80247BB0 02330018 */  mult      $s1, $s3
/* 143974 80247BB4 0040182D */  daddu     $v1, $v0, $zero
/* 143978 80247BB8 24420008 */  addiu     $v0, $v0, 0x8
/* 14397C 80247BBC AE420000 */  sw        $v0, 0x0($s2)
/* 143980 80247BC0 001117C3 */  sra       $v0, $s1, 31
/* 143984 80247BC4 AC750000 */  sw        $s5, 0x0($v1)
/* 143988 80247BC8 AC740004 */  sw        $s4, 0x4($v1)
/* 14398C 80247BCC 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 143990 80247BD0 00005010 */  mfhi      $t2
/* 143994 80247BD4 000A3083 */  sra       $a2, $t2, 2
/* 143998 80247BD8 00C23023 */  subu      $a2, $a2, $v0
/* 14399C 80247BDC 00061080 */  sll       $v0, $a2, 2
/* 1439A0 80247BE0 00461021 */  addu      $v0, $v0, $a2
/* 1439A4 80247BE4 00021040 */  sll       $v0, $v0, 1
/* 1439A8 80247BE8 02221023 */  subu      $v0, $s1, $v0
/* 1439AC 80247BEC 00022840 */  sll       $a1, $v0, 1
/* 1439B0 80247BF0 00A22821 */  addu      $a1, $a1, $v0
/* 1439B4 80247BF4 00052840 */  sll       $a1, $a1, 1
/* 1439B8 80247BF8 24A5000B */  addiu     $a1, $a1, 0xB
/* 1439BC 80247BFC 01652821 */  addu      $a1, $t3, $a1
/* 1439C0 80247C00 000630C0 */  sll       $a2, $a2, 3
/* 1439C4 80247C04 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 1439C8 80247C08 24C6005C */  addiu     $a2, $a2, 0x5C
/* 1439CC 80247C0C 0C091ABE */  jal       pause_badges_draw_bp_orbs
/* 1439D0 80247C10 01463021 */   addu     $a2, $t2, $a2
/* 1439D4 80247C14 26310001 */  addiu     $s1, $s1, 0x1
/* 1439D8 80247C18 0230102A */  slt       $v0, $s1, $s0
/* 1439DC 80247C1C 1440FFE3 */  bnez      $v0, .LJP_80247BAC
/* 1439E0 80247C20 0000202D */   daddu    $a0, $zero, $zero
.LJP_80247C24:
/* 1439E4 80247C24 3C05800A */  lui       $a1, %hi(gMainGfxPos)
/* 1439E8 80247C28 24A5A64C */  addiu     $a1, $a1, %lo(gMainGfxPos)
/* 1439EC 80247C2C 8CA40000 */  lw        $a0, 0x0($a1)
/* 1439F0 80247C30 3C02E700 */  lui       $v0, (0xE7000000 >> 16)
/* 1439F4 80247C34 0080182D */  daddu     $v1, $a0, $zero
/* 1439F8 80247C38 24840008 */  addiu     $a0, $a0, 0x8
/* 1439FC 80247C3C ACA40000 */  sw        $a0, 0x0($a1)
/* 143A00 80247C40 AC620000 */  sw        $v0, 0x0($v1)
/* 143A04 80247C44 AC600004 */  sw        $zero, 0x4($v1)
/* 143A08 80247C48 8FAB0074 */  lw        $t3, 0x74($sp)
/* 143A0C 80247C4C 11600089 */  beqz      $t3, .LJP_80247E74
/* 143A10 80247C50 24820008 */   addiu    $v0, $a0, 0x8
/* 143A14 80247C54 ACA20000 */  sw        $v0, 0x0($a1)
/* 143A18 80247C58 3C02FA00 */  lui       $v0, (0xFA000000 >> 16)
/* 143A1C 80247C5C AC820000 */  sw        $v0, 0x0($a0)
/* 143A20 80247C60 00171400 */  sll       $v0, $s7, 16
/* 143A24 80247C64 001E1A00 */  sll       $v1, $fp, 8
/* 143A28 80247C68 00431025 */  or        $v0, $v0, $v1
/* 143A2C 80247C6C 344200FF */  ori       $v0, $v0, 0xFF
/* 143A30 80247C70 AC820004 */  sw        $v0, 0x4($a0)
/* 143A34 80247C74 8FAA006C */  lw        $t2, 0x6C($sp)
/* 143A38 80247C78 8FAB0070 */  lw        $t3, 0x70($sp)
/* 143A3C 80247C7C 014B1023 */  subu      $v0, $t2, $t3
/* 143A40 80247C80 1840001D */  blez      $v0, .LJP_80247CF8
/* 143A44 80247C84 0000882D */   daddu    $s1, $zero, $zero
/* 143A48 80247C88 3C126666 */  lui       $s2, (0x66666667 >> 16)
/* 143A4C 80247C8C 36526667 */  ori       $s2, $s2, (0x66666667 & 0xFFFF)
/* 143A50 80247C90 0040802D */  daddu     $s0, $v0, $zero
/* 143A54 80247C94 02320018 */  mult      $s1, $s2
.LJP_80247C98:
/* 143A58 80247C98 24040002 */  addiu     $a0, $zero, 0x2
/* 143A5C 80247C9C 001117C3 */  sra       $v0, $s1, 31
/* 143A60 80247CA0 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 143A64 80247CA4 00005010 */  mfhi      $t2
/* 143A68 80247CA8 008A3007 */  srav      $a2, $t2, $a0
/* 143A6C 80247CAC 00C23023 */  subu      $a2, $a2, $v0
/* 143A70 80247CB0 00861004 */  sllv      $v0, $a2, $a0
/* 143A74 80247CB4 00461021 */  addu      $v0, $v0, $a2
/* 143A78 80247CB8 00021040 */  sll       $v0, $v0, 1
/* 143A7C 80247CBC 02221023 */  subu      $v0, $s1, $v0
/* 143A80 80247CC0 00022840 */  sll       $a1, $v0, 1
/* 143A84 80247CC4 00A22821 */  addu      $a1, $a1, $v0
/* 143A88 80247CC8 00052840 */  sll       $a1, $a1, 1
/* 143A8C 80247CCC 24A5000B */  addiu     $a1, $a1, 0xB
/* 143A90 80247CD0 01652821 */  addu      $a1, $t3, $a1
/* 143A94 80247CD4 000630C0 */  sll       $a2, $a2, 3
/* 143A98 80247CD8 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 143A9C 80247CDC 24C6005C */  addiu     $a2, $a2, 0x5C
/* 143AA0 80247CE0 0C091ABE */  jal       pause_badges_draw_bp_orbs
/* 143AA4 80247CE4 01463021 */   addu     $a2, $t2, $a2
/* 143AA8 80247CE8 26310001 */  addiu     $s1, $s1, 0x1
/* 143AAC 80247CEC 0230102A */  slt       $v0, $s1, $s0
/* 143AB0 80247CF0 1440FFE9 */  bnez      $v0, .LJP_80247C98
/* 143AB4 80247CF4 02320018 */   mult     $s1, $s2
.LJP_80247CF8:
/* 143AB8 80247CF8 3C10800A */  lui       $s0, %hi(gMainGfxPos)
/* 143ABC 80247CFC 2610A64C */  addiu     $s0, $s0, %lo(gMainGfxPos)
/* 143AC0 80247D00 3C02E700 */  lui       $v0, (0xE7000000 >> 16)
/* 143AC4 80247D04 8E030000 */  lw        $v1, 0x0($s0)
/* 143AC8 80247D08 8FAB006C */  lw        $t3, 0x6C($sp)
/* 143ACC 80247D0C 8FAA0070 */  lw        $t2, 0x70($sp)
/* 143AD0 80247D10 3C058007 */  lui       $a1, %hi(gGameStatusPtr)
/* 143AD4 80247D14 8CA5417C */  lw        $a1, %lo(gGameStatusPtr)($a1)
/* 143AD8 80247D18 016A8823 */  subu      $s1, $t3, $t2
/* 143ADC 80247D1C 0060202D */  daddu     $a0, $v1, $zero
/* 143AE0 80247D20 AC820000 */  sw        $v0, 0x0($a0)
/* 143AE4 80247D24 AC800004 */  sw        $zero, 0x4($a0)
/* 143AE8 80247D28 94A40134 */  lhu       $a0, 0x134($a1)
/* 143AEC 80247D2C 24630008 */  addiu     $v1, $v1, 0x8
/* 143AF0 80247D30 00041100 */  sll       $v0, $a0, 4
/* 143AF4 80247D34 00441023 */  subu      $v0, $v0, $a0
/* 143AF8 80247D38 44826000 */  mtc1      $v0, $f12
/* 143AFC 80247D3C 00000000 */  nop
/* 143B00 80247D40 46806320 */  cvt.s.w   $f12, $f12
/* 143B04 80247D44 0C00A8AB */  jal       sin_deg
/* 143B08 80247D48 AE030000 */   sw       $v1, 0x0($s0)
/* 143B0C 80247D4C 3C04E200 */  lui       $a0, (0xE200001C >> 16)
/* 143B10 80247D50 3484001C */  ori       $a0, $a0, (0xE200001C & 0xFFFF)
/* 143B14 80247D54 3C030050 */  lui       $v1, (0x504340 >> 16)
/* 143B18 80247D58 34634340 */  ori       $v1, $v1, (0x504340 & 0xFFFF)
/* 143B1C 80247D5C 3C013F80 */  lui       $at, (0x3F800000 >> 16)
/* 143B20 80247D60 44811000 */  mtc1      $at, $f2
/* 143B24 80247D64 8E050000 */  lw        $a1, 0x0($s0)
/* 143B28 80247D68 46020000 */  add.s     $f0, $f0, $f2
/* 143B2C 80247D6C 00A0102D */  daddu     $v0, $a1, $zero
/* 143B30 80247D70 3C018027 */  lui       $at, %hi(D_JP_8026F680)
/* 143B34 80247D74 D422F680 */  ldc1      $f2, %lo(D_JP_8026F680)($at)
/* 143B38 80247D78 46000021 */  cvt.d.s   $f0, $f0
/* 143B3C 80247D7C 46220002 */  mul.d     $f0, $f0, $f2
/* 143B40 80247D80 00000000 */  nop
/* 143B44 80247D84 24A50008 */  addiu     $a1, $a1, 0x8
/* 143B48 80247D88 AE050000 */  sw        $a1, 0x0($s0)
/* 143B4C 80247D8C AC440000 */  sw        $a0, 0x0($v0)
/* 143B50 80247D90 AC430004 */  sw        $v1, 0x4($v0)
/* 143B54 80247D94 3C013FE0 */  lui       $at, (0x3FE00000 >> 16)
/* 143B58 80247D98 44811800 */  mtc1      $at, $f3
/* 143B5C 80247D9C 44801000 */  mtc1      $zero, $f2
/* 143B60 80247DA0 24A20008 */  addiu     $v0, $a1, 0x8
/* 143B64 80247DA4 AE020000 */  sw        $v0, 0x0($s0)
/* 143B68 80247DA8 46220000 */  add.d     $f0, $f0, $f2
/* 143B6C 80247DAC 3C02FA00 */  lui       $v0, (0xFA000000 >> 16)
/* 143B70 80247DB0 3C01437F */  lui       $at, (0x437F0000 >> 16)
/* 143B74 80247DB4 44811000 */  mtc1      $at, $f2
/* 143B78 80247DB8 46200020 */  cvt.s.d   $f0, $f0
/* 143B7C 80247DBC 46020002 */  mul.s     $f0, $f0, $f2
/* 143B80 80247DC0 00000000 */  nop
/* 143B84 80247DC4 ACA20000 */  sw        $v0, 0x0($a1)
/* 143B88 80247DC8 00171400 */  sll       $v0, $s7, 16
/* 143B8C 80247DCC 001E1A00 */  sll       $v1, $fp, 8
/* 143B90 80247DD0 00431025 */  or        $v0, $v0, $v1
/* 143B94 80247DD4 4600018D */  trunc.w.s $f6, $f0
/* 143B98 80247DD8 44043000 */  mfc1      $a0, $f6
/* 143B9C 80247DDC 00000000 */  nop
/* 143BA0 80247DE0 308400FF */  andi      $a0, $a0, 0xFF
/* 143BA4 80247DE4 00441025 */  or        $v0, $v0, $a0
/* 143BA8 80247DE8 ACA20004 */  sw        $v0, 0x4($a1)
/* 143BAC 80247DEC 8FAB006C */  lw        $t3, 0x6C($sp)
/* 143BB0 80247DF0 022B102A */  slt       $v0, $s1, $t3
/* 143BB4 80247DF4 10400046 */  beqz      $v0, .LJP_80247F10
/* 143BB8 80247DF8 00000000 */   nop
/* 143BBC 80247DFC 3C106666 */  lui       $s0, (0x66666667 >> 16)
/* 143BC0 80247E00 36106667 */  ori       $s0, $s0, (0x66666667 & 0xFFFF)
/* 143BC4 80247E04 02300018 */  mult      $s1, $s0
.LJP_80247E08:
/* 143BC8 80247E08 24040002 */  addiu     $a0, $zero, 0x2
/* 143BCC 80247E0C 001117C3 */  sra       $v0, $s1, 31
/* 143BD0 80247E10 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 143BD4 80247E14 00005010 */  mfhi      $t2
/* 143BD8 80247E18 008A3007 */  srav      $a2, $t2, $a0
/* 143BDC 80247E1C 00C23023 */  subu      $a2, $a2, $v0
/* 143BE0 80247E20 00861004 */  sllv      $v0, $a2, $a0
/* 143BE4 80247E24 00461021 */  addu      $v0, $v0, $a2
/* 143BE8 80247E28 00021040 */  sll       $v0, $v0, 1
/* 143BEC 80247E2C 02221023 */  subu      $v0, $s1, $v0
/* 143BF0 80247E30 00022840 */  sll       $a1, $v0, 1
/* 143BF4 80247E34 00A22821 */  addu      $a1, $a1, $v0
/* 143BF8 80247E38 00052840 */  sll       $a1, $a1, 1
/* 143BFC 80247E3C 24A5000B */  addiu     $a1, $a1, 0xB
/* 143C00 80247E40 01652821 */  addu      $a1, $t3, $a1
/* 143C04 80247E44 000630C0 */  sll       $a2, $a2, 3
/* 143C08 80247E48 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 143C0C 80247E4C 24C6005C */  addiu     $a2, $a2, 0x5C
/* 143C10 80247E50 0C091ABE */  jal       pause_badges_draw_bp_orbs
/* 143C14 80247E54 01463021 */   addu     $a2, $t2, $a2
/* 143C18 80247E58 8FAB006C */  lw        $t3, 0x6C($sp)
/* 143C1C 80247E5C 26310001 */  addiu     $s1, $s1, 0x1
/* 143C20 80247E60 022B102A */  slt       $v0, $s1, $t3
/* 143C24 80247E64 1440FFE8 */  bnez      $v0, .LJP_80247E08
/* 143C28 80247E68 02300018 */   mult     $s1, $s0
/* 143C2C 80247E6C 08091FC4 */  j         .LJP_80247F10
/* 143C30 80247E70 00000000 */   nop
.LJP_80247E74:
/* 143C34 80247E74 ACA20000 */  sw        $v0, 0x0($a1)
/* 143C38 80247E78 3C02FA00 */  lui       $v0, (0xFA000000 >> 16)
/* 143C3C 80247E7C AC820000 */  sw        $v0, 0x0($a0)
/* 143C40 80247E80 00171400 */  sll       $v0, $s7, 16
/* 143C44 80247E84 001E1A00 */  sll       $v1, $fp, 8
/* 143C48 80247E88 00431025 */  or        $v0, $v0, $v1
/* 143C4C 80247E8C 344200FF */  ori       $v0, $v0, 0xFF
/* 143C50 80247E90 AC820004 */  sw        $v0, 0x4($a0)
/* 143C54 80247E94 8FAA006C */  lw        $t2, 0x6C($sp)
/* 143C58 80247E98 1940001D */  blez      $t2, .LJP_80247F10
/* 143C5C 80247E9C 0000882D */   daddu    $s1, $zero, $zero
/* 143C60 80247EA0 3C106666 */  lui       $s0, (0x66666667 >> 16)
/* 143C64 80247EA4 36106667 */  ori       $s0, $s0, (0x66666667 & 0xFFFF)
/* 143C68 80247EA8 02300018 */  mult      $s1, $s0
.LJP_80247EAC:
/* 143C6C 80247EAC 24040002 */  addiu     $a0, $zero, 0x2
/* 143C70 80247EB0 001117C3 */  sra       $v0, $s1, 31
/* 143C74 80247EB4 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 143C78 80247EB8 00005010 */  mfhi      $t2
/* 143C7C 80247EBC 008A3007 */  srav      $a2, $t2, $a0
/* 143C80 80247EC0 00C23023 */  subu      $a2, $a2, $v0
/* 143C84 80247EC4 00861004 */  sllv      $v0, $a2, $a0
/* 143C88 80247EC8 00461021 */  addu      $v0, $v0, $a2
/* 143C8C 80247ECC 00021040 */  sll       $v0, $v0, 1
/* 143C90 80247ED0 02221023 */  subu      $v0, $s1, $v0
/* 143C94 80247ED4 00022840 */  sll       $a1, $v0, 1
/* 143C98 80247ED8 00A22821 */  addu      $a1, $a1, $v0
/* 143C9C 80247EDC 00052840 */  sll       $a1, $a1, 1
/* 143CA0 80247EE0 24A5000B */  addiu     $a1, $a1, 0xB
/* 143CA4 80247EE4 01652821 */  addu      $a1, $t3, $a1
/* 143CA8 80247EE8 000630C0 */  sll       $a2, $a2, 3
/* 143CAC 80247EEC 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 143CB0 80247EF0 24C6005C */  addiu     $a2, $a2, 0x5C
/* 143CB4 80247EF4 0C091ABE */  jal       pause_badges_draw_bp_orbs
/* 143CB8 80247EF8 01463021 */   addu     $a2, $t2, $a2
/* 143CBC 80247EFC 8FAB006C */  lw        $t3, 0x6C($sp)
/* 143CC0 80247F00 26310001 */  addiu     $s1, $s1, 0x1
/* 143CC4 80247F04 022B102A */  slt       $v0, $s1, $t3
/* 143CC8 80247F08 1440FFE8 */  bnez      $v0, .LJP_80247EAC
/* 143CCC 80247F0C 02300018 */   mult     $s1, $s0
.LJP_80247F10:
/* 143CD0 80247F10 3C03800A */  lui       $v1, %hi(gMainGfxPos)
/* 143CD4 80247F14 2463A64C */  addiu     $v1, $v1, %lo(gMainGfxPos)
/* 143CD8 80247F18 8C620000 */  lw        $v0, 0x0($v1)
/* 143CDC 80247F1C 0040202D */  daddu     $a0, $v0, $zero
/* 143CE0 80247F20 24420008 */  addiu     $v0, $v0, 0x8
/* 143CE4 80247F24 AC620000 */  sw        $v0, 0x0($v1)
/* 143CE8 80247F28 3C02E700 */  lui       $v0, (0xE7000000 >> 16)
/* 143CEC 80247F2C AC820000 */  sw        $v0, 0x0($a0)
/* 143CF0 80247F30 AC800004 */  sw        $zero, 0x4($a0)
/* 143CF4 80247F34 3C038027 */  lui       $v1, %hi(gPauseBadgesCurrentTab)
/* 143CF8 80247F38 8C63FA5C */  lw        $v1, %lo(gPauseBadgesCurrentTab)($v1)
/* 143CFC 80247F3C 8FA600C4 */  lw        $a2, 0xC4($sp)
/* 143D00 80247F40 50600001 */  beql      $v1, $zero, .LJP_80247F48
/* 143D04 80247F44 24C60009 */   addiu    $a2, $a2, 0x9
.LJP_80247F48:
/* 143D08 80247F48 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 143D0C 80247F4C 24020057 */  addiu     $v0, $zero, 0x57
/* 143D10 80247F50 AFA20014 */  sw        $v0, 0x14($sp)
/* 143D14 80247F54 24020022 */  addiu     $v0, $zero, 0x22
/* 143D18 80247F58 AFA20018 */  sw        $v0, 0x18($sp)
/* 143D1C 80247F5C 240200FF */  addiu     $v0, $zero, 0xFF
/* 143D20 80247F60 AFA2001C */  sw        $v0, 0x1C($sp)
/* 143D24 80247F64 24020001 */  addiu     $v0, $zero, 0x1
/* 143D28 80247F68 AFA00010 */  sw        $zero, 0x10($sp)
/* 143D2C 80247F6C 14620004 */  bne       $v1, $v0, .LJP_80247F80
/* 143D30 80247F70 25470007 */   addiu    $a3, $t2, 0x7
/* 143D34 80247F74 24020080 */  addiu     $v0, $zero, 0x80
/* 143D38 80247F78 08091FE1 */  j         .LJP_80247F84
/* 143D3C 80247F7C AFA20020 */   sw       $v0, 0x20($sp)
.LJP_80247F80:
/* 143D40 80247F80 AFA00020 */  sw        $zero, 0x20($sp)
.LJP_80247F84:
/* 143D44 80247F84 24040004 */  addiu     $a0, $zero, 0x4
/* 143D48 80247F88 3C058027 */  lui       $a1, %hi(gPauseWS_13)
/* 143D4C 80247F8C 24A5F2A8 */  addiu     $a1, $a1, %lo(gPauseWS_13)
/* 143D50 80247F90 24020140 */  addiu     $v0, $zero, 0x140
/* 143D54 80247F94 AFA20044 */  sw        $v0, 0x44($sp)
/* 143D58 80247F98 240200F0 */  addiu     $v0, $zero, 0xF0
/* 143D5C 80247F9C AFA00024 */  sw        $zero, 0x24($sp)
/* 143D60 80247FA0 AFA00028 */  sw        $zero, 0x28($sp)
/* 143D64 80247FA4 AFA0002C */  sw        $zero, 0x2C($sp)
/* 143D68 80247FA8 AFA00030 */  sw        $zero, 0x30($sp)
/* 143D6C 80247FAC AFA00034 */  sw        $zero, 0x34($sp)
/* 143D70 80247FB0 AFA00038 */  sw        $zero, 0x38($sp)
/* 143D74 80247FB4 AFA0003C */  sw        $zero, 0x3C($sp)
/* 143D78 80247FB8 AFA00040 */  sw        $zero, 0x40($sp)
/* 143D7C 80247FBC AFA20048 */  sw        $v0, 0x48($sp)
/* 143D80 80247FC0 0C03D51C */  jal       draw_box
/* 143D84 80247FC4 AFA0004C */   sw       $zero, 0x4C($sp)
/* 143D88 80247FC8 0C09396C */  jal       pause_get_menu_msg
/* 143D8C 80247FCC 24040047 */   addiu    $a0, $zero, 0x47
/* 143D90 80247FD0 3C118027 */  lui       $s1, %hi(gPauseBadgesCurrentTab)
/* 143D94 80247FD4 2631FA5C */  addiu     $s1, $s1, %lo(gPauseBadgesCurrentTab)
/* 143D98 80247FD8 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 143D9C 80247FDC 8E230000 */  lw        $v1, 0x0($s1)
/* 143DA0 80247FE0 14600002 */  bnez      $v1, .LJP_80247FEC
/* 143DA4 80247FE4 2565000C */   addiu    $a1, $t3, 0xC
/* 143DA8 80247FE8 25650015 */  addiu     $a1, $t3, 0x15
.LJP_80247FEC:
/* 143DAC 80247FEC 240700FF */  addiu     $a3, $zero, 0xFF
/* 143DB0 80247FF0 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 143DB4 80247FF4 24100001 */  addiu     $s0, $zero, 0x1
/* 143DB8 80247FF8 14700002 */  bne       $v1, $s0, .LJP_80248004
/* 143DBC 80247FFC 25460011 */   addiu    $a2, $t2, 0x11
/* 143DC0 80248000 240700BF */  addiu     $a3, $zero, 0xBF
.LJP_80248004:
/* 143DC4 80248004 0040202D */  daddu     $a0, $v0, $zero
/* 143DC8 80248008 AFA00010 */  sw        $zero, 0x10($sp)
/* 143DCC 8024800C 0C04ADC4 */  jal       draw_msg
/* 143DD0 80248010 AFB00014 */   sw       $s0, 0x14($sp)
/* 143DD4 80248014 8E230000 */  lw        $v1, 0x0($s1)
/* 143DD8 80248018 8FA600C4 */  lw        $a2, 0xC4($sp)
/* 143DDC 8024801C 50700001 */  beql      $v1, $s0, .LJP_80248024
/* 143DE0 80248020 24C60009 */   addiu    $a2, $a2, 0x9
.LJP_80248024:
/* 143DE4 80248024 8FAB00C8 */  lw        $t3, 0xC8($sp)
/* 143DE8 80248028 24020057 */  addiu     $v0, $zero, 0x57
/* 143DEC 8024802C AFA20014 */  sw        $v0, 0x14($sp)
/* 143DF0 80248030 24020022 */  addiu     $v0, $zero, 0x22
/* 143DF4 80248034 AFA20018 */  sw        $v0, 0x18($sp)
/* 143DF8 80248038 240200FF */  addiu     $v0, $zero, 0xFF
/* 143DFC 8024803C AFA00010 */  sw        $zero, 0x10($sp)
/* 143E00 80248040 AFA2001C */  sw        $v0, 0x1C($sp)
/* 143E04 80248044 14600004 */  bnez      $v1, .LJP_80248058
/* 143E08 80248048 25670027 */   addiu    $a3, $t3, 0x27
/* 143E0C 8024804C 24020080 */  addiu     $v0, $zero, 0x80
/* 143E10 80248050 08092017 */  j         .LJP_8024805C
/* 143E14 80248054 AFA20020 */   sw       $v0, 0x20($sp)
.LJP_80248058:
/* 143E18 80248058 AFA00020 */  sw        $zero, 0x20($sp)
.LJP_8024805C:
/* 143E1C 8024805C 24040004 */  addiu     $a0, $zero, 0x4
/* 143E20 80248060 3C058027 */  lui       $a1, %hi(gPauseWS_13)
/* 143E24 80248064 24A5F2A8 */  addiu     $a1, $a1, %lo(gPauseWS_13)
/* 143E28 80248068 24020140 */  addiu     $v0, $zero, 0x140
/* 143E2C 8024806C AFA20044 */  sw        $v0, 0x44($sp)
/* 143E30 80248070 240200F0 */  addiu     $v0, $zero, 0xF0
/* 143E34 80248074 AFA00024 */  sw        $zero, 0x24($sp)
/* 143E38 80248078 AFA00028 */  sw        $zero, 0x28($sp)
/* 143E3C 8024807C AFA0002C */  sw        $zero, 0x2C($sp)
/* 143E40 80248080 AFA00030 */  sw        $zero, 0x30($sp)
/* 143E44 80248084 AFA00034 */  sw        $zero, 0x34($sp)
/* 143E48 80248088 AFA00038 */  sw        $zero, 0x38($sp)
/* 143E4C 8024808C AFA0003C */  sw        $zero, 0x3C($sp)
/* 143E50 80248090 AFA00040 */  sw        $zero, 0x40($sp)
/* 143E54 80248094 AFA20048 */  sw        $v0, 0x48($sp)
/* 143E58 80248098 0C03D51C */  jal       draw_box
/* 143E5C 8024809C AFA0004C */   sw       $zero, 0x4C($sp)
/* 143E60 802480A0 0C09396C */  jal       pause_get_menu_msg
/* 143E64 802480A4 24040048 */   addiu    $a0, $zero, 0x48
/* 143E68 802480A8 3C108027 */  lui       $s0, %hi(gPauseBadgesCurrentTab)
/* 143E6C 802480AC 2610FA5C */  addiu     $s0, $s0, %lo(gPauseBadgesCurrentTab)
/* 143E70 802480B0 24080001 */  addiu     $t0, $zero, 0x1
/* 143E74 802480B4 8FAA00C4 */  lw        $t2, 0xC4($sp)
/* 143E78 802480B8 8E030000 */  lw        $v1, 0x0($s0)
/* 143E7C 802480BC 14680002 */  bne       $v1, $t0, .LJP_802480C8
/* 143E80 802480C0 25450008 */   addiu    $a1, $t2, 0x8
/* 143E84 802480C4 25450011 */  addiu     $a1, $t2, 0x11
.LJP_802480C8:
/* 143E88 802480C8 8FAB00C8 */  lw        $t3, 0xC8($sp)
/* 143E8C 802480CC 240700FF */  addiu     $a3, $zero, 0xFF
/* 143E90 802480D0 14600002 */  bnez      $v1, .LJP_802480DC
/* 143E94 802480D4 25660031 */   addiu    $a2, $t3, 0x31
/* 143E98 802480D8 240700BF */  addiu     $a3, $zero, 0xBF
.LJP_802480DC:
/* 143E9C 802480DC 0040202D */  daddu     $a0, $v0, $zero
/* 143EA0 802480E0 AFA00010 */  sw        $zero, 0x10($sp)
/* 143EA4 802480E4 0C04ADC4 */  jal       draw_msg
/* 143EA8 802480E8 AFA80014 */   sw       $t0, 0x14($sp)
/* 143EAC 802480EC 3C038027 */  lui       $v1, %hi(gPauseMenuCurrentTab)
/* 143EB0 802480F0 8063F7A4 */  lb        $v1, %lo(gPauseMenuCurrentTab)($v1)
/* 143EB4 802480F4 24020002 */  addiu     $v0, $zero, 0x2
/* 143EB8 802480F8 14620050 */  bne       $v1, $v0, .LJP_8024823C
/* 143EBC 802480FC 00000000 */   nop
/* 143EC0 80248100 3C028027 */  lui       $v0, %hi(gPauseBadgesLevel)
/* 143EC4 80248104 8C42FA58 */  lw        $v0, %lo(gPauseBadgesLevel)($v0)
/* 143EC8 80248108 14400009 */  bnez      $v0, .LJP_80248130
/* 143ECC 8024810C 24040020 */   addiu    $a0, $zero, 0x20
/* 143ED0 80248110 8E060000 */  lw        $a2, 0x0($s0)
/* 143ED4 80248114 8FAA00C4 */  lw        $t2, 0xC4($sp)
/* 143ED8 80248118 8FAB00C8 */  lw        $t3, 0xC8($sp)
/* 143EDC 8024811C 2545000A */  addiu     $a1, $t2, 0xA
/* 143EE0 80248120 00063140 */  sll       $a2, $a2, 5
/* 143EE4 80248124 24C6001A */  addiu     $a2, $a2, 0x1A
/* 143EE8 80248128 0809208D */  j         .LJP_80248234
/* 143EEC 8024812C 01663021 */   addu     $a2, $t3, $a2
.LJP_80248130:
/* 143EF0 80248130 3C118027 */  lui       $s1, %hi(gPauseBadgesCurrentPage)
/* 143EF4 80248134 2631F940 */  addiu     $s1, $s1, %lo(gPauseBadgesCurrentPage)
/* 143EF8 80248138 8E240000 */  lw        $a0, 0x0($s1)
/* 143EFC 8024813C 3C128027 */  lui       $s2, %hi(gPauseBadgesPages)
/* 143F00 80248140 2652F948 */  addiu     $s2, $s2, %lo(gPauseBadgesPages)
/* 143F04 80248144 00041040 */  sll       $v0, $a0, 1
/* 143F08 80248148 00441021 */  addu      $v0, $v0, $a0
/* 143F0C 8024814C 00021080 */  sll       $v0, $v0, 2
/* 143F10 80248150 00521021 */  addu      $v0, $v0, $s2
/* 143F14 80248154 90430001 */  lbu       $v1, 0x1($v0)
/* 143F18 80248158 90420002 */  lbu       $v0, 0x2($v0)
/* 143F1C 8024815C 00620018 */  mult      $v1, $v0
/* 143F20 80248160 3C108027 */  lui       $s0, %hi(gPauseBadgesSelectedIndex)
/* 143F24 80248164 2610FA38 */  addiu     $s0, $s0, %lo(gPauseBadgesSelectedIndex)
/* 143F28 80248168 8E050000 */  lw        $a1, 0x0($s0)
/* 143F2C 8024816C 00005012 */  mflo      $t2
/* 143F30 80248170 0C0919EB */  jal       pause_badges_get_pos_x
/* 143F34 80248174 00AA2823 */   subu     $a1, $a1, $t2
/* 143F38 80248178 8E240000 */  lw        $a0, 0x0($s1)
/* 143F3C 8024817C 00041840 */  sll       $v1, $a0, 1
/* 143F40 80248180 00641821 */  addu      $v1, $v1, $a0
/* 143F44 80248184 00031880 */  sll       $v1, $v1, 2
/* 143F48 80248188 00721821 */  addu      $v1, $v1, $s2
/* 143F4C 8024818C 90650001 */  lbu       $a1, 0x1($v1)
/* 143F50 80248190 90630002 */  lbu       $v1, 0x2($v1)
/* 143F54 80248194 00A30018 */  mult      $a1, $v1
/* 143F58 80248198 8E050000 */  lw        $a1, 0x0($s0)
/* 143F5C 8024819C 0040802D */  daddu     $s0, $v0, $zero
/* 143F60 802481A0 00005012 */  mflo      $t2
/* 143F64 802481A4 0C091A02 */  jal       pause_badges_get_pos_y
/* 143F68 802481A8 00AA2823 */   subu     $a1, $a1, $t2
/* 143F6C 802481AC 0200202D */  daddu     $a0, $s0, $zero
/* 143F70 802481B0 0C091A52 */  jal       pause_badges_scroll_offset_x
/* 143F74 802481B4 0040802D */   daddu    $s0, $v0, $zero
/* 143F78 802481B8 0200202D */  daddu     $a0, $s0, $zero
/* 143F7C 802481BC 0C091A4E */  jal       pause_badges_scroll_offset_y
/* 143F80 802481C0 0040802D */   daddu    $s0, $v0, $zero
/* 143F84 802481C4 0040302D */  daddu     $a2, $v0, $zero
/* 143F88 802481C8 04C10003 */  bgez      $a2, .LJP_802481D8
/* 143F8C 802481CC 28C20071 */   slti     $v0, $a2, 0x71
/* 143F90 802481D0 08092078 */  j         .LJP_802481E0
/* 143F94 802481D4 0000302D */   daddu    $a2, $zero, $zero
.LJP_802481D8:
/* 143F98 802481D8 50400001 */  beql      $v0, $zero, .LJP_802481E0
/* 143F9C 802481DC 24060070 */   addiu    $a2, $zero, 0x70
.LJP_802481E0:
/* 143FA0 802481E0 3C038027 */  lui       $v1, %hi(gPauseBadgesCurrentScrollPos)
/* 143FA4 802481E4 8C63FA4C */  lw        $v1, %lo(gPauseBadgesCurrentScrollPos)($v1)
/* 143FA8 802481E8 3C028027 */  lui       $v0, %hi(gPauseBadgesTargetScrollPos)
/* 143FAC 802481EC 8C42FA50 */  lw        $v0, %lo(gPauseBadgesTargetScrollPos)($v0)
/* 143FB0 802481F0 1062000A */  beq       $v1, $v0, .LJP_8024821C
/* 143FB4 802481F4 24040020 */   addiu    $a0, $zero, 0x20
/* 143FB8 802481F8 2605005D */  addiu     $a1, $s0, 0x5D
/* 143FBC 802481FC 24C60017 */  addiu     $a2, $a2, 0x17
/* 143FC0 80248200 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 143FC4 80248204 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 143FC8 80248208 01652821 */  addu      $a1, $t3, $a1
/* 143FCC 8024820C 0C0908DF */  jal       pause_set_cursor_pos_immediate
/* 143FD0 80248210 01463021 */   addu     $a2, $t2, $a2
/* 143FD4 80248214 0809208F */  j         .LJP_8024823C
/* 143FD8 80248218 00000000 */   nop
.LJP_8024821C:
/* 143FDC 8024821C 2605005D */  addiu     $a1, $s0, 0x5D
/* 143FE0 80248220 24C60017 */  addiu     $a2, $a2, 0x17
/* 143FE4 80248224 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 143FE8 80248228 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 143FEC 8024822C 01652821 */  addu      $a1, $t3, $a1
/* 143FF0 80248230 01463021 */  addu      $a2, $t2, $a2
.LJP_80248234:
/* 143FF4 80248234 0C090935 */  jal       pause_set_cursor_pos
/* 143FF8 80248238 00000000 */   nop
.LJP_8024823C:
/* 143FFC 8024823C 3C108027 */  lui       $s0, %hi(gPauseBadgesShowNotEnoughBP)
/* 144000 80248240 2610FA60 */  addiu     $s0, $s0, %lo(gPauseBadgesShowNotEnoughBP)
/* 144004 80248244 8E020000 */  lw        $v0, 0x0($s0)
/* 144008 80248248 1040004D */  beqz      $v0, .LJP_80248380
/* 14400C 8024824C 00000000 */   nop
/* 144010 80248250 0C0908DC */  jal       pause_set_cursor_opacity
/* 144014 80248254 0000202D */   daddu    $a0, $zero, $zero
/* 144018 80248258 8E020000 */  lw        $v0, 0x0($s0)
/* 14401C 8024825C 24100001 */  addiu     $s0, $zero, 0x1
/* 144020 80248260 1450001F */  bne       $v0, $s0, .LJP_802482E0
/* 144024 80248264 24040004 */   addiu    $a0, $zero, 0x4
/* 144028 80248268 3C058027 */  lui       $a1, %hi(gPauseWS_13)
/* 14402C 8024826C 24A5F2A8 */  addiu     $a1, $a1, %lo(gPauseWS_13)
/* 144030 80248270 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 144034 80248274 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 144038 80248278 24020089 */  addiu     $v0, $zero, 0x89
/* 14403C 8024827C AFA20014 */  sw        $v0, 0x14($sp)
/* 144040 80248280 2402001A */  addiu     $v0, $zero, 0x1A
/* 144044 80248284 AFA20018 */  sw        $v0, 0x18($sp)
/* 144048 80248288 240200FF */  addiu     $v0, $zero, 0xFF
/* 14404C 8024828C AFA2001C */  sw        $v0, 0x1C($sp)
/* 144050 80248290 24020140 */  addiu     $v0, $zero, 0x140
/* 144054 80248294 AFA20044 */  sw        $v0, 0x44($sp)
/* 144058 80248298 240200F0 */  addiu     $v0, $zero, 0xF0
/* 14405C 8024829C AFA00010 */  sw        $zero, 0x10($sp)
/* 144060 802482A0 AFA00020 */  sw        $zero, 0x20($sp)
/* 144064 802482A4 AFA00024 */  sw        $zero, 0x24($sp)
/* 144068 802482A8 AFA00028 */  sw        $zero, 0x28($sp)
/* 14406C 802482AC AFA0002C */  sw        $zero, 0x2C($sp)
/* 144070 802482B0 AFA00030 */  sw        $zero, 0x30($sp)
/* 144074 802482B4 AFA00034 */  sw        $zero, 0x34($sp)
/* 144078 802482B8 AFA00038 */  sw        $zero, 0x38($sp)
/* 14407C 802482BC AFA0003C */  sw        $zero, 0x3C($sp)
/* 144080 802482C0 AFA00040 */  sw        $zero, 0x40($sp)
/* 144084 802482C4 AFA20048 */  sw        $v0, 0x48($sp)
/* 144088 802482C8 AFA0004C */  sw        $zero, 0x4C($sp)
/* 14408C 802482CC 25660043 */  addiu     $a2, $t3, 0x43
/* 144090 802482D0 0C03D51C */  jal       draw_box
/* 144094 802482D4 2547003C */   addiu    $a3, $t2, 0x3C
/* 144098 802482D8 080920D5 */  j         .LJP_80248354
/* 14409C 802482DC 24040049 */   addiu    $a0, $zero, 0x49
.LJP_802482E0:
/* 1440A0 802482E0 3C058027 */  lui       $a1, %hi(gPauseWS_13)
/* 1440A4 802482E4 24A5F2A8 */  addiu     $a1, $a1, %lo(gPauseWS_13)
/* 1440A8 802482E8 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 1440AC 802482EC 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 1440B0 802482F0 240200AD */  addiu     $v0, $zero, 0xAD
/* 1440B4 802482F4 AFA20014 */  sw        $v0, 0x14($sp)
/* 1440B8 802482F8 2402001A */  addiu     $v0, $zero, 0x1A
/* 1440BC 802482FC AFA20018 */  sw        $v0, 0x18($sp)
/* 1440C0 80248300 240200FF */  addiu     $v0, $zero, 0xFF
/* 1440C4 80248304 AFA2001C */  sw        $v0, 0x1C($sp)
/* 1440C8 80248308 24020140 */  addiu     $v0, $zero, 0x140
/* 1440CC 8024830C AFA20044 */  sw        $v0, 0x44($sp)
/* 1440D0 80248310 240200F0 */  addiu     $v0, $zero, 0xF0
/* 1440D4 80248314 AFA00010 */  sw        $zero, 0x10($sp)
/* 1440D8 80248318 AFA00020 */  sw        $zero, 0x20($sp)
/* 1440DC 8024831C AFA00024 */  sw        $zero, 0x24($sp)
/* 1440E0 80248320 AFA00028 */  sw        $zero, 0x28($sp)
/* 1440E4 80248324 AFA0002C */  sw        $zero, 0x2C($sp)
/* 1440E8 80248328 AFA00030 */  sw        $zero, 0x30($sp)
/* 1440EC 8024832C AFA00034 */  sw        $zero, 0x34($sp)
/* 1440F0 80248330 AFA00038 */  sw        $zero, 0x38($sp)
/* 1440F4 80248334 AFA0003C */  sw        $zero, 0x3C($sp)
/* 1440F8 80248338 AFA00040 */  sw        $zero, 0x40($sp)
/* 1440FC 8024833C AFA20048 */  sw        $v0, 0x48($sp)
/* 144100 80248340 AFA0004C */  sw        $zero, 0x4C($sp)
/* 144104 80248344 25660043 */  addiu     $a2, $t3, 0x43
/* 144108 80248348 0C03D51C */  jal       draw_box
/* 14410C 8024834C 2547003C */   addiu    $a3, $t2, 0x3C
/* 144110 80248350 2404004A */  addiu     $a0, $zero, 0x4A
.LJP_80248354:
/* 144114 80248354 0C09396C */  jal       pause_get_menu_msg
/* 144118 80248358 00000000 */   nop
/* 14411C 8024835C 0040202D */  daddu     $a0, $v0, $zero
/* 144120 80248360 8FAB00C4 */  lw        $t3, 0xC4($sp)
/* 144124 80248364 8FAA00C8 */  lw        $t2, 0xC8($sp)
/* 144128 80248368 240700FF */  addiu     $a3, $zero, 0xFF
/* 14412C 8024836C AFA00010 */  sw        $zero, 0x10($sp)
/* 144130 80248370 AFB00014 */  sw        $s0, 0x14($sp)
/* 144134 80248374 2565004E */  addiu     $a1, $t3, 0x4E
/* 144138 80248378 0C04ADC4 */  jal       draw_msg
/* 14413C 8024837C 25460042 */   addiu    $a2, $t2, 0x42
.LJP_80248380:
/* 144140 80248380 8FBF00BC */  lw        $ra, 0xBC($sp)
/* 144144 80248384 8FBE00B8 */  lw        $fp, 0xB8($sp)
/* 144148 80248388 8FB700B4 */  lw        $s7, 0xB4($sp)
/* 14414C 8024838C 8FB600B0 */  lw        $s6, 0xB0($sp)
/* 144150 80248390 8FB500AC */  lw        $s5, 0xAC($sp)
/* 144154 80248394 8FB400A8 */  lw        $s4, 0xA8($sp)
/* 144158 80248398 8FB300A4 */  lw        $s3, 0xA4($sp)
/* 14415C 8024839C 8FB200A0 */  lw        $s2, 0xA0($sp)
/* 144160 802483A0 8FB1009C */  lw        $s1, 0x9C($sp)
/* 144164 802483A4 8FB00098 */  lw        $s0, 0x98($sp)
/* 144168 802483A8 03E00008 */  jr        $ra
/* 14416C 802483AC 27BD00C0 */   addiu    $sp, $sp, 0xC0
.size pause_badges_draw_contents, . - pause_badges_draw_contents
