.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_JP_8029D4F8
/* 1D3EE8 8029D4F8 80250FCC */ .word .LJP_80250FCC
/* 1D3EEC 8029D4FC 80250FCC */ .word .LJP_80250FCC
/* 1D3EF0 8029D500 80250FCC */ .word .LJP_80250FCC
/* 1D3EF4 8029D504 80250FA4 */ .word .LJP_80250FA4
/* 1D3EF8 8029D508 80251314 */ .word .LJP_80251314
/* 1D3EFC 8029D50C 80251314 */ .word .LJP_80251314
/* 1D3F00 8029D510 80251314 */ .word .LJP_80251314
/* 1D3F04 8029D514 80251314 */ .word .LJP_80251314
/* 1D3F08 8029D518 80250FA4 */ .word .LJP_80250FA4
/* 1D3F0C 8029D51C 80250FA4 */ .word .LJP_80250FA4
/* 1D3F10 8029D520 80251194 */ .word .LJP_80251194
/* 1D3F14 8029D524 80251194 */ .word .LJP_80251194
/* 1D3F18 8029D528 80251194 */ .word .LJP_80251194
/* 1D3F1C 8029D52C 80251194 */ .word .LJP_80251194
/* 1D3F20 8029D530 80251194 */ .word .LJP_80251194
/* 1D3F24 8029D534 80251194 */ .word .LJP_80251194
/* 1D3F28 8029D538 80251194 */ .word .LJP_80251194
/* 1D3F2C 8029D53C 80251194 */ .word .LJP_80251194
/* 1D3F30 8029D540 80251254 */ .word .LJP_80251254
/* 1D3F34 8029D544 80251254 */ .word .LJP_80251254
/* 1D3F38 8029D548 80251254 */ .word .LJP_80251254
/* 1D3F3C 8029D54C 80251254 */ .word .LJP_80251254
/* 1D3F40 8029D550 80251254 */ .word .LJP_80251254
/* 1D3F44 8029D554 80251254 */ .word .LJP_80251254
/* 1D3F48 8029D558 80251254 */ .word .LJP_80251254
/* 1D3F4C 8029D55C 80251254 */ .word .LJP_80251254
/* 1D3F50 8029D560 80250FA4 */ .word .LJP_80250FA4
/* 1D3F54 8029D564 80250FA4 */ .word .LJP_80250FA4
/* 1D3F58 8029D568 80250FA4 */ .word .LJP_80250FA4
/* 1D3F5C 8029D56C 80251314 */ .word .LJP_80251314
/* 1D3F60 8029D570 80251314 */ .word .LJP_80251314
/* 1D3F64 8029D574 80251314 */ .word .LJP_80251314
/* 1D3F68 8029D578 80251314 */ .word .LJP_80251314
/* 1D3F6C 8029D57C 80251314 */ .word .LJP_80251314
/* 1D3F70 8029D580 80251314 */ .word .LJP_80251314
/* 1D3F74 8029D584 80250FA4 */ .word .LJP_80250FA4
/* 1D3F78 8029D588 80250FA4 */ .word .LJP_80250FA4
/* 1D3F7C 8029D58C 80250FA4 */ .word .LJP_80250FA4
/* 1D3F80 8029D590 80250FA4 */ .word .LJP_80250FA4
/* 1D3F84 8029D594 80250FA4 */ .word .LJP_80250FA4
/* 1D3F88 8029D598 80250FA4 */ .word .LJP_80250FA4
/* 1D3F8C 8029D59C 80250FA4 */ .word .LJP_80250FA4
/* 1D3F90 8029D5A0 80250FA4 */ .word .LJP_80250FA4
/* 1D3F94 8029D5A4 80250FA4 */ .word .LJP_80250FA4
/* 1D3F98 8029D5A8 80250FA4 */ .word .LJP_80250FA4
/* 1D3F9C 8029D5AC 80250FA4 */ .word .LJP_80250FA4
/* 1D3FA0 8029D5B0 80251048 */ .word .LJP_80251048
/* 1D3FA4 8029D5B4 80251048 */ .word .LJP_80251048
/* 1D3FA8 8029D5B8 80251048 */ .word .LJP_80251048
/* 1D3FAC 8029D5BC 80251048 */ .word .LJP_80251048
/* 1D3FB0 8029D5C0 80251048 */ .word .LJP_80251048
/* 1D3FB4 8029D5C4 80251048 */ .word .LJP_80251048
/* 1D3FB8 8029D5C8 80251048 */ .word .LJP_80251048
/* 1D3FBC 8029D5CC 80251048 */ .word .LJP_80251048
/* 1D3FC0 8029D5D0 80251048 */ .word .LJP_80251048
/* 1D3FC4 8029D5D4 80251048 */ .word .LJP_80251048
/* 1D3FC8 8029D5D8 80251048 */ .word .LJP_80251048
/* 1D3FCC 8029D5DC 80251048 */ .word .LJP_80251048
/* 1D3FD0 8029D5E0 80251048 */ .word .LJP_80251048
/* 1D3FD4 8029D5E4 80251048 */ .word .LJP_80251048
/* 1D3FD8 8029D5E8 80251048 */ .word .LJP_80251048
/* 1D3FDC 8029D5EC 80251048 */ .word .LJP_80251048
/* 1D3FE0 8029D5F0 80251048 */ .word .LJP_80251048
/* 1D3FE4 8029D5F4 80251048 */ .word .LJP_80251048
/* 1D3FE8 8029D5F8 80251048 */ .word .LJP_80251048
/* 1D3FEC 8029D5FC 80251048 */ .word .LJP_80251048
/* 1D3FF0 8029D600 80251048 */ .word .LJP_80251048
/* 1D3FF4 8029D604 80250FA4 */ .word .LJP_80250FA4
/* 1D3FF8 8029D608 80250FA4 */ .word .LJP_80250FA4
/* 1D3FFC 8029D60C 80250FA4 */ .word .LJP_80250FA4
/* 1D4000 8029D610 80250FA4 */ .word .LJP_80250FA4
/* 1D4004 8029D614 80250FA4 */ .word .LJP_80250FA4
/* 1D4008 8029D618 80250FA4 */ .word .LJP_80250FA4
/* 1D400C 8029D61C 80251118 */ .word .LJP_80251118
/* 1D4010 8029D620 80251118 */ .word .LJP_80251118
/* 1D4014 8029D624 80251118 */ .word .LJP_80251118
/* 1D4018 8029D628 80251118 */ .word .LJP_80251118
/* 1D401C 8029D62C 80251118 */ .word .LJP_80251118
/* 1D4020 8029D630 80251118 */ .word .LJP_80251118
/* 1D4024 8029D634 80251118 */ .word .LJP_80251118
/* 1D4028 8029D638 80250FCC */ .word .LJP_80250FCC
/* 1D402C 8029D63C 80251354 */ .word .LJP_80251354
/* 1D4030 8029D640 80250FA4 */ .word .LJP_80250FA4
/* 1D4034 8029D644 80250FA4 */ .word .LJP_80250FA4
/* 1D4038 8029D648 80250FA4 */ .word .LJP_80250FA4
/* 1D403C 8029D64C 00000000 */ .word 0x00000000
.size jtbl_JP_8029D4F8, . - jtbl_JP_8029D4F8


.section .text
/* Generated by spimdisasm 1.20.0 */

glabel btl_show_message_popup
/* 187954 80250F64 27BDFFC8 */  addiu     $sp, $sp, -0x38
/* 187958 80250F68 AFB1002C */  sw        $s1, 0x2C($sp)
/* 18795C 80250F6C 0080882D */  daddu     $s1, $a0, $zero
/* 187960 80250F70 AFBF0034 */  sw        $ra, 0x34($sp)
/* 187964 80250F74 AFB20030 */  sw        $s2, 0x30($sp)
/* 187968 80250F78 AFB00028 */  sw        $s0, 0x28($sp)
/* 18796C 80250F7C 86230012 */  lh        $v1, 0x12($s1)
/* 187970 80250F80 2C620055 */  sltiu     $v0, $v1, 0x55
/* 187974 80250F84 10400128 */  beqz      $v0, .LJP_80251428
/* 187978 80250F88 24120050 */   addiu    $s2, $zero, 0x50
/* 18797C 80250F8C 00031080 */  sll       $v0, $v1, 2
/* 187980 80250F90 3C01802A */  lui       $at, %hi(jtbl_JP_8029D4F8)
/* 187984 80250F94 00220821 */  addu      $at, $at, $v0
/* 187988 80250F98 8C22D4F8 */  lw        $v0, %lo(jtbl_JP_8029D4F8)($at)
/* 18798C 80250F9C 00400008 */  jr        $v0
/* 187990 80250FA0 00000000 */   nop
.LJP_80250FA4:
/* 187994 80250FA4 82220017 */  lb        $v0, 0x17($s1)
/* 187998 80250FA8 1040011F */  beqz      $v0, .LJP_80251428
/* 18799C 80250FAC 0000282D */   daddu    $a1, $zero, $zero
/* 1879A0 80250FB0 86220012 */  lh        $v0, 0x12($s1)
/* 1879A4 80250FB4 A2200017 */  sb        $zero, 0x17($s1)
/* 1879A8 80250FB8 00021080 */  sll       $v0, $v0, 2
/* 1879AC 80250FBC 3C048028 */  lui       $a0, %hi(BattleMessages)
/* 1879B0 80250FC0 00822021 */  addu      $a0, $a0, $v0
/* 1879B4 80250FC4 080944E8 */  j         .LJP_802513A0
/* 1879B8 80250FC8 8C843A34 */   lw       $a0, %lo(BattleMessages)($a0)
.LJP_80250FCC:
/* 1879BC 80250FCC 82220017 */  lb        $v0, 0x17($s1)
/* 1879C0 80250FD0 10400115 */  beqz      $v0, .LJP_80251428
/* 1879C4 80250FD4 00000000 */   nop
/* 1879C8 80250FD8 86220012 */  lh        $v0, 0x12($s1)
/* 1879CC 80250FDC A2200017 */  sb        $zero, 0x17($s1)
/* 1879D0 80250FE0 00021080 */  sll       $v0, $v0, 2
/* 1879D4 80250FE4 3C048028 */  lui       $a0, %hi(BattleMessages)
/* 1879D8 80250FE8 00822021 */  addu      $a0, $a0, $v0
/* 1879DC 80250FEC 8C843A34 */  lw        $a0, %lo(BattleMessages)($a0)
/* 1879E0 80250FF0 0C04ADB5 */  jal       get_msg_width
/* 1879E4 80250FF4 0000282D */   daddu    $a1, $zero, $zero
/* 1879E8 80250FF8 24040009 */  addiu     $a0, $zero, 0x9
/* 1879EC 80250FFC 3C058028 */  lui       $a1, %hi(D_JP_8028374C)
/* 1879F0 80251000 24A5374C */  addiu     $a1, $a1, %lo(D_JP_8028374C)
/* 1879F4 80251004 0240302D */  daddu     $a2, $s2, $zero
/* 1879F8 80251008 86230012 */  lh        $v1, 0x12($s1)
/* 1879FC 8025100C 2442001F */  addiu     $v0, $v0, 0x1F
/* 187A00 80251010 00031880 */  sll       $v1, $v1, 2
/* 187A04 80251014 00651821 */  addu      $v1, $v1, $a1
/* 187A08 80251018 80650000 */  lb        $a1, 0x0($v1)
/* 187A0C 8025101C 80670001 */  lb        $a3, 0x1($v1)
/* 187A10 80251020 3C038025 */  lui       $v1, %hi(btl_message_popup_draw_content)
/* 187A14 80251024 246307FC */  addiu     $v1, $v1, %lo(btl_message_popup_draw_content)
/* 187A18 80251028 AFA30018 */  sw        $v1, 0x18($sp)
/* 187A1C 8025102C 2403FFFF */  addiu     $v1, $zero, -0x1
/* 187A20 80251030 AFA00014 */  sw        $zero, 0x14($sp)
/* 187A24 80251034 AFB1001C */  sw        $s1, 0x1C($sp)
/* 187A28 80251038 AFA30020 */  sw        $v1, 0x20($sp)
/* 187A2C 8025103C 00454021 */  addu      $t0, $v0, $a1
/* 187A30 80251040 080944FD */  j         .LJP_802513F4
/* 187A34 80251044 24E9002D */   addiu    $t1, $a3, 0x2D
.LJP_80251048:
/* 187A38 80251048 82220017 */  lb        $v0, 0x17($s1)
/* 187A3C 8025104C 104000F6 */  beqz      $v0, .LJP_80251428
/* 187A40 80251050 0000282D */   daddu    $a1, $zero, $zero
/* 187A44 80251054 86220012 */  lh        $v0, 0x12($s1)
/* 187A48 80251058 A2200017 */  sb        $zero, 0x17($s1)
/* 187A4C 8025105C 00021080 */  sll       $v0, $v0, 2
/* 187A50 80251060 3C048028 */  lui       $a0, %hi(BattleMessages)
/* 187A54 80251064 00822021 */  addu      $a0, $a0, $v0
/* 187A58 80251068 8C843A34 */  lw        $a0, %lo(BattleMessages)($a0)
/* 187A5C 8025106C 0C04ADB5 */  jal       get_msg_width
/* 187A60 80251070 241200C0 */   addiu    $s2, $zero, 0xC0
/* 187A64 80251074 3C038028 */  lui       $v1, %hi(D_JP_8028374C)
/* 187A68 80251078 2463374C */  addiu     $v1, $v1, %lo(D_JP_8028374C)
/* 187A6C 8025107C 86250012 */  lh        $a1, 0x12($s1)
/* 187A70 80251080 2442001F */  addiu     $v0, $v0, 0x1F
/* 187A74 80251084 00052080 */  sll       $a0, $a1, 2
/* 187A78 80251088 00832021 */  addu      $a0, $a0, $v1
/* 187A7C 8025108C 80830000 */  lb        $v1, 0x0($a0)
/* 187A80 80251090 2410003B */  addiu     $s0, $zero, 0x3B
/* 187A84 80251094 00434021 */  addu      $t0, $v0, $v1
/* 187A88 80251098 000817C2 */  srl       $v0, $t0, 31
/* 187A8C 8025109C 01021021 */  addu      $v0, $t0, $v0
/* 187A90 802510A0 00021043 */  sra       $v0, $v0, 1
/* 187A94 802510A4 240300A0 */  addiu     $v1, $zero, 0xA0
/* 187A98 802510A8 00621823 */  subu      $v1, $v1, $v0
/* 187A9C 802510AC 80820001 */  lb        $v0, 0x1($a0)
/* 187AA0 802510B0 0100382D */  daddu     $a3, $t0, $zero
/* 187AA4 802510B4 14B00005 */  bne       $a1, $s0, .LJP_802510CC
/* 187AA8 802510B8 2449001C */   addiu    $t1, $v0, 0x1C
/* 187AAC 802510BC 24120078 */  addiu     $s2, $zero, 0x78
/* 187AB0 802510C0 24020001 */  addiu     $v0, $zero, 0x1
/* 187AB4 802510C4 3C01802A */  lui       $at, %hi(BattleMessage_BoxPosLocked)
/* 187AB8 802510C8 A422F94C */  sh        $v0, %lo(BattleMessage_BoxPosLocked)($at)
.LJP_802510CC:
/* 187ABC 802510CC 24040009 */  addiu     $a0, $zero, 0x9
/* 187AC0 802510D0 0060282D */  daddu     $a1, $v1, $zero
/* 187AC4 802510D4 0240302D */  daddu     $a2, $s2, $zero
/* 187AC8 802510D8 3C028025 */  lui       $v0, %hi(btl_message_popup_draw_content)
/* 187ACC 802510DC 244207FC */  addiu     $v0, $v0, %lo(btl_message_popup_draw_content)
/* 187AD0 802510E0 AFA20018 */  sw        $v0, 0x18($sp)
/* 187AD4 802510E4 2402FFFF */  addiu     $v0, $zero, -0x1
/* 187AD8 802510E8 3C01802A */  lui       $at, %hi(BattleMessage_CurBoxPosY)
/* 187ADC 802510EC A426F94E */  sh        $a2, %lo(BattleMessage_CurBoxPosY)($at)
/* 187AE0 802510F0 AFA90010 */  sw        $t1, 0x10($sp)
/* 187AE4 802510F4 AFA00014 */  sw        $zero, 0x14($sp)
/* 187AE8 802510F8 AFB1001C */  sw        $s1, 0x1C($sp)
/* 187AEC 802510FC 0C05335E */  jal       set_window_properties
/* 187AF0 80251100 AFA20020 */   sw       $v0, 0x20($sp)
/* 187AF4 80251104 86220012 */  lh        $v0, 0x12($s1)
/* 187AF8 80251108 105000C3 */  beq       $v0, $s0, .LJP_80251418
/* 187AFC 8025110C 24040009 */   addiu    $a0, $zero, 0x9
/* 187B00 80251110 08094508 */  j         .LJP_80251420
/* 187B04 80251114 24050008 */   addiu    $a1, $zero, 0x8
.LJP_80251118:
/* 187B08 80251118 82220017 */  lb        $v0, 0x17($s1)
/* 187B0C 8025111C 104000C2 */  beqz      $v0, .LJP_80251428
/* 187B10 80251120 00000000 */   nop
/* 187B14 80251124 86220012 */  lh        $v0, 0x12($s1)
/* 187B18 80251128 A2200017 */  sb        $zero, 0x17($s1)
/* 187B1C 8025112C 00021080 */  sll       $v0, $v0, 2
/* 187B20 80251130 3C048028 */  lui       $a0, %hi(BattleMessages)
/* 187B24 80251134 00822021 */  addu      $a0, $a0, $v0
/* 187B28 80251138 8C843A34 */  lw        $a0, %lo(BattleMessages)($a0)
/* 187B2C 8025113C 0C04ADB5 */  jal       get_msg_width
/* 187B30 80251140 0000282D */   daddu    $a1, $zero, $zero
/* 187B34 80251144 24040009 */  addiu     $a0, $zero, 0x9
/* 187B38 80251148 3C058028 */  lui       $a1, %hi(D_JP_8028374C)
/* 187B3C 8025114C 24A5374C */  addiu     $a1, $a1, %lo(D_JP_8028374C)
/* 187B40 80251150 0240302D */  daddu     $a2, $s2, $zero
/* 187B44 80251154 86230012 */  lh        $v1, 0x12($s1)
/* 187B48 80251158 24420037 */  addiu     $v0, $v0, 0x37
/* 187B4C 8025115C 00031880 */  sll       $v1, $v1, 2
/* 187B50 80251160 00651821 */  addu      $v1, $v1, $a1
/* 187B54 80251164 80650000 */  lb        $a1, 0x0($v1)
/* 187B58 80251168 80670001 */  lb        $a3, 0x1($v1)
/* 187B5C 8025116C 3C038025 */  lui       $v1, %hi(btl_message_popup_draw_content)
/* 187B60 80251170 246307FC */  addiu     $v1, $v1, %lo(btl_message_popup_draw_content)
/* 187B64 80251174 AFA30018 */  sw        $v1, 0x18($sp)
/* 187B68 80251178 2403FFFF */  addiu     $v1, $zero, -0x1
/* 187B6C 8025117C AFA00014 */  sw        $zero, 0x14($sp)
/* 187B70 80251180 AFB1001C */  sw        $s1, 0x1C($sp)
/* 187B74 80251184 AFA30020 */  sw        $v1, 0x20($sp)
/* 187B78 80251188 00454021 */  addu      $t0, $v0, $a1
/* 187B7C 8025118C 080944FD */  j         .LJP_802513F4
/* 187B80 80251190 24E90028 */   addiu    $t1, $a3, 0x28
.LJP_80251194:
/* 187B84 80251194 82220017 */  lb        $v0, 0x17($s1)
/* 187B88 80251198 104000A3 */  beqz      $v0, .LJP_80251428
/* 187B8C 8025119C 00000000 */   nop
/* 187B90 802511A0 86220012 */  lh        $v0, 0x12($s1)
/* 187B94 802511A4 A2200017 */  sb        $zero, 0x17($s1)
/* 187B98 802511A8 00021080 */  sll       $v0, $v0, 2
/* 187B9C 802511AC 3C048028 */  lui       $a0, %hi(BattleMessages)
/* 187BA0 802511B0 00822021 */  addu      $a0, $a0, $v0
/* 187BA4 802511B4 8C843A34 */  lw        $a0, %lo(BattleMessages)($a0)
/* 187BA8 802511B8 0C04ADB5 */  jal       get_msg_width
/* 187BAC 802511BC 0000282D */   daddu    $a1, $zero, $zero
/* 187BB0 802511C0 3C058028 */  lui       $a1, %hi(D_JP_8028374C)
/* 187BB4 802511C4 24A5374C */  addiu     $a1, $a1, %lo(D_JP_8028374C)
/* 187BB8 802511C8 86240012 */  lh        $a0, 0x12($s1)
/* 187BBC 802511CC 2442001F */  addiu     $v0, $v0, 0x1F
/* 187BC0 802511D0 00041880 */  sll       $v1, $a0, 2
/* 187BC4 802511D4 00652821 */  addu      $a1, $v1, $a1
/* 187BC8 802511D8 2484FFF6 */  addiu     $a0, $a0, -0xA
/* 187BCC 802511DC 80A30000 */  lb        $v1, 0x0($a1)
/* 187BD0 802511E0 00042080 */  sll       $a0, $a0, 2
/* 187BD4 802511E4 00434021 */  addu      $t0, $v0, $v1
/* 187BD8 802511E8 000817C2 */  srl       $v0, $t0, 31
/* 187BDC 802511EC 01021021 */  addu      $v0, $t0, $v0
/* 187BE0 802511F0 00021043 */  sra       $v0, $v0, 1
/* 187BE4 802511F4 240300A0 */  addiu     $v1, $zero, 0xA0
/* 187BE8 802511F8 00621823 */  subu      $v1, $v1, $v0
/* 187BEC 802511FC 3C028028 */  lui       $v0, %hi(D_JP_80283B88)
/* 187BF0 80251200 00441021 */  addu      $v0, $v0, $a0
/* 187BF4 80251204 8C423B88 */  lw        $v0, %lo(D_JP_80283B88)($v0)
/* 187BF8 80251208 10400004 */  beqz      $v0, .LJP_8025121C
/* 187BFC 8025120C 0100382D */   daddu    $a3, $t0, $zero
/* 187C00 80251210 80A20001 */  lb        $v0, 0x1($a1)
/* 187C04 80251214 08094489 */  j         .LJP_80251224
/* 187C08 80251218 2449002D */   addiu    $t1, $v0, 0x2D
.LJP_8025121C:
/* 187C0C 8025121C 80A20001 */  lb        $v0, 0x1($a1)
/* 187C10 80251220 2449001C */  addiu     $t1, $v0, 0x1C
.LJP_80251224:
/* 187C14 80251224 24040009 */  addiu     $a0, $zero, 0x9
/* 187C18 80251228 0060282D */  daddu     $a1, $v1, $zero
/* 187C1C 8025122C 0240302D */  daddu     $a2, $s2, $zero
/* 187C20 80251230 3C028025 */  lui       $v0, %hi(btl_message_popup_draw_content)
/* 187C24 80251234 244207FC */  addiu     $v0, $v0, %lo(btl_message_popup_draw_content)
/* 187C28 80251238 AFA20018 */  sw        $v0, 0x18($sp)
/* 187C2C 8025123C 2402FFFF */  addiu     $v0, $zero, -0x1
/* 187C30 80251240 AFA90010 */  sw        $t1, 0x10($sp)
/* 187C34 80251244 AFA00014 */  sw        $zero, 0x14($sp)
/* 187C38 80251248 AFB1001C */  sw        $s1, 0x1C($sp)
/* 187C3C 8025124C 08094504 */  j         .LJP_80251410
/* 187C40 80251250 AFA20020 */   sw       $v0, 0x20($sp)
.LJP_80251254:
/* 187C44 80251254 82220017 */  lb        $v0, 0x17($s1)
/* 187C48 80251258 10400073 */  beqz      $v0, .LJP_80251428
/* 187C4C 8025125C 00000000 */   nop
/* 187C50 80251260 86220012 */  lh        $v0, 0x12($s1)
/* 187C54 80251264 A2200017 */  sb        $zero, 0x17($s1)
/* 187C58 80251268 00021080 */  sll       $v0, $v0, 2
/* 187C5C 8025126C 3C048028 */  lui       $a0, %hi(BattleMessages)
/* 187C60 80251270 00822021 */  addu      $a0, $a0, $v0
/* 187C64 80251274 8C843A34 */  lw        $a0, %lo(BattleMessages)($a0)
/* 187C68 80251278 0C04ADB5 */  jal       get_msg_width
/* 187C6C 8025127C 0000282D */   daddu    $a1, $zero, $zero
/* 187C70 80251280 3C058028 */  lui       $a1, %hi(D_JP_8028374C)
/* 187C74 80251284 24A5374C */  addiu     $a1, $a1, %lo(D_JP_8028374C)
/* 187C78 80251288 86240012 */  lh        $a0, 0x12($s1)
/* 187C7C 8025128C 2442001F */  addiu     $v0, $v0, 0x1F
/* 187C80 80251290 00041880 */  sll       $v1, $a0, 2
/* 187C84 80251294 00652821 */  addu      $a1, $v1, $a1
/* 187C88 80251298 2484FFEE */  addiu     $a0, $a0, -0x12
/* 187C8C 8025129C 80A30000 */  lb        $v1, 0x0($a1)
/* 187C90 802512A0 00042080 */  sll       $a0, $a0, 2
/* 187C94 802512A4 00434021 */  addu      $t0, $v0, $v1
/* 187C98 802512A8 000817C2 */  srl       $v0, $t0, 31
/* 187C9C 802512AC 01021021 */  addu      $v0, $t0, $v0
/* 187CA0 802512B0 00021043 */  sra       $v0, $v0, 1
/* 187CA4 802512B4 240300A0 */  addiu     $v1, $zero, 0xA0
/* 187CA8 802512B8 00621823 */  subu      $v1, $v1, $v0
/* 187CAC 802512BC 3C028028 */  lui       $v0, %hi(D_JP_80283BA8)
/* 187CB0 802512C0 00441021 */  addu      $v0, $v0, $a0
/* 187CB4 802512C4 8C423BA8 */  lw        $v0, %lo(D_JP_80283BA8)($v0)
/* 187CB8 802512C8 10400004 */  beqz      $v0, .LJP_802512DC
/* 187CBC 802512CC 0100382D */   daddu    $a3, $t0, $zero
/* 187CC0 802512D0 80A20001 */  lb        $v0, 0x1($a1)
/* 187CC4 802512D4 080944B9 */  j         .LJP_802512E4
/* 187CC8 802512D8 2449002D */   addiu    $t1, $v0, 0x2D
.LJP_802512DC:
/* 187CCC 802512DC 80A20001 */  lb        $v0, 0x1($a1)
/* 187CD0 802512E0 2449001C */  addiu     $t1, $v0, 0x1C
.LJP_802512E4:
/* 187CD4 802512E4 24040009 */  addiu     $a0, $zero, 0x9
/* 187CD8 802512E8 0060282D */  daddu     $a1, $v1, $zero
/* 187CDC 802512EC 0240302D */  daddu     $a2, $s2, $zero
/* 187CE0 802512F0 3C028025 */  lui       $v0, %hi(btl_message_popup_draw_content)
/* 187CE4 802512F4 244207FC */  addiu     $v0, $v0, %lo(btl_message_popup_draw_content)
/* 187CE8 802512F8 AFA20018 */  sw        $v0, 0x18($sp)
/* 187CEC 802512FC 2402FFFF */  addiu     $v0, $zero, -0x1
/* 187CF0 80251300 AFA90010 */  sw        $t1, 0x10($sp)
/* 187CF4 80251304 AFA00014 */  sw        $zero, 0x14($sp)
/* 187CF8 80251308 AFB1001C */  sw        $s1, 0x1C($sp)
/* 187CFC 8025130C 08094504 */  j         .LJP_80251410
/* 187D00 80251310 AFA20020 */   sw       $v0, 0x20($sp)
.LJP_80251314:
/* 187D04 80251314 82220017 */  lb        $v0, 0x17($s1)
/* 187D08 80251318 10400043 */  beqz      $v0, .LJP_80251428
/* 187D0C 8025131C 00000000 */   nop
/* 187D10 80251320 86220012 */  lh        $v0, 0x12($s1)
/* 187D14 80251324 A2200017 */  sb        $zero, 0x17($s1)
/* 187D18 80251328 3C04802A */  lui       $a0, %hi(BattlePopupMessageVar)
/* 187D1C 8025132C 8484F940 */  lh        $a0, %lo(BattlePopupMessageVar)($a0)
/* 187D20 80251330 00021080 */  sll       $v0, $v0, 2
/* 187D24 80251334 3C108028 */  lui       $s0, %hi(BattleMessages)
/* 187D28 80251338 02028021 */  addu      $s0, $s0, $v0
/* 187D2C 8025133C 8E103A34 */  lw        $s0, %lo(BattleMessages)($s0)
/* 187D30 80251340 0C04AB92 */  jal       set_message_int_var
/* 187D34 80251344 0000282D */   daddu    $a1, $zero, $zero
/* 187D38 80251348 0000282D */  daddu     $a1, $zero, $zero
/* 187D3C 8025134C 080944E8 */  j         .LJP_802513A0
/* 187D40 80251350 0200202D */   daddu    $a0, $s0, $zero
.LJP_80251354:
/* 187D44 80251354 82220017 */  lb        $v0, 0x17($s1)
/* 187D48 80251358 10400033 */  beqz      $v0, .LJP_80251428
/* 187D4C 8025135C 00000000 */   nop
/* 187D50 80251360 A2200017 */  sb        $zero, 0x17($s1)
/* 187D54 80251364 3C03802A */  lui       $v1, %hi(BattlePopupMessageVar)
/* 187D58 80251368 8463F940 */  lh        $v1, %lo(BattlePopupMessageVar)($v1)
/* 187D5C 8025136C 86220012 */  lh        $v0, 0x12($s1)
/* 187D60 80251370 00031880 */  sll       $v1, $v1, 2
/* 187D64 80251374 00021080 */  sll       $v0, $v0, 2
/* 187D68 80251378 3C048028 */  lui       $a0, %hi(bActorMessages)
/* 187D6C 8025137C 00832021 */  addu      $a0, $a0, $v1
/* 187D70 80251380 8C843BC8 */  lw        $a0, %lo(bActorMessages)($a0)
/* 187D74 80251384 3C108028 */  lui       $s0, %hi(BattleMessages)
/* 187D78 80251388 02028021 */  addu      $s0, $s0, $v0
/* 187D7C 8025138C 8E103A34 */  lw        $s0, %lo(BattleMessages)($s0)
/* 187D80 80251390 0C04AB67 */  jal       set_message_text_var
/* 187D84 80251394 0000282D */   daddu    $a1, $zero, $zero
/* 187D88 80251398 0200202D */  daddu     $a0, $s0, $zero
/* 187D8C 8025139C 0000282D */  daddu     $a1, $zero, $zero
.LJP_802513A0:
/* 187D90 802513A0 0C04ADB5 */  jal       get_msg_width
/* 187D94 802513A4 00000000 */   nop
/* 187D98 802513A8 24040009 */  addiu     $a0, $zero, 0x9
/* 187D9C 802513AC 3C058028 */  lui       $a1, %hi(D_JP_8028374C)
/* 187DA0 802513B0 24A5374C */  addiu     $a1, $a1, %lo(D_JP_8028374C)
/* 187DA4 802513B4 0240302D */  daddu     $a2, $s2, $zero
/* 187DA8 802513B8 86230012 */  lh        $v1, 0x12($s1)
/* 187DAC 802513BC 2442001F */  addiu     $v0, $v0, 0x1F
/* 187DB0 802513C0 00031880 */  sll       $v1, $v1, 2
/* 187DB4 802513C4 00651821 */  addu      $v1, $v1, $a1
/* 187DB8 802513C8 80650000 */  lb        $a1, 0x0($v1)
/* 187DBC 802513CC 80670001 */  lb        $a3, 0x1($v1)
/* 187DC0 802513D0 3C038025 */  lui       $v1, %hi(btl_message_popup_draw_content)
/* 187DC4 802513D4 246307FC */  addiu     $v1, $v1, %lo(btl_message_popup_draw_content)
/* 187DC8 802513D8 AFA30018 */  sw        $v1, 0x18($sp)
/* 187DCC 802513DC 2403FFFF */  addiu     $v1, $zero, -0x1
/* 187DD0 802513E0 AFA00014 */  sw        $zero, 0x14($sp)
/* 187DD4 802513E4 AFB1001C */  sw        $s1, 0x1C($sp)
/* 187DD8 802513E8 AFA30020 */  sw        $v1, 0x20($sp)
/* 187DDC 802513EC 00454021 */  addu      $t0, $v0, $a1
/* 187DE0 802513F0 24E9001C */  addiu     $t1, $a3, 0x1C
.LJP_802513F4:
/* 187DE4 802513F4 00082FC2 */  srl       $a1, $t0, 31
/* 187DE8 802513F8 01052821 */  addu      $a1, $t0, $a1
/* 187DEC 802513FC 00052843 */  sra       $a1, $a1, 1
/* 187DF0 80251400 240200A0 */  addiu     $v0, $zero, 0xA0
/* 187DF4 80251404 00452823 */  subu      $a1, $v0, $a1
/* 187DF8 80251408 0100382D */  daddu     $a3, $t0, $zero
/* 187DFC 8025140C AFA90010 */  sw        $t1, 0x10($sp)
.LJP_80251410:
/* 187E00 80251410 0C05335E */  jal       set_window_properties
/* 187E04 80251414 00000000 */   nop
.LJP_80251418:
/* 187E08 80251418 24040009 */  addiu     $a0, $zero, 0x9
/* 187E0C 8025141C 24050001 */  addiu     $a1, $zero, 0x1
.LJP_80251420:
/* 187E10 80251420 0C0533CB */  jal       set_window_update
/* 187E14 80251424 00000000 */   nop
.LJP_80251428:
/* 187E18 80251428 8FBF0034 */  lw        $ra, 0x34($sp)
/* 187E1C 8025142C 8FB20030 */  lw        $s2, 0x30($sp)
/* 187E20 80251430 8FB1002C */  lw        $s1, 0x2C($sp)
/* 187E24 80251434 8FB00028 */  lw        $s0, 0x28($sp)
/* 187E28 80251438 03E00008 */  jr        $ra
/* 187E2C 8025143C 27BD0038 */   addiu    $sp, $sp, 0x38
.size btl_show_message_popup, . - btl_show_message_popup
