.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_JP_802BFE08
/* 328F78 802BFE08 802BE418 */ .word .L802BE418
/* 328F7C 802BFE0C 802BEABC */ .word .L802BEABC
/* 328F80 802BFE10 802BF494 */ .word .L802BF494
/* 328F84 802BFE14 802BF1A8 */ .word .L802BF1A8
/* 328F88 802BFE18 802BF1C0 */ .word .L802BF1C0
/* 328F8C 802BFE1C 802BF1F0 */ .word .L802BF1F0
/* 328F90 802BFE20 802BF494 */ .word .L802BF494
/* 328F94 802BFE24 802BF494 */ .word .L802BF494
/* 328F98 802BFE28 802BF494 */ .word .L802BF494
/* 328F9C 802BFE2C 802BF494 */ .word .L802BF494
/* 328FA0 802BFE30 802BF3A4 */ .word .L802BF3A4
/* 328FA4 802BFE34 802BF494 */ .word .L802BF494
/* 328FA8 802BFE38 802BF494 */ .word .L802BF494
/* 328FAC 802BFE3C 802BF494 */ .word .L802BF494
/* 328FB0 802BFE40 802BF494 */ .word .L802BF494
/* 328FB4 802BFE44 802BF494 */ .word .L802BF494
/* 328FB8 802BFE48 802BF494 */ .word .L802BF494
/* 328FBC 802BFE4C 802BF494 */ .word .L802BF494
/* 328FC0 802BFE50 802BF494 */ .word .L802BF494
/* 328FC4 802BFE54 802BF494 */ .word .L802BF494
/* 328FC8 802BFE58 802BE530 */ .word .L802BE530
/* 328FCC 802BFE5C 802BE720 */ .word .L802BE720
/* 328FD0 802BFE60 802BE97C */ .word .L802BE97C
/* 328FD4 802BFE64 802BE93C */ .word .L802BE93C
/* 328FD8 802BFE68 802BE97C */ .word .L802BE97C
/* 328FDC 802BFE6C 802BE988 */ .word .L802BE988
.size jtbl_JP_802BFE08, . - jtbl_JP_802BFE08

dlabel D_JP_802BFE70
/* 328FE0 802BFE70 3FE3333333333333 */ .double 0.599999999999999978
.size D_JP_802BFE70, . - D_JP_802BFE70


.section .text
/* Generated by spimdisasm 1.20.1 */

glabel world_sushie_UseAbility
/* 3274B8 802BE348 27BDFF90 */  addiu     $sp, $sp, -0x70
/* 3274BC 802BE34C AFB5005C */  sw        $s5, 0x5C($sp)
/* 3274C0 802BE350 0080A82D */  daddu     $s5, $a0, $zero
/* 3274C4 802BE354 AFB20050 */  sw        $s2, 0x50($sp)
/* 3274C8 802BE358 3C128011 */  lui       $s2, %hi(gPlayerStatus)
/* 3274CC 802BE35C 2652F188 */  addiu     $s2, $s2, %lo(gPlayerStatus)
/* 3274D0 802BE360 AFB00048 */  sw        $s0, 0x48($sp)
/* 3274D4 802BE364 3C108011 */  lui       $s0, %hi(gPlayerData)
/* 3274D8 802BE368 2610F450 */  addiu     $s0, $s0, %lo(gPlayerData)
/* 3274DC 802BE36C AFB60060 */  sw        $s6, 0x60($sp)
/* 3274E0 802BE370 3C168016 */  lui       $s6, %hi(gCollisionStatus)
/* 3274E4 802BE374 26D6F4D0 */  addiu     $s6, $s6, %lo(gCollisionStatus)
/* 3274E8 802BE378 AFB40058 */  sw        $s4, 0x58($sp)
/* 3274EC 802BE37C 3C148011 */  lui       $s4, %hi(gPartnerStatus)
/* 3274F0 802BE380 2694ED70 */  addiu     $s4, $s4, %lo(gPartnerStatus)
/* 3274F4 802BE384 AFBF0064 */  sw        $ra, 0x64($sp)
/* 3274F8 802BE388 AFB30054 */  sw        $s3, 0x54($sp)
/* 3274FC 802BE38C AFB1004C */  sw        $s1, 0x4C($sp)
/* 327500 802BE390 F7B40068 */  sdc1      $f20, 0x68($sp)
/* 327504 802BE394 8EB1014C */  lw        $s1, 0x14C($s5)
/* 327508 802BE398 10A0000F */  beqz      $a1, .L802BE3D8
/* 32750C 802BE39C 3C04FFBF */   lui      $a0, (0xFFBFFFFF >> 16)
/* 327510 802BE3A0 0C0AFE31 */  jal       world_sushie_try_cancel_tweester
/* 327514 802BE3A4 0220202D */   daddu    $a0, $s1, $zero
/* 327518 802BE3A8 3C01802C */  lui       $at, %hi(world_sushie_InertialMoveAngle)
/* 32751C 802BE3AC AC20FE9C */  sw        $zero, %lo(world_sushie_InertialMoveAngle)($at)
/* 327520 802BE3B0 3C01802C */  lui       $at, %hi(world_sushie_InertialMoveSpeed)
/* 327524 802BE3B4 AC20FE98 */  sw        $zero, %lo(world_sushie_InertialMoveSpeed)($at)
/* 327528 802BE3B8 3C01802C */  lui       $at, %hi(world_sushie_UnusedMoveX)
/* 32752C 802BE3BC AC20FEA0 */  sw        $zero, %lo(world_sushie_UnusedMoveX)($at)
/* 327530 802BE3C0 3C01802C */  lui       $at, %hi(world_sushie_UnusedMoveZ)
/* 327534 802BE3C4 AC20FEA4 */  sw        $zero, %lo(world_sushie_UnusedMoveZ)($at)
/* 327538 802BE3C8 3C01802C */  lui       $at, %hi(world_sushie_ResurfaceVelY)
/* 32753C 802BE3CC AC20FEA8 */  sw        $zero, %lo(world_sushie_ResurfaceVelY)($at)
/* 327540 802BE3D0 AEA00070 */  sw        $zero, 0x70($s5)
/* 327544 802BE3D4 3C04FFBF */  lui       $a0, (0xFFBFFFFF >> 16)
.L802BE3D8:
/* 327548 802BE3D8 3484FFFF */  ori       $a0, $a0, (0xFFBFFFFF & 0xFFFF)
/* 32754C 802BE3DC 8E020310 */  lw        $v0, 0x310($s0)
/* 327550 802BE3E0 8E430004 */  lw        $v1, 0x4($s2)
/* 327554 802BE3E4 24420001 */  addiu     $v0, $v0, 0x1
/* 327558 802BE3E8 00641824 */  and       $v1, $v1, $a0
/* 32755C 802BE3EC AE020310 */  sw        $v0, 0x310($s0)
/* 327560 802BE3F0 AE430004 */  sw        $v1, 0x4($s2)
/* 327564 802BE3F4 8EA30070 */  lw        $v1, 0x70($s5)
/* 327568 802BE3F8 2C62001A */  sltiu     $v0, $v1, 0x1A
/* 32756C 802BE3FC 10400425 */  beqz      $v0, .L802BF494
/* 327570 802BE400 00031080 */   sll      $v0, $v1, 2
/* 327574 802BE404 3C01802C */  lui       $at, %hi(jtbl_JP_802BFE08)
/* 327578 802BE408 00220821 */  addu      $at, $at, $v0
/* 32757C 802BE40C 8C22FE08 */  lw        $v0, %lo(jtbl_JP_802BFE08)($at)
/* 327580 802BE410 00400008 */  jr        $v0
/* 327584 802BE414 00000000 */   nop
.L802BE418:
/* 327588 802BE418 3C138007 */  lui       $s3, %hi(gGameStatusPtr)
/* 32758C 802BE41C 2673417C */  addiu     $s3, $s3, %lo(gGameStatusPtr)
/* 327590 802BE420 8E620000 */  lw        $v0, 0x0($s3)
/* 327594 802BE424 8042007D */  lb        $v0, 0x7D($v0)
/* 327598 802BE428 14400012 */  bnez      $v0, .L802BE474
/* 32759C 802BE42C 3C040008 */   lui      $a0, (0x8000F >> 16)
/* 3275A0 802BE430 86C40012 */  lh        $a0, 0x12($s6)
/* 3275A4 802BE434 0480000A */  bltz      $a0, .L802BE460
/* 3275A8 802BE438 AFA40040 */   sw       $a0, 0x40($sp)
/* 3275AC 802BE43C 30824000 */  andi      $v0, $a0, 0x4000
/* 3275B0 802BE440 14400415 */  bnez      $v0, .L802BF498
/* 3275B4 802BE444 24020001 */   addiu    $v0, $zero, 0x1
/* 3275B8 802BE448 0C016E96 */  jal       get_collider_flags
/* 3275BC 802BE44C 00000000 */   nop
/* 3275C0 802BE450 304200FF */  andi      $v0, $v0, 0xFF
/* 3275C4 802BE454 24030004 */  addiu     $v1, $zero, 0x4
/* 3275C8 802BE458 10430003 */  beq       $v0, $v1, .L802BE468
/* 3275CC 802BE45C AFA20040 */   sw       $v0, 0x40($sp)
.L802BE460:
/* 3275D0 802BE460 080AFD26 */  j         .L802BF498
/* 3275D4 802BE464 24020001 */   addiu    $v0, $zero, 0x1
.L802BE468:
/* 3275D8 802BE468 24020014 */  addiu     $v0, $zero, 0x14
/* 3275DC 802BE46C 080AFD25 */  j         .L802BF494
/* 3275E0 802BE470 AEA20070 */   sw       $v0, 0x70($s5)
.L802BE474:
/* 3275E4 802BE474 C622003C */  lwc1      $f2, 0x3C($s1)
/* 3275E8 802BE478 3C014180 */  lui       $at, (0x41800000 >> 16)
/* 3275EC 802BE47C 44810000 */  mtc1      $at, $f0
/* 3275F0 802BE480 3484000F */  ori       $a0, $a0, (0x8000F & 0xFFFF)
/* 3275F4 802BE484 46001000 */  add.s     $f0, $f2, $f0
/* 3275F8 802BE488 24100001 */  addiu     $s0, $zero, 0x1
/* 3275FC 802BE48C E6220064 */  swc1      $f2, 0x64($s1)
/* 327600 802BE490 E640002C */  swc1      $f0, 0x2C($s2)
/* 327604 802BE494 8E220000 */  lw        $v0, 0x0($s1)
/* 327608 802BE498 2403FDFF */  addiu     $v1, $zero, -0x201
/* 32760C 802BE49C 3C01802C */  lui       $at, %hi(world_sushie_IsRiding)
/* 327610 802BE4A0 AC30FE8C */  sw        $s0, %lo(world_sushie_IsRiding)($at)
/* 327614 802BE4A4 34420008 */  ori       $v0, $v0, 0x8
/* 327618 802BE4A8 00431024 */  and       $v0, $v0, $v1
/* 32761C 802BE4AC 34420100 */  ori       $v0, $v0, 0x100
/* 327620 802BE4B0 0C037FD6 */  jal       suggest_player_anim_always_forward
/* 327624 802BE4B4 AE220000 */   sw       $v0, 0x0($s1)
/* 327628 802BE4B8 0C038031 */  jal       disable_player_shadow
/* 32762C 802BE4BC 00000000 */   nop
/* 327630 802BE4C0 0C00EA2F */  jal       disable_npc_shadow
/* 327634 802BE4C4 0220202D */   daddu    $a0, $s1, $zero
/* 327638 802BE4C8 0220202D */  daddu     $a0, $s1, $zero
/* 32763C 802BE4CC 24050004 */  addiu     $a1, $zero, 0x4
/* 327640 802BE4D0 24060002 */  addiu     $a2, $zero, 0x2
/* 327644 802BE4D4 0000382D */  daddu     $a3, $zero, $zero
/* 327648 802BE4D8 AFA00010 */  sw        $zero, 0x10($sp)
/* 32764C 802BE4DC AFA00014 */  sw        $zero, 0x14($sp)
/* 327650 802BE4E0 0C00F4B9 */  jal       npc_set_imgfx_params
/* 327654 802BE4E4 AFA00018 */   sw       $zero, 0x18($sp)
/* 327658 802BE4E8 3C020007 */  lui       $v0, (0x7000A >> 16)
/* 32765C 802BE4EC 3442000A */  ori       $v0, $v0, (0x7000A & 0xFFFF)
/* 327660 802BE4F0 AE220028 */  sw        $v0, 0x28($s1)
/* 327664 802BE4F4 C640005C */  lwc1      $f0, 0x5C($s2)
/* 327668 802BE4F8 8E620000 */  lw        $v0, 0x0($s3)
/* 32766C 802BE4FC AE200014 */  sw        $zero, 0x14($s1)
/* 327670 802BE500 E6200018 */  swc1      $f0, 0x18($s1)
/* 327674 802BE504 A2900000 */  sb        $s0, 0x0($s4)
/* 327678 802BE508 A040007D */  sb        $zero, 0x7D($v0)
/* 32767C 802BE50C 24020007 */  addiu     $v0, $zero, 0x7
/* 327680 802BE510 A2820003 */  sb        $v0, 0x3($s4)
/* 327684 802BE514 3C01802C */  lui       $at, %hi(world_sushie_DiveState)
/* 327688 802BE518 AC20FE84 */  sw        $zero, %lo(world_sushie_DiveState)($at)
/* 32768C 802BE51C 3C01802C */  lui       $at, %hi(world_sushie_DiveTime)
/* 327690 802BE520 AC20FE88 */  sw        $zero, %lo(world_sushie_DiveTime)($at)
/* 327694 802BE524 AEA00078 */  sw        $zero, 0x78($s5)
/* 327698 802BE528 080AFD25 */  j         .L802BF494
/* 32769C 802BE52C AEB00070 */   sw       $s0, 0x70($s5)
.L802BE530:
/* 3276A0 802BE530 86C40012 */  lh        $a0, 0x12($s6)
/* 3276A4 802BE534 0480FFCA */  bltz      $a0, .L802BE460
/* 3276A8 802BE538 27B00020 */   addiu    $s0, $sp, 0x20
/* 3276AC 802BE53C 0200282D */  daddu     $a1, $s0, $zero
/* 3276B0 802BE540 27B30024 */  addiu     $s3, $sp, 0x24
/* 3276B4 802BE544 0260302D */  daddu     $a2, $s3, $zero
/* 3276B8 802BE548 27B40028 */  addiu     $s4, $sp, 0x28
/* 3276BC 802BE54C 0C016EB0 */  jal       get_collider_center
/* 3276C0 802BE550 0280382D */   daddu    $a3, $s4, $zero
/* 3276C4 802BE554 C7AC0020 */  lwc1      $f12, 0x20($sp)
/* 3276C8 802BE558 C7AE0028 */  lwc1      $f14, 0x28($sp)
/* 3276CC 802BE55C 8E460028 */  lw        $a2, 0x28($s2)
/* 3276D0 802BE560 0C00A710 */  jal       atan2
/* 3276D4 802BE564 8E470030 */   lw       $a3, 0x30($s2)
/* 3276D8 802BE568 0000202D */  daddu     $a0, $zero, $zero
/* 3276DC 802BE56C 0200282D */  daddu     $a1, $s0, $zero
/* 3276E0 802BE570 0260302D */  daddu     $a2, $s3, $zero
/* 3276E4 802BE574 864200B2 */  lh        $v0, 0xB2($s2)
/* 3276E8 802BE578 0280382D */  daddu     $a3, $s4, $zero
/* 3276EC 802BE57C E7A0002C */  swc1      $f0, 0x2C($sp)
/* 3276F0 802BE580 C6400028 */  lwc1      $f0, 0x28($s2)
/* 3276F4 802BE584 C644002C */  lwc1      $f4, 0x2C($s2)
/* 3276F8 802BE588 C6460030 */  lwc1      $f6, 0x30($s2)
/* 3276FC 802BE58C 3C013F00 */  lui       $at, (0x3F000000 >> 16)
/* 327700 802BE590 4481A000 */  mtc1      $at, $f20
/* 327704 802BE594 44821000 */  mtc1      $v0, $f2
/* 327708 802BE598 00000000 */  nop
/* 32770C 802BE59C 468010A0 */  cvt.s.w   $f2, $f2
/* 327710 802BE5A0 864200B2 */  lh        $v0, 0xB2($s2)
/* 327714 802BE5A4 46141082 */  mul.s     $f2, $f2, $f20
/* 327718 802BE5A8 00000000 */  nop
/* 32771C 802BE5AC E7A00020 */  swc1      $f0, 0x20($sp)
/* 327720 802BE5B0 E7A40024 */  swc1      $f4, 0x24($sp)
/* 327724 802BE5B4 E7A60028 */  swc1      $f6, 0x28($sp)
/* 327728 802BE5B8 44820000 */  mtc1      $v0, $f0
/* 32772C 802BE5BC 00000000 */  nop
/* 327730 802BE5C0 46800020 */  cvt.s.w   $f0, $f0
/* 327734 802BE5C4 46000000 */  add.s     $f0, $f0, $f0
/* 327738 802BE5C8 27A2002C */  addiu     $v0, $sp, 0x2C
/* 32773C 802BE5CC AFA20018 */  sw        $v0, 0x18($sp)
/* 327740 802BE5D0 E7A00014 */  swc1      $f0, 0x14($sp)
/* 327744 802BE5D4 0C0AF889 */  jal       world_sushie_test_ray_to_wall_center
/* 327748 802BE5D8 E7A20010 */   swc1     $f2, 0x10($sp)
/* 32774C 802BE5DC 2403FFFF */  addiu     $v1, $zero, -0x1
/* 327750 802BE5E0 04400004 */  bltz      $v0, .L802BE5F4
/* 327754 802BE5E4 AFA20040 */   sw       $v0, 0x40($sp)
/* 327758 802BE5E8 0C016E96 */  jal       get_collider_flags
/* 32775C 802BE5EC 0040202D */   daddu    $a0, $v0, $zero
/* 327760 802BE5F0 304300FF */  andi      $v1, $v0, 0xFF
.L802BE5F4:
/* 327764 802BE5F4 24020004 */  addiu     $v0, $zero, 0x4
/* 327768 802BE5F8 146203A7 */  bne       $v1, $v0, .L802BF498
/* 32776C 802BE5FC 24020001 */   addiu    $v0, $zero, 0x1
/* 327770 802BE600 3C01802C */  lui       $at, %hi(world_sushie_IsRiding)
/* 327774 802BE604 AC22FE8C */  sw        $v0, %lo(world_sushie_IsRiding)($at)
/* 327778 802BE608 0C039761 */  jal       set_action_state
/* 32777C 802BE60C 24040021 */   addiu    $a0, $zero, 0x21
/* 327780 802BE610 0C03803D */  jal       disable_player_static_collisions
/* 327784 802BE614 00000000 */   nop
/* 327788 802BE618 0C038056 */  jal       disable_player_input
/* 32778C 802BE61C 00000000 */   nop
/* 327790 802BE620 3C020008 */  lui       $v0, (0x80000 >> 16)
/* 327794 802BE624 AE220080 */  sw        $v0, 0x80($s1)
/* 327798 802BE628 C6400028 */  lwc1      $f0, 0x28($s2)
/* 32779C 802BE62C 3C064220 */  lui       $a2, (0x42200000 >> 16)
/* 3277A0 802BE630 E6200060 */  swc1      $f0, 0x60($s1)
/* 3277A4 802BE634 C640002C */  lwc1      $f0, 0x2C($s2)
/* 3277A8 802BE638 E6200064 */  swc1      $f0, 0x64($s1)
/* 3277AC 802BE63C C6420030 */  lwc1      $f2, 0x30($s2)
/* 3277B0 802BE640 C7A0002C */  lwc1      $f0, 0x2C($sp)
/* 3277B4 802BE644 26240060 */  addiu     $a0, $s1, 0x60
/* 3277B8 802BE648 E620000C */  swc1      $f0, 0xC($s1)
/* 3277BC 802BE64C E6220068 */  swc1      $f2, 0x68($s1)
/* 3277C0 802BE650 E6400080 */  swc1      $f0, 0x80($s2)
/* 3277C4 802BE654 8E27000C */  lw        $a3, 0xC($s1)
/* 3277C8 802BE658 3C0142B4 */  lui       $at, (0x42B40000 >> 16)
/* 3277CC 802BE65C 44810000 */  mtc1      $at, $f0
/* 3277D0 802BE660 26250068 */  addiu     $a1, $s1, 0x68
/* 3277D4 802BE664 0C00A7D7 */  jal       add_vec2D_polar
/* 3277D8 802BE668 E6200034 */   swc1     $f0, 0x34($s1)
/* 3277DC 802BE66C C6200060 */  lwc1      $f0, 0x60($s1)
/* 3277E0 802BE670 C6220064 */  lwc1      $f2, 0x64($s1)
/* 3277E4 802BE674 C6240068 */  lwc1      $f4, 0x68($s1)
/* 3277E8 802BE678 3C0142C8 */  lui       $at, (0x42C80000 >> 16)
/* 3277EC 802BE67C 44813000 */  mtc1      $at, $f6
/* 3277F0 802BE680 27A20030 */  addiu     $v0, $sp, 0x30
/* 3277F4 802BE684 E7A00020 */  swc1      $f0, 0x20($sp)
/* 3277F8 802BE688 E7A20024 */  swc1      $f2, 0x24($sp)
/* 3277FC 802BE68C E7A40028 */  swc1      $f4, 0x28($sp)
/* 327800 802BE690 E7A60030 */  swc1      $f6, 0x30($sp)
/* 327804 802BE694 AFA20010 */  sw        $v0, 0x10($sp)
/* 327808 802BE698 C620000C */  lwc1      $f0, 0xC($s1)
/* 32780C 802BE69C 0200282D */  daddu     $a1, $s0, $zero
/* 327810 802BE6A0 E7A00014 */  swc1      $f0, 0x14($sp)
/* 327814 802BE6A4 862200A6 */  lh        $v0, 0xA6($s1)
/* 327818 802BE6A8 0260302D */  daddu     $a2, $s3, $zero
/* 32781C 802BE6AC 44820000 */  mtc1      $v0, $f0
/* 327820 802BE6B0 00000000 */  nop
/* 327824 802BE6B4 46800020 */  cvt.s.w   $f0, $f0
/* 327828 802BE6B8 E7A00018 */  swc1      $f0, 0x18($sp)
/* 32782C 802BE6BC 8E240080 */  lw        $a0, 0x80($s1)
/* 327830 802BE6C0 0C0371D6 */  jal       npc_raycast_down_around
/* 327834 802BE6C4 0280382D */   daddu    $a3, $s4, $zero
/* 327838 802BE6C8 3C050007 */  lui       $a1, (0x70003 >> 16)
/* 32783C 802BE6CC 34A50003 */  ori       $a1, $a1, (0x70003 & 0xFFFF)
/* 327840 802BE6D0 862300A8 */  lh        $v1, 0xA8($s1)
/* 327844 802BE6D4 3C040001 */  lui       $a0, (0x10002 >> 16)
/* 327848 802BE6D8 44830000 */  mtc1      $v1, $f0
/* 32784C 802BE6DC 00000000 */  nop
/* 327850 802BE6E0 46800020 */  cvt.s.w   $f0, $f0
/* 327854 802BE6E4 46140002 */  mul.s     $f0, $f0, $f20
/* 327858 802BE6E8 00000000 */  nop
/* 32785C 802BE6EC C7A20024 */  lwc1      $f2, 0x24($sp)
/* 327860 802BE6F0 34840002 */  ori       $a0, $a0, (0x10002 & 0xFFFF)
/* 327864 802BE6F4 AFA20040 */  sw        $v0, 0x40($sp)
/* 327868 802BE6F8 2402000C */  addiu     $v0, $zero, 0xC
/* 32786C 802BE6FC 46001081 */  sub.s     $f2, $f2, $f0
/* 327870 802BE700 AE250028 */  sw        $a1, 0x28($s1)
/* 327874 802BE704 A622008E */  sh        $v0, 0x8E($s1)
/* 327878 802BE708 0C037FB7 */  jal       suggest_player_anim_allow_backward
/* 32787C 802BE70C E6220064 */   swc1     $f2, 0x64($s1)
/* 327880 802BE710 8EA20070 */  lw        $v0, 0x70($s5)
/* 327884 802BE714 24420001 */  addiu     $v0, $v0, 0x1
/* 327888 802BE718 080AFD25 */  j         .L802BF494
/* 32788C 802BE71C AEA20070 */   sw       $v0, 0x70($s5)
.L802BE720:
/* 327890 802BE720 C6200060 */  lwc1      $f0, 0x60($s1)
/* 327894 802BE724 C62A0038 */  lwc1      $f10, 0x38($s1)
/* 327898 802BE728 8622008E */  lh        $v0, 0x8E($s1)
/* 32789C 802BE72C C6240064 */  lwc1      $f4, 0x64($s1)
/* 3278A0 802BE730 C628003C */  lwc1      $f8, 0x3C($s1)
/* 3278A4 802BE734 C6260040 */  lwc1      $f6, 0x40($s1)
/* 3278A8 802BE738 44821000 */  mtc1      $v0, $f2
/* 3278AC 802BE73C 00000000 */  nop
/* 3278B0 802BE740 468010A0 */  cvt.s.w   $f2, $f2
/* 3278B4 802BE744 0040202D */  daddu     $a0, $v0, $zero
/* 3278B8 802BE748 460A0001 */  sub.s     $f0, $f0, $f10
/* 3278BC 802BE74C 0080182D */  daddu     $v1, $a0, $zero
/* 3278C0 802BE750 9622008E */  lhu       $v0, 0x8E($s1)
/* 3278C4 802BE754 46082101 */  sub.s     $f4, $f4, $f8
/* 3278C8 802BE758 2442FFFF */  addiu     $v0, $v0, -0x1
/* 3278CC 802BE75C A622008E */  sh        $v0, 0x8E($s1)
/* 3278D0 802BE760 00021400 */  sll       $v0, $v0, 16
/* 3278D4 802BE764 46020003 */  div.s     $f0, $f0, $f2
/* 3278D8 802BE768 46005280 */  add.s     $f10, $f10, $f0
/* 3278DC 802BE76C C6220068 */  lwc1      $f2, 0x68($s1)
/* 3278E0 802BE770 44840000 */  mtc1      $a0, $f0
/* 3278E4 802BE774 00000000 */  nop
/* 3278E8 802BE778 46800020 */  cvt.s.w   $f0, $f0
/* 3278EC 802BE77C 46061081 */  sub.s     $f2, $f2, $f6
/* 3278F0 802BE780 46002103 */  div.s     $f4, $f4, $f0
/* 3278F4 802BE784 44830000 */  mtc1      $v1, $f0
/* 3278F8 802BE788 00000000 */  nop
/* 3278FC 802BE78C 46800020 */  cvt.s.w   $f0, $f0
/* 327900 802BE790 46044200 */  add.s     $f8, $f8, $f4
/* 327904 802BE794 00021C03 */  sra       $v1, $v0, 16
/* 327908 802BE798 46001083 */  div.s     $f2, $f2, $f0
/* 32790C 802BE79C 46023180 */  add.s     $f6, $f6, $f2
/* 327910 802BE7A0 E62A0038 */  swc1      $f10, 0x38($s1)
/* 327914 802BE7A4 E628003C */  swc1      $f8, 0x3C($s1)
/* 327918 802BE7A8 1060000D */  beqz      $v1, .LJP_802BE7E0
/* 32791C 802BE7AC E6260040 */   swc1     $f6, 0x40($s1)
/* 327920 802BE7B0 24020002 */  addiu     $v0, $zero, 0x2
/* 327924 802BE7B4 14620338 */  bne       $v1, $v0, .L802BF498
/* 327928 802BE7B8 0000102D */   daddu    $v0, $zero, $zero
/* 32792C 802BE7BC 24042081 */  addiu     $a0, $zero, 0x2081
/* 327930 802BE7C0 0000282D */  daddu     $a1, $zero, $zero
/* 327934 802BE7C4 0C053B6E */  jal       sfx_play_sound_at_npc
/* 327938 802BE7C8 2406FFFC */   addiu    $a2, $zero, -0x4
/* 32793C 802BE7CC 3C040001 */  lui       $a0, (0x10006 >> 16)
/* 327940 802BE7D0 0C037FB7 */  jal       suggest_player_anim_allow_backward
/* 327944 802BE7D4 34840006 */   ori      $a0, $a0, (0x10006 & 0xFFFF)
/* 327948 802BE7D8 080AFD26 */  j         .L802BF498
/* 32794C 802BE7DC 0000102D */   daddu    $v0, $zero, $zero
.LJP_802BE7E0:
/* 327950 802BE7E0 0220202D */  daddu     $a0, $s1, $zero
/* 327954 802BE7E4 8E220000 */  lw        $v0, 0x0($s1)
/* 327958 802BE7E8 3C030001 */  lui       $v1, (0x10000 >> 16)
/* 32795C 802BE7EC AE230080 */  sw        $v1, 0x80($s1)
/* 327960 802BE7F0 2403FDBF */  addiu     $v1, $zero, -0x241
/* 327964 802BE7F4 34420008 */  ori       $v0, $v0, 0x8
/* 327968 802BE7F8 00431024 */  and       $v0, $v0, $v1
/* 32796C 802BE7FC 0C00EA2F */  jal       disable_npc_shadow
/* 327970 802BE800 AE220000 */   sw       $v0, 0x0($s1)
/* 327974 802BE804 0220202D */  daddu     $a0, $s1, $zero
/* 327978 802BE808 24050004 */  addiu     $a1, $zero, 0x4
/* 32797C 802BE80C 24060002 */  addiu     $a2, $zero, 0x2
/* 327980 802BE810 0000382D */  daddu     $a3, $zero, $zero
/* 327984 802BE814 AFA00010 */  sw        $zero, 0x10($sp)
/* 327988 802BE818 AFA00014 */  sw        $zero, 0x14($sp)
/* 32798C 802BE81C 0C00F4B9 */  jal       npc_set_imgfx_params
/* 327990 802BE820 AFA00018 */   sw       $zero, 0x18($sp)
/* 327994 802BE824 3C020007 */  lui       $v0, (0x7000A >> 16)
/* 327998 802BE828 3442000A */  ori       $v0, $v0, (0x7000A & 0xFFFF)
/* 32799C 802BE82C 3C030040 */  lui       $v1, (0x400000 >> 16)
/* 3279A0 802BE830 AE220028 */  sw        $v0, 0x28($s1)
/* 3279A4 802BE834 C64C0028 */  lwc1      $f12, 0x28($s2)
/* 3279A8 802BE838 8E420000 */  lw        $v0, 0x0($s2)
/* 3279AC 802BE83C C64E0030 */  lwc1      $f14, 0x30($s2)
/* 3279B0 802BE840 00431025 */  or        $v0, $v0, $v1
/* 3279B4 802BE844 AE420000 */  sw        $v0, 0x0($s2)
/* 3279B8 802BE848 8E260060 */  lw        $a2, 0x60($s1)
/* 3279BC 802BE84C 0C00A7A5 */  jal       dist2D
/* 3279C0 802BE850 8E270068 */   lw       $a3, 0x68($s1)
/* 3279C4 802BE854 3C0140A0 */  lui       $at, (0x40A00000 >> 16)
/* 3279C8 802BE858 44811000 */  mtc1      $at, $f2
/* 3279CC 802BE85C 3C013F19 */  lui       $at, (0x3F19999A >> 16)
/* 3279D0 802BE860 3421999A */  ori       $at, $at, (0x3F19999A & 0xFFFF)
/* 3279D4 802BE864 44812000 */  mtc1      $at, $f4
/* 3279D8 802BE868 C6260064 */  lwc1      $f6, 0x64($s1)
/* 3279DC 802BE86C E622001C */  swc1      $f2, 0x1C($s1)
/* 3279E0 802BE870 E6240014 */  swc1      $f4, 0x14($s1)
/* 3279E4 802BE874 C642002C */  lwc1      $f2, 0x2C($s2)
/* 3279E8 802BE878 3C040001 */  lui       $a0, (0x10007 >> 16)
/* 3279EC 802BE87C 46023181 */  sub.s     $f6, $f6, $f2
/* 3279F0 802BE880 C622001C */  lwc1      $f2, 0x1C($s1)
/* 3279F4 802BE884 34840007 */  ori       $a0, $a0, (0x10007 & 0xFFFF)
/* 3279F8 802BE888 46021080 */  add.s     $f2, $f2, $f2
/* 3279FC 802BE88C E7A00030 */  swc1      $f0, 0x30($sp)
/* 327A00 802BE890 E7A60024 */  swc1      $f6, 0x24($sp)
/* 327A04 802BE894 46041083 */  div.s     $f2, $f2, $f4
/* 327A08 802BE898 4600140D */  trunc.w.s $f16, $f2
/* 327A0C 802BE89C 44028000 */  mfc1      $v0, $f16
/* 327A10 802BE8A0 00000000 */  nop
/* 327A14 802BE8A4 A622008E */  sh        $v0, 0x8E($s1)
/* 327A18 802BE8A8 00021400 */  sll       $v0, $v0, 16
/* 327A1C 802BE8AC 00021403 */  sra       $v0, $v0, 16
/* 327A20 802BE8B0 44824000 */  mtc1      $v0, $f8
/* 327A24 802BE8B4 00000000 */  nop
/* 327A28 802BE8B8 46804220 */  cvt.s.w   $f8, $f8
/* 327A2C 802BE8BC 8623008E */  lh        $v1, 0x8E($s1)
/* 327A30 802BE8C0 C622001C */  lwc1      $f2, 0x1C($s1)
/* 327A34 802BE8C4 44832000 */  mtc1      $v1, $f4
/* 327A38 802BE8C8 00000000 */  nop
/* 327A3C 802BE8CC 46802120 */  cvt.s.w   $f4, $f4
/* 327A40 802BE8D0 46043183 */  div.s     $f6, $f6, $f4
/* 327A44 802BE8D4 46061080 */  add.s     $f2, $f2, $f6
/* 327A48 802BE8D8 46080003 */  div.s     $f0, $f0, $f8
/* 327A4C 802BE8DC E6200018 */  swc1      $f0, 0x18($s1)
/* 327A50 802BE8E0 0C037FB7 */  jal       suggest_player_anim_allow_backward
/* 327A54 802BE8E4 E622001C */   swc1     $f2, 0x1C($s1)
/* 327A58 802BE8E8 8EA20070 */  lw        $v0, 0x70($s5)
/* 327A5C 802BE8EC 24420001 */  addiu     $v0, $v0, 0x1
/* 327A60 802BE8F0 AEA20070 */  sw        $v0, 0x70($s5)
/* 327A64 802BE8F4 862200A8 */  lh        $v0, 0xA8($s1)
/* 327A68 802BE8F8 3C013F00 */  lui       $at, (0x3F000000 >> 16)
/* 327A6C 802BE8FC 44811000 */  mtc1      $at, $f2
/* 327A70 802BE900 44820000 */  mtc1      $v0, $f0
/* 327A74 802BE904 00000000 */  nop
/* 327A78 802BE908 46800020 */  cvt.s.w   $f0, $f0
/* 327A7C 802BE90C 46020002 */  mul.s     $f0, $f0, $f2
/* 327A80 802BE910 00000000 */  nop
/* 327A84 802BE914 C6220064 */  lwc1      $f2, 0x64($s1)
/* 327A88 802BE918 AFA00010 */  sw        $zero, 0x10($sp)
/* 327A8C 802BE91C 46001080 */  add.s     $f2, $f2, $f0
/* 327A90 802BE920 8E250038 */  lw        $a1, 0x38($s1)
/* 327A94 802BE924 8E270040 */  lw        $a3, 0x40($s1)
/* 327A98 802BE928 44061000 */  mfc1      $a2, $f2
/* 327A9C 802BE92C 0C01C164 */  jal       fx_rising_bubble
/* 327AA0 802BE930 0000202D */   daddu    $a0, $zero, $zero
/* 327AA4 802BE934 080AFD26 */  j         .L802BF498
/* 327AA8 802BE938 0000102D */   daddu    $v0, $zero, $zero
.L802BE93C:
/* 327AAC 802BE93C 862200A8 */  lh        $v0, 0xA8($s1)
/* 327AB0 802BE940 3C013F00 */  lui       $at, (0x3F000000 >> 16)
/* 327AB4 802BE944 44811000 */  mtc1      $at, $f2
/* 327AB8 802BE948 44820000 */  mtc1      $v0, $f0
/* 327ABC 802BE94C 00000000 */  nop
/* 327AC0 802BE950 46800020 */  cvt.s.w   $f0, $f0
/* 327AC4 802BE954 46020002 */  mul.s     $f0, $f0, $f2
/* 327AC8 802BE958 00000000 */  nop
/* 327ACC 802BE95C C6220064 */  lwc1      $f2, 0x64($s1)
/* 327AD0 802BE960 AFA00010 */  sw        $zero, 0x10($sp)
/* 327AD4 802BE964 46001080 */  add.s     $f2, $f2, $f0
/* 327AD8 802BE968 8E250038 */  lw        $a1, 0x38($s1)
/* 327ADC 802BE96C 8E270040 */  lw        $a3, 0x40($s1)
/* 327AE0 802BE970 44061000 */  mfc1      $a2, $f2
/* 327AE4 802BE974 0C01C164 */  jal       fx_rising_bubble
/* 327AE8 802BE978 0000202D */   daddu    $a0, $zero, $zero
.L802BE97C:
/* 327AEC 802BE97C 8EA20070 */  lw        $v0, 0x70($s5)
/* 327AF0 802BE980 24420001 */  addiu     $v0, $v0, 0x1
/* 327AF4 802BE984 AEA20070 */  sw        $v0, 0x70($s5)
.L802BE988:
/* 327AF8 802BE988 C640002C */  lwc1      $f0, 0x2C($s2)
/* 327AFC 802BE98C C622001C */  lwc1      $f2, 0x1C($s1)
/* 327B00 802BE990 46020000 */  add.s     $f0, $f0, $f2
/* 327B04 802BE994 26440028 */  addiu     $a0, $s2, 0x28
/* 327B08 802BE998 E640002C */  swc1      $f0, 0x2C($s2)
/* 327B0C 802BE99C C620001C */  lwc1      $f0, 0x1C($s1)
/* 327B10 802BE9A0 C6220014 */  lwc1      $f2, 0x14($s1)
/* 327B14 802BE9A4 8E260018 */  lw        $a2, 0x18($s1)
/* 327B18 802BE9A8 46020001 */  sub.s     $f0, $f0, $f2
/* 327B1C 802BE9AC 8E27000C */  lw        $a3, 0xC($s1)
/* 327B20 802BE9B0 26450030 */  addiu     $a1, $s2, 0x30
/* 327B24 802BE9B4 0C00A7D7 */  jal       add_vec2D_polar
/* 327B28 802BE9B8 E620001C */   swc1     $f0, 0x1C($s1)
/* 327B2C 802BE9BC C622001C */  lwc1      $f2, 0x1C($s1)
/* 327B30 802BE9C0 44800000 */  mtc1      $zero, $f0
/* 327B34 802BE9C4 00000000 */  nop
/* 327B38 802BE9C8 4600103E */  c.le.s    $f2, $f0
/* 327B3C 802BE9CC 00000000 */  nop
/* 327B40 802BE9D0 45000004 */  bc1f      .L802BE9E4
/* 327B44 802BE9D4 00000000 */   nop
/* 327B48 802BE9D8 3C040001 */  lui       $a0, (0x10008 >> 16)
/* 327B4C 802BE9DC 0C037FB7 */  jal       suggest_player_anim_allow_backward
/* 327B50 802BE9E0 34840008 */   ori      $a0, $a0, (0x10008 & 0xFFFF)
.L802BE9E4:
/* 327B54 802BE9E4 C6400028 */  lwc1      $f0, 0x28($s2)
/* 327B58 802BE9E8 C642002C */  lwc1      $f2, 0x2C($s2)
/* 327B5C 802BE9EC C6440030 */  lwc1      $f4, 0x30($s2)
/* 327B60 802BE9F0 3C02800B */  lui       $v0, %hi(gCameras)
/* 327B64 802BE9F4 24421D60 */  addiu     $v0, $v0, %lo(gCameras)
/* 327B68 802BE9F8 E4400060 */  swc1      $f0, 0x60($v0)
/* 327B6C 802BE9FC E4420064 */  swc1      $f2, 0x64($v0)
/* 327B70 802BEA00 E4440068 */  swc1      $f4, 0x68($v0)
/* 327B74 802BEA04 8622008E */  lh        $v0, 0x8E($s1)
/* 327B78 802BEA08 9623008E */  lhu       $v1, 0x8E($s1)
/* 327B7C 802BEA0C 144002A0 */  bnez      $v0, .L802BF490
/* 327B80 802BEA10 2462FFFF */   addiu    $v0, $v1, -0x1
/* 327B84 802BEA14 0C039761 */  jal       set_action_state
/* 327B88 802BEA18 24040021 */   addiu    $a0, $zero, 0x21
/* 327B8C 802BEA1C 0C038031 */  jal       disable_player_shadow
/* 327B90 802BEA20 00000000 */   nop
/* 327B94 802BEA24 3C03FFBF */  lui       $v1, (0xFFBFFFFF >> 16)
/* 327B98 802BEA28 3463FFFF */  ori       $v1, $v1, (0xFFBFFFFF & 0xFFFF)
/* 327B9C 802BEA2C 3C040008 */  lui       $a0, (0x8000F >> 16)
/* 327BA0 802BEA30 8E420000 */  lw        $v0, 0x0($s2)
/* 327BA4 802BEA34 3484000F */  ori       $a0, $a0, (0x8000F & 0xFFFF)
/* 327BA8 802BEA38 00431024 */  and       $v0, $v0, $v1
/* 327BAC 802BEA3C 0C037FD6 */  jal       suggest_player_anim_always_forward
/* 327BB0 802BEA40 AE420000 */   sw       $v0, 0x0($s2)
/* 327BB4 802BEA44 24042013 */  addiu     $a0, $zero, 0x2013
/* 327BB8 802BEA48 0000282D */  daddu     $a1, $zero, $zero
/* 327BBC 802BEA4C 0C053B6E */  jal       sfx_play_sound_at_npc
/* 327BC0 802BEA50 2406FFFC */   addiu    $a2, $zero, -0x4
/* 327BC4 802BEA54 C6200038 */  lwc1      $f0, 0x38($s1)
/* 327BC8 802BEA58 3C014040 */  lui       $at, (0x40400000 >> 16)
/* 327BCC 802BEA5C 44811000 */  mtc1      $at, $f2
/* 327BD0 802BEA60 3C038007 */  lui       $v1, %hi(gGameStatusPtr)
/* 327BD4 802BEA64 8C63417C */  lw        $v1, %lo(gGameStatusPtr)($v1)
/* 327BD8 802BEA68 E6400028 */  swc1      $f0, 0x28($s2)
/* 327BDC 802BEA6C C620003C */  lwc1      $f0, 0x3C($s1)
/* 327BE0 802BEA70 E640002C */  swc1      $f0, 0x2C($s2)
/* 327BE4 802BEA74 C6200040 */  lwc1      $f0, 0x40($s1)
/* 327BE8 802BEA78 E6400030 */  swc1      $f0, 0x30($s2)
/* 327BEC 802BEA7C C620000C */  lwc1      $f0, 0xC($s1)
/* 327BF0 802BEA80 24020001 */  addiu     $v0, $zero, 0x1
/* 327BF4 802BEA84 E6400080 */  swc1      $f0, 0x80($s2)
/* 327BF8 802BEA88 E6220018 */  swc1      $f2, 0x18($s1)
/* 327BFC 802BEA8C A2820000 */  sb        $v0, 0x0($s4)
/* 327C00 802BEA90 24020007 */  addiu     $v0, $zero, 0x7
/* 327C04 802BEA94 A060007D */  sb        $zero, 0x7D($v1)
/* 327C08 802BEA98 A2820003 */  sb        $v0, 0x3($s4)
/* 327C0C 802BEA9C 24020001 */  addiu     $v0, $zero, 0x1
/* 327C10 802BEAA0 3C01802C */  lui       $at, %hi(world_sushie_DiveState)
/* 327C14 802BEAA4 AC20FE84 */  sw        $zero, %lo(world_sushie_DiveState)($at)
/* 327C18 802BEAA8 3C01802C */  lui       $at, %hi(world_sushie_DiveTime)
/* 327C1C 802BEAAC AC20FE88 */  sw        $zero, %lo(world_sushie_DiveTime)($at)
/* 327C20 802BEAB0 AEA00078 */  sw        $zero, 0x78($s5)
/* 327C24 802BEAB4 080AFD25 */  j         .L802BF494
/* 327C28 802BEAB8 AEA20070 */   sw       $v0, 0x70($s5)
.L802BEABC:
/* 327C2C 802BEABC 0220202D */  daddu     $a0, $s1, $zero
/* 327C30 802BEAC0 8E420004 */  lw        $v0, 0x4($s2)
/* 327C34 802BEAC4 3C030040 */  lui       $v1, (0x400000 >> 16)
/* 327C38 802BEAC8 00431025 */  or        $v0, $v0, $v1
/* 327C3C 802BEACC 0C0AF505 */  jal       world_sushie_update_riding_physics
/* 327C40 802BEAD0 AE420004 */   sw       $v0, 0x4($s2)
/* 327C44 802BEAD4 3C10802C */  lui       $s0, %hi(world_sushie_DiveState)
/* 327C48 802BEAD8 2610FE84 */  addiu     $s0, $s0, %lo(world_sushie_DiveState)
/* 327C4C 802BEADC 8E020000 */  lw        $v0, 0x0($s0)
/* 327C50 802BEAE0 14400052 */  bnez      $v0, .L802BEC2C
/* 327C54 802BEAE4 00000000 */   nop
/* 327C58 802BEAE8 8EA30078 */  lw        $v1, 0x78($s5)
/* 327C5C 802BEAEC 24620001 */  addiu     $v0, $v1, 0x1
/* 327C60 802BEAF0 AEA20078 */  sw        $v0, 0x78($s5)
/* 327C64 802BEAF4 28420015 */  slti      $v0, $v0, 0x15
/* 327C68 802BEAF8 14400002 */  bnez      $v0, .L802BEB04
/* 327C6C 802BEAFC 2462FFD9 */   addiu    $v0, $v1, -0x27
/* 327C70 802BEB00 AEA20078 */  sw        $v0, 0x78($s5)
.L802BEB04:
/* 327C74 802BEB04 8EA20078 */  lw        $v0, 0x78($s5)
/* 327C78 802BEB08 3C013E00 */  lui       $at, (0x3E000000 >> 16)
/* 327C7C 802BEB0C 44810000 */  mtc1      $at, $f0
/* 327C80 802BEB10 04420001 */  bltzl     $v0, .LJP_802BEB18
/* 327C84 802BEB14 00021023 */   negu     $v0, $v0
.LJP_802BEB18:
/* 327C88 802BEB18 44821000 */  mtc1      $v0, $f2
/* 327C8C 802BEB1C 00000000 */  nop
/* 327C90 802BEB20 468010A0 */  cvt.s.w   $f2, $f2
/* 327C94 802BEB24 46001082 */  mul.s     $f2, $f2, $f0
/* 327C98 802BEB28 00000000 */  nop
/* 327C9C 802BEB2C C6200064 */  lwc1      $f0, 0x64($s1)
/* 327CA0 802BEB30 46020000 */  add.s     $f0, $f0, $f2
/* 327CA4 802BEB34 E620003C */  swc1      $f0, 0x3C($s1)
/* 327CA8 802BEB38 8EA30078 */  lw        $v1, 0x78($s5)
/* 327CAC 802BEB3C 24020005 */  addiu     $v0, $zero, 0x5
/* 327CB0 802BEB40 14620011 */  bne       $v1, $v0, .L802BEB88
/* 327CB4 802BEB44 27A4002C */   addiu    $a0, $sp, 0x2C
/* 327CB8 802BEB48 0C0AF483 */  jal       world_sushie_get_movement_from_input
/* 327CBC 802BEB4C 27A50034 */   addiu    $a1, $sp, 0x34
/* 327CC0 802BEB50 8E020000 */  lw        $v0, 0x0($s0)
/* 327CC4 802BEB54 1440000C */  bnez      $v0, .L802BEB88
/* 327CC8 802BEB58 00000000 */   nop
/* 327CCC 802BEB5C C7A20034 */  lwc1      $f2, 0x34($sp)
/* 327CD0 802BEB60 44800000 */  mtc1      $zero, $f0
/* 327CD4 802BEB64 00000000 */  nop
/* 327CD8 802BEB68 46001032 */  c.eq.s    $f2, $f0
/* 327CDC 802BEB6C 00000000 */  nop
/* 327CE0 802BEB70 45010002 */  bc1t      .L802BEB7C
/* 327CE4 802BEB74 24042014 */   addiu    $a0, $zero, 0x2014
/* 327CE8 802BEB78 24042015 */  addiu     $a0, $zero, 0x2015
.L802BEB7C:
/* 327CEC 802BEB7C 0000282D */  daddu     $a1, $zero, $zero
/* 327CF0 802BEB80 0C053B6E */  jal       sfx_play_sound_at_npc
/* 327CF4 802BEB84 2406FFFC */   addiu    $a2, $zero, -0x4
.L802BEB88:
/* 327CF8 802BEB88 3C01802C */  lui       $at, %hi(world_sushie_InertialMoveSpeed)
/* 327CFC 802BEB8C C420FE98 */  lwc1      $f0, %lo(world_sushie_InertialMoveSpeed)($at)
/* 327D00 802BEB90 44802000 */  mtc1      $zero, $f4
/* 327D04 802BEB94 00000000 */  nop
/* 327D08 802BEB98 46040032 */  c.eq.s    $f0, $f4
/* 327D0C 802BEB9C 00000000 */  nop
/* 327D10 802BEBA0 45000024 */  bc1f      .L802BEC34
/* 327D14 802BEBA4 00000000 */   nop
/* 327D18 802BEBA8 3C028007 */  lui       $v0, %hi(gGameStatusPtr)
/* 327D1C 802BEBAC 8C42417C */  lw        $v0, %lo(gGameStatusPtr)($v0)
/* 327D20 802BEBB0 94430134 */  lhu       $v1, 0x134($v0)
/* 327D24 802BEBB4 3C02CCCC */  lui       $v0, (0xCCCCCCCD >> 16)
/* 327D28 802BEBB8 3442CCCD */  ori       $v0, $v0, (0xCCCCCCCD & 0xFFFF)
/* 327D2C 802BEBBC 00620019 */  multu     $v1, $v0
/* 327D30 802BEBC0 00004810 */  mfhi      $t1
/* 327D34 802BEBC4 000920C2 */  srl       $a0, $t1, 3
/* 327D38 802BEBC8 00041080 */  sll       $v0, $a0, 2
/* 327D3C 802BEBCC 00441021 */  addu      $v0, $v0, $a0
/* 327D40 802BEBD0 00021040 */  sll       $v0, $v0, 1
/* 327D44 802BEBD4 00621823 */  subu      $v1, $v1, $v0
/* 327D48 802BEBD8 3063FFFF */  andi      $v1, $v1, 0xFFFF
/* 327D4C 802BEBDC 14600015 */  bnez      $v1, .L802BEC34
/* 327D50 802BEBE0 00000000 */   nop
/* 327D54 802BEBE4 862200A8 */  lh        $v0, 0xA8($s1)
/* 327D58 802BEBE8 3C013F00 */  lui       $at, (0x3F000000 >> 16)
/* 327D5C 802BEBEC 44811000 */  mtc1      $at, $f2
/* 327D60 802BEBF0 44820000 */  mtc1      $v0, $f0
/* 327D64 802BEBF4 00000000 */  nop
/* 327D68 802BEBF8 46800020 */  cvt.s.w   $f0, $f0
/* 327D6C 802BEBFC 46020002 */  mul.s     $f0, $f0, $f2
/* 327D70 802BEC00 00000000 */  nop
/* 327D74 802BEC04 C6220064 */  lwc1      $f2, 0x64($s1)
/* 327D78 802BEC08 E7A40010 */  swc1      $f4, 0x10($sp)
/* 327D7C 802BEC0C 46001080 */  add.s     $f2, $f2, $f0
/* 327D80 802BEC10 8E250038 */  lw        $a1, 0x38($s1)
/* 327D84 802BEC14 8E270040 */  lw        $a3, 0x40($s1)
/* 327D88 802BEC18 44061000 */  mfc1      $a2, $f2
/* 327D8C 802BEC1C 0C01C164 */  jal       fx_rising_bubble
/* 327D90 802BEC20 0000202D */   daddu    $a0, $zero, $zero
/* 327D94 802BEC24 080AFB0D */  j         .L802BEC34
/* 327D98 802BEC28 00000000 */   nop
.L802BEC2C:
/* 327D9C 802BEC2C C6200064 */  lwc1      $f0, 0x64($s1)
/* 327DA0 802BEC30 E620003C */  swc1      $f0, 0x3C($s1)
.L802BEC34:
/* 327DA4 802BEC34 8E420004 */  lw        $v0, 0x4($s2)
/* 327DA8 802BEC38 3C030040 */  lui       $v1, (0x400000 >> 16)
/* 327DAC 802BEC3C 00431024 */  and       $v0, $v0, $v1
/* 327DB0 802BEC40 14400003 */  bnez      $v0, D_802BEC50
/* 327DB4 802BEC44 00000000 */   nop
/* 327DB8 802BEC48 0C0AF440 */  jal       world_sushie_sync_player_position
/* 327DBC 802BEC4C 00000000 */   nop
D_802BEC50:
/* 327DC0 802BEC50 3C06802C */  lui       $a2, %hi(world_sushie_DiveState)
/* 327DC4 802BEC54 8CC6FE84 */  lw        $a2, %lo(world_sushie_DiveState)($a2)
/* 327DC8 802BEC58 24020001 */  addiu     $v0, $zero, 0x1
/* 327DCC 802BEC5C 14C20028 */  bne       $a2, $v0, .L802BED00
/* 327DD0 802BEC60 00000000 */   nop
/* 327DD4 802BEC64 3C028007 */  lui       $v0, %hi(gGameStatusPtr)
/* 327DD8 802BEC68 8C42417C */  lw        $v0, %lo(gGameStatusPtr)($v0)
/* 327DDC 802BEC6C 94440134 */  lhu       $a0, 0x134($v0)
/* 327DE0 802BEC70 3C03AF28 */  lui       $v1, (0xAF286BCB >> 16)
/* 327DE4 802BEC74 34636BCB */  ori       $v1, $v1, (0xAF286BCB & 0xFFFF)
/* 327DE8 802BEC78 00830019 */  multu     $a0, $v1
/* 327DEC 802BEC7C 00001810 */  mfhi      $v1
/* 327DF0 802BEC80 00831023 */  subu      $v0, $a0, $v1
/* 327DF4 802BEC84 00021042 */  srl       $v0, $v0, 1
/* 327DF8 802BEC88 00621821 */  addu      $v1, $v1, $v0
/* 327DFC 802BEC8C 00031902 */  srl       $v1, $v1, 4
/* 327E00 802BEC90 00031080 */  sll       $v0, $v1, 2
/* 327E04 802BEC94 00431021 */  addu      $v0, $v0, $v1
/* 327E08 802BEC98 00021080 */  sll       $v0, $v0, 2
/* 327E0C 802BEC9C 00431023 */  subu      $v0, $v0, $v1
/* 327E10 802BECA0 00822023 */  subu      $a0, $a0, $v0
/* 327E14 802BECA4 3084FFFF */  andi      $a0, $a0, 0xFFFF
/* 327E18 802BECA8 14800047 */  bnez      $a0, .L802BEDC8
/* 327E1C 802BECAC 00000000 */   nop
/* 327E20 802BECB0 862200A8 */  lh        $v0, 0xA8($s1)
/* 327E24 802BECB4 3C013F00 */  lui       $at, (0x3F000000 >> 16)
/* 327E28 802BECB8 44810000 */  mtc1      $at, $f0
/* 327E2C 802BECBC 44822000 */  mtc1      $v0, $f4
/* 327E30 802BECC0 00000000 */  nop
/* 327E34 802BECC4 46802120 */  cvt.s.w   $f4, $f4
/* 327E38 802BECC8 46002102 */  mul.s     $f4, $f4, $f0
/* 327E3C 802BECCC 00000000 */  nop
/* 327E40 802BECD0 C622003C */  lwc1      $f2, 0x3C($s1)
/* 327E44 802BECD4 3C01802C */  lui       $at, %hi(world_sushie_WaterSurfaceY)
/* 327E48 802BECD8 C420FE80 */  lwc1      $f0, %lo(world_sushie_WaterSurfaceY)($at)
/* 327E4C 802BECDC 46020001 */  sub.s     $f0, $f0, $f2
/* 327E50 802BECE0 C6220064 */  lwc1      $f2, 0x64($s1)
/* 327E54 802BECE4 E7A00010 */  swc1      $f0, 0x10($sp)
/* 327E58 802BECE8 46041080 */  add.s     $f2, $f2, $f4
/* 327E5C 802BECEC 8E250038 */  lw        $a1, 0x38($s1)
/* 327E60 802BECF0 8E270040 */  lw        $a3, 0x40($s1)
/* 327E64 802BECF4 44061000 */  mfc1      $a2, $f2
/* 327E68 802BECF8 080AFB70 */  j         .L802BEDC0
/* 327E6C 802BECFC 00000000 */   nop
.L802BED00:
/* 327E70 802BED00 3C01802C */  lui       $at, %hi(world_sushie_InertialMoveSpeed)
/* 327E74 802BED04 C420FE98 */  lwc1      $f0, %lo(world_sushie_InertialMoveSpeed)($at)
/* 327E78 802BED08 44803000 */  mtc1      $zero, $f6
/* 327E7C 802BED0C 00000000 */  nop
/* 327E80 802BED10 46060032 */  c.eq.s    $f0, $f6
/* 327E84 802BED14 00000000 */  nop
/* 327E88 802BED18 4501002B */  bc1t      .L802BEDC8
/* 327E8C 802BED1C 28C20002 */   slti     $v0, $a2, 0x2
/* 327E90 802BED20 10400029 */  beqz      $v0, .L802BEDC8
/* 327E94 802BED24 3C032492 */   lui      $v1, (0x24924925 >> 16)
/* 327E98 802BED28 3C028007 */  lui       $v0, %hi(gGameStatusPtr)
/* 327E9C 802BED2C 8C42417C */  lw        $v0, %lo(gGameStatusPtr)($v0)
/* 327EA0 802BED30 94440134 */  lhu       $a0, 0x134($v0)
/* 327EA4 802BED34 34634925 */  ori       $v1, $v1, (0x24924925 & 0xFFFF)
/* 327EA8 802BED38 00830019 */  multu     $a0, $v1
/* 327EAC 802BED3C 00001810 */  mfhi      $v1
/* 327EB0 802BED40 00831023 */  subu      $v0, $a0, $v1
/* 327EB4 802BED44 00021042 */  srl       $v0, $v0, 1
/* 327EB8 802BED48 00621821 */  addu      $v1, $v1, $v0
/* 327EBC 802BED4C 00031882 */  srl       $v1, $v1, 2
/* 327EC0 802BED50 000310C0 */  sll       $v0, $v1, 3
/* 327EC4 802BED54 00431023 */  subu      $v0, $v0, $v1
/* 327EC8 802BED58 00822023 */  subu      $a0, $a0, $v0
/* 327ECC 802BED5C 3084FFFF */  andi      $a0, $a0, 0xFFFF
/* 327ED0 802BED60 14800019 */  bnez      $a0, .L802BEDC8
/* 327ED4 802BED64 26250038 */   addiu    $a1, $s1, 0x38
/* 327ED8 802BED68 862200A8 */  lh        $v0, 0xA8($s1)
/* 327EDC 802BED6C 3C013F00 */  lui       $at, (0x3F000000 >> 16)
/* 327EE0 802BED70 44811000 */  mtc1      $at, $f2
/* 327EE4 802BED74 44820000 */  mtc1      $v0, $f0
/* 327EE8 802BED78 00000000 */  nop
/* 327EEC 802BED7C 46800020 */  cvt.s.w   $f0, $f0
/* 327EF0 802BED80 46020002 */  mul.s     $f0, $f0, $f2
/* 327EF4 802BED84 00000000 */  nop
/* 327EF8 802BED88 C6220064 */  lwc1      $f2, 0x64($s1)
/* 327EFC 802BED8C 26270040 */  addiu     $a3, $s1, 0x40
/* 327F00 802BED90 10C00007 */  beqz      $a2, .L802BEDB0
/* 327F04 802BED94 46001100 */   add.s    $f4, $f2, $f0
/* 327F08 802BED98 3C01802C */  lui       $at, %hi(world_sushie_WaterSurfaceY)
/* 327F0C 802BED9C C420FE80 */  lwc1      $f0, %lo(world_sushie_WaterSurfaceY)($at)
/* 327F10 802BEDA0 C622003C */  lwc1      $f2, 0x3C($s1)
/* 327F14 802BEDA4 46020001 */  sub.s     $f0, $f0, $f2
/* 327F18 802BEDA8 080AFB6D */  j         .L802BEDB4
/* 327F1C 802BEDAC E7A00010 */   swc1     $f0, 0x10($sp)
.L802BEDB0:
/* 327F20 802BEDB0 E7A60010 */  swc1      $f6, 0x10($sp)
.L802BEDB4:
/* 327F24 802BEDB4 8CA50000 */  lw        $a1, 0x0($a1)
/* 327F28 802BEDB8 44062000 */  mfc1      $a2, $f4
/* 327F2C 802BEDBC 8CE70000 */  lw        $a3, 0x0($a3)
.L802BEDC0:
/* 327F30 802BEDC0 0C01C164 */  jal       fx_rising_bubble
/* 327F34 802BEDC4 0000202D */   daddu    $a0, $zero, $zero
.L802BEDC8:
/* 327F38 802BEDC8 C6200038 */  lwc1      $f0, 0x38($s1)
/* 327F3C 802BEDCC 3C01802C */  lui       $at, %hi(world_sushie_WaterSurfaceY)
/* 327F40 802BEDD0 C422FE80 */  lwc1      $f2, %lo(world_sushie_WaterSurfaceY)($at)
/* 327F44 802BEDD4 3C03800B */  lui       $v1, %hi(gCameras)
/* 327F48 802BEDD8 24631D60 */  addiu     $v1, $v1, %lo(gCameras)
/* 327F4C 802BEDDC E4600060 */  swc1      $f0, 0x60($v1)
/* 327F50 802BEDE0 E4620064 */  swc1      $f2, 0x64($v1)
/* 327F54 802BEDE4 8E82000C */  lw        $v0, 0xC($s4)
/* 327F58 802BEDE8 C6200040 */  lwc1      $f0, 0x40($s1)
/* 327F5C 802BEDEC 30424004 */  andi      $v0, $v0, 0x4004
/* 327F60 802BEDF0 14400006 */  bnez      $v0, .L802BEE0C
/* 327F64 802BEDF4 E4600068 */   swc1     $f0, 0x68($v1)
/* 327F68 802BEDF8 3C02802C */  lui       $v0, %hi(world_sushie_TouchDockTime)
/* 327F6C 802BEDFC 8C42FE90 */  lw        $v0, %lo(world_sushie_TouchDockTime)($v0)
/* 327F70 802BEE00 2842001E */  slti      $v0, $v0, 0x1E
/* 327F74 802BEE04 144001A4 */  bnez      $v0, .L802BF498
/* 327F78 802BEE08 0000102D */   daddu    $v0, $zero, $zero
.L802BEE0C:
/* 327F7C 802BEE0C 3C02802C */  lui       $v0, %hi(world_sushie_IsUnderwater)
/* 327F80 802BEE10 8C42FE94 */  lw        $v0, %lo(world_sushie_IsUnderwater)($v0)
/* 327F84 802BEE14 144001A0 */  bnez      $v0, .L802BF498
/* 327F88 802BEE18 0000102D */   daddu    $v0, $zero, $zero
/* 327F8C 802BEE1C 862200A8 */  lh        $v0, 0xA8($s1)
/* 327F90 802BEE20 C6260038 */  lwc1      $f6, 0x38($s1)
/* 327F94 802BEE24 C6200064 */  lwc1      $f0, 0x64($s1)
/* 327F98 802BEE28 C6220040 */  lwc1      $f2, 0x40($s1)
/* 327F9C 802BEE2C 3C014120 */  lui       $at, (0x41200000 >> 16)
/* 327FA0 802BEE30 44814000 */  mtc1      $at, $f8
/* 327FA4 802BEE34 44822000 */  mtc1      $v0, $f4
/* 327FA8 802BEE38 00000000 */  nop
/* 327FAC 802BEE3C 46802120 */  cvt.s.w   $f4, $f4
/* 327FB0 802BEE40 46040000 */  add.s     $f0, $f0, $f4
/* 327FB4 802BEE44 E7A60020 */  swc1      $f6, 0x20($sp)
/* 327FB8 802BEE48 E7A20028 */  swc1      $f2, 0x28($sp)
/* 327FBC 802BEE4C E7A00024 */  swc1      $f0, 0x24($sp)
/* 327FC0 802BEE50 E7A80010 */  swc1      $f8, 0x10($sp)
/* 327FC4 802BEE54 C620000C */  lwc1      $f0, 0xC($s1)
/* 327FC8 802BEE58 E7A00014 */  swc1      $f0, 0x14($sp)
/* 327FCC 802BEE5C 862200A8 */  lh        $v0, 0xA8($s1)
/* 327FD0 802BEE60 27A50020 */  addiu     $a1, $sp, 0x20
/* 327FD4 802BEE64 44820000 */  mtc1      $v0, $f0
/* 327FD8 802BEE68 00000000 */  nop
/* 327FDC 802BEE6C 46800020 */  cvt.s.w   $f0, $f0
/* 327FE0 802BEE70 E7A00018 */  swc1      $f0, 0x18($sp)
/* 327FE4 802BEE74 862200A6 */  lh        $v0, 0xA6($s1)
/* 327FE8 802BEE78 27A60024 */  addiu     $a2, $sp, 0x24
/* 327FEC 802BEE7C 44820000 */  mtc1      $v0, $f0
/* 327FF0 802BEE80 00000000 */  nop
/* 327FF4 802BEE84 46800020 */  cvt.s.w   $f0, $f0
/* 327FF8 802BEE88 E7A0001C */  swc1      $f0, 0x1C($sp)
/* 327FFC 802BEE8C 8E240080 */  lw        $a0, 0x80($s1)
/* 328000 802BEE90 0C0376B1 */  jal       npc_test_move_taller_with_slipping
/* 328004 802BEE94 27A70028 */   addiu    $a3, $sp, 0x28
/* 328008 802BEE98 10400004 */  beqz      $v0, .L802BEEAC
/* 32800C 802BEE9C 2402FFFF */   addiu    $v0, $zero, -0x1
/* 328010 802BEEA0 3C028011 */  lui       $v0, %hi(D_8010CB3A)
/* 328014 802BEEA4 9442CB3A */  lhu       $v0, %lo(D_8010CB3A)($v0)
/* 328018 802BEEA8 A6220086 */  sh        $v0, 0x86($s1)
.L802BEEAC:
/* 32801C 802BEEAC A6C20000 */  sh        $v0, 0x0($s6)
/* 328020 802BEEB0 86240086 */  lh        $a0, 0x86($s1)
/* 328024 802BEEB4 96220086 */  lhu       $v0, 0x86($s1)
/* 328028 802BEEB8 04800009 */  bltz      $a0, .L802BEEE0
/* 32802C 802BEEBC 30424000 */   andi     $v0, $v0, 0x4000
/* 328030 802BEEC0 14400007 */  bnez      $v0, .L802BEEE0
/* 328034 802BEEC4 00000000 */   nop
/* 328038 802BEEC8 0C016E96 */  jal       get_collider_flags
/* 32803C 802BEECC 00000000 */   nop
/* 328040 802BEED0 304200FF */  andi      $v0, $v0, 0xFF
/* 328044 802BEED4 24030004 */  addiu     $v1, $zero, 0x4
/* 328048 802BEED8 10430011 */  beq       $v0, $v1, .L802BEF20
/* 32804C 802BEEDC AFA20040 */   sw       $v0, 0x40($sp)
.L802BEEE0:
/* 328050 802BEEE0 3C03802C */  lui       $v1, %hi(world_sushie_DiveState)
/* 328054 802BEEE4 8C63FE84 */  lw        $v1, %lo(world_sushie_DiveState)($v1)
/* 328058 802BEEE8 24020002 */  addiu     $v0, $zero, 0x2
/* 32805C 802BEEEC 1462016A */  bne       $v1, $v0, .L802BF498
/* 328060 802BEEF0 0000102D */   daddu    $v0, $zero, $zero
/* 328064 802BEEF4 3C03802C */  lui       $v1, %hi(world_sushie_DiveTime)
/* 328068 802BEEF8 8C63FE88 */  lw        $v1, %lo(world_sushie_DiveTime)($v1)
/* 32806C 802BEEFC 24020001 */  addiu     $v0, $zero, 0x1
/* 328070 802BEF00 14620165 */  bne       $v1, $v0, .L802BF498
/* 328074 802BEF04 0000102D */   daddu    $v0, $zero, $zero
/* 328078 802BEF08 24040294 */  addiu     $a0, $zero, 0x294
/* 32807C 802BEF0C 0000282D */  daddu     $a1, $zero, $zero
/* 328080 802BEF10 0C053B6E */  jal       sfx_play_sound_at_npc
/* 328084 802BEF14 2406FFFC */   addiu    $a2, $zero, -0x4
/* 328088 802BEF18 080AFD26 */  j         .L802BF498
/* 32808C 802BEF1C 0000102D */   daddu    $v0, $zero, $zero
.L802BEF20:
/* 328090 802BEF20 27B00020 */  addiu     $s0, $sp, 0x20
/* 328094 802BEF24 0200202D */  daddu     $a0, $s0, $zero
/* 328098 802BEF28 27B40028 */  addiu     $s4, $sp, 0x28
/* 32809C 802BEF2C 3C064220 */  lui       $a2, (0x42200000 >> 16)
/* 3280A0 802BEF30 8E27000C */  lw        $a3, 0xC($s1)
/* 3280A4 802BEF34 C6240038 */  lwc1      $f4, 0x38($s1)
/* 3280A8 802BEF38 C6200064 */  lwc1      $f0, 0x64($s1)
/* 3280AC 802BEF3C 3C0142C8 */  lui       $at, (0x42C80000 >> 16)
/* 3280B0 802BEF40 4481A000 */  mtc1      $at, $f20
/* 3280B4 802BEF44 C6220040 */  lwc1      $f2, 0x40($s1)
/* 3280B8 802BEF48 0280282D */  daddu     $a1, $s4, $zero
/* 3280BC 802BEF4C 3C01802C */  lui       $at, %hi(world_sushie_TouchDockTime)
/* 3280C0 802BEF50 AC20FE90 */  sw        $zero, %lo(world_sushie_TouchDockTime)($at)
/* 3280C4 802BEF54 46140000 */  add.s     $f0, $f0, $f20
/* 3280C8 802BEF58 E7A40020 */  swc1      $f4, 0x20($sp)
/* 3280CC 802BEF5C E7A20028 */  swc1      $f2, 0x28($sp)
/* 3280D0 802BEF60 0C00A7D7 */  jal       add_vec2D_polar
/* 3280D4 802BEF64 E7A00024 */   swc1     $f0, 0x24($sp)
/* 3280D8 802BEF68 0200282D */  daddu     $a1, $s0, $zero
/* 3280DC 802BEF6C 27B60030 */  addiu     $s6, $sp, 0x30
/* 3280E0 802BEF70 27B30024 */  addiu     $s3, $sp, 0x24
/* 3280E4 802BEF74 E7B40030 */  swc1      $f20, 0x30($sp)
/* 3280E8 802BEF78 AFB60010 */  sw        $s6, 0x10($sp)
/* 3280EC 802BEF7C C620000C */  lwc1      $f0, 0xC($s1)
/* 3280F0 802BEF80 0260302D */  daddu     $a2, $s3, $zero
/* 3280F4 802BEF84 AFA00018 */  sw        $zero, 0x18($sp)
/* 3280F8 802BEF88 E7A00014 */  swc1      $f0, 0x14($sp)
/* 3280FC 802BEF8C 8E240080 */  lw        $a0, 0x80($s1)
/* 328100 802BEF90 0C0371D6 */  jal       npc_raycast_down_around
/* 328104 802BEF94 0280382D */   daddu    $a3, $s4, $zero
/* 328108 802BEF98 1040013E */  beqz      $v0, .L802BF494
/* 32810C 802BEF9C AFA20040 */   sw       $v0, 0x40($sp)
/* 328110 802BEFA0 0200282D */  daddu     $a1, $s0, $zero
/* 328114 802BEFA4 0260302D */  daddu     $a2, $s3, $zero
/* 328118 802BEFA8 86240086 */  lh        $a0, 0x86($s1)
/* 32811C 802BEFAC 0C016EB0 */  jal       get_collider_center
/* 328120 802BEFB0 0280382D */   daddu    $a3, $s4, $zero
/* 328124 802BEFB4 C62C0038 */  lwc1      $f12, 0x38($s1)
/* 328128 802BEFB8 C62E0040 */  lwc1      $f14, 0x40($s1)
/* 32812C 802BEFBC 8FA60020 */  lw        $a2, 0x20($sp)
/* 328130 802BEFC0 0C00A7A5 */  jal       dist2D
/* 328134 802BEFC4 8FA70028 */   lw       $a3, 0x28($sp)
/* 328138 802BEFC8 C62C0038 */  lwc1      $f12, 0x38($s1)
/* 32813C 802BEFCC C62E0040 */  lwc1      $f14, 0x40($s1)
/* 328140 802BEFD0 8FA60020 */  lw        $a2, 0x20($sp)
/* 328144 802BEFD4 8FA70028 */  lw        $a3, 0x28($sp)
/* 328148 802BEFD8 0C00A710 */  jal       atan2
/* 32814C 802BEFDC E7A00030 */   swc1     $f0, 0x30($sp)
/* 328150 802BEFE0 3C0140C9 */  lui       $at, (0x40C90FD0 >> 16)
/* 328154 802BEFE4 34210FD0 */  ori       $at, $at, (0x40C90FD0 & 0xFFFF)
/* 328158 802BEFE8 44811000 */  mtc1      $at, $f2
/* 32815C 802BEFEC 00000000 */  nop
/* 328160 802BEFF0 46020002 */  mul.s     $f0, $f0, $f2
/* 328164 802BEFF4 00000000 */  nop
/* 328168 802BEFF8 27A50038 */  addiu     $a1, $sp, 0x38
/* 32816C 802BEFFC 3C0143B4 */  lui       $at, (0x43B40000 >> 16)
/* 328170 802BF000 44816000 */  mtc1      $at, $f12
/* 328174 802BF004 27A6003C */  addiu     $a2, $sp, 0x3C
/* 328178 802BF008 0C00A81D */  jal       sin_cos_rad
/* 32817C 802BF00C 460C0303 */   div.s    $f12, $f0, $f12
/* 328180 802BF010 C7A60038 */  lwc1      $f6, 0x38($sp)
/* 328184 802BF014 C7A20030 */  lwc1      $f2, 0x30($sp)
/* 328188 802BF018 46023182 */  mul.s     $f6, $f6, $f2
/* 32818C 802BF01C 00000000 */  nop
/* 328190 802BF020 3C01802C */  lui       $at, %hi(D_JP_802BFE70)
/* 328194 802BF024 D420FE70 */  ldc1      $f0, %lo(D_JP_802BFE70)($at)
/* 328198 802BF028 460031A1 */  cvt.d.s   $f6, $f6
/* 32819C 802BF02C 46203182 */  mul.d     $f6, $f6, $f0
/* 3281A0 802BF030 00000000 */  nop
/* 3281A4 802BF034 C7A4003C */  lwc1      $f4, 0x3C($sp)
/* 3281A8 802BF038 46022102 */  mul.s     $f4, $f4, $f2
/* 3281AC 802BF03C 00000000 */  nop
/* 3281B0 802BF040 46002121 */  cvt.d.s   $f4, $f4
/* 3281B4 802BF044 46202102 */  mul.d     $f4, $f4, $f0
/* 3281B8 802BF048 00000000 */  nop
/* 3281BC 802BF04C C6220038 */  lwc1      $f2, 0x38($s1)
/* 3281C0 802BF050 460010A1 */  cvt.d.s   $f2, $f2
/* 3281C4 802BF054 C6200040 */  lwc1      $f0, 0x40($s1)
/* 3281C8 802BF058 46261080 */  add.d     $f2, $f2, $f6
/* 3281CC 802BF05C 0200282D */  daddu     $a1, $s0, $zero
/* 3281D0 802BF060 46000021 */  cvt.d.s   $f0, $f0
/* 3281D4 802BF064 46240001 */  sub.d     $f0, $f0, $f4
/* 3281D8 802BF068 E7B40030 */  swc1      $f20, 0x30($sp)
/* 3281DC 802BF06C 462010A0 */  cvt.s.d   $f2, $f2
/* 3281E0 802BF070 46200020 */  cvt.s.d   $f0, $f0
/* 3281E4 802BF074 E7A20020 */  swc1      $f2, 0x20($sp)
/* 3281E8 802BF078 E7A00028 */  swc1      $f0, 0x28($sp)
/* 3281EC 802BF07C AFB60010 */  sw        $s6, 0x10($sp)
/* 3281F0 802BF080 C620000C */  lwc1      $f0, 0xC($s1)
/* 3281F4 802BF084 0260302D */  daddu     $a2, $s3, $zero
/* 3281F8 802BF088 AFA00018 */  sw        $zero, 0x18($sp)
/* 3281FC 802BF08C E7A00014 */  swc1      $f0, 0x14($sp)
/* 328200 802BF090 8E240080 */  lw        $a0, 0x80($s1)
/* 328204 802BF094 0C0371D6 */  jal       npc_raycast_down_around
/* 328208 802BF098 0280382D */   daddu    $a3, $s4, $zero
/* 32820C 802BF09C C7A00024 */  lwc1      $f0, 0x24($sp)
/* 328210 802BF0A0 C7A20020 */  lwc1      $f2, 0x20($sp)
/* 328214 802BF0A4 C7A40028 */  lwc1      $f4, 0x28($sp)
/* 328218 802BF0A8 E6200064 */  swc1      $f0, 0x64($s1)
/* 32821C 802BF0AC E6220060 */  swc1      $f2, 0x60($s1)
/* 328220 802BF0B0 E6240068 */  swc1      $f4, 0x68($s1)
/* 328224 802BF0B4 C64C0028 */  lwc1      $f12, 0x28($s2)
/* 328228 802BF0B8 C64E0030 */  lwc1      $f14, 0x30($s2)
/* 32822C 802BF0BC 44061000 */  mfc1      $a2, $f2
/* 328230 802BF0C0 44072000 */  mfc1      $a3, $f4
/* 328234 802BF0C4 0C00A710 */  jal       atan2
/* 328238 802BF0C8 00000000 */   nop
/* 32823C 802BF0CC E6400080 */  swc1      $f0, 0x80($s2)
/* 328240 802BF0D0 E620000C */  swc1      $f0, 0xC($s1)
/* 328244 802BF0D4 C64C0028 */  lwc1      $f12, 0x28($s2)
/* 328248 802BF0D8 C64E0030 */  lwc1      $f14, 0x30($s2)
/* 32824C 802BF0DC 8E260060 */  lw        $a2, 0x60($s1)
/* 328250 802BF0E0 0C00A7A5 */  jal       dist2D
/* 328254 802BF0E4 8E270068 */   lw       $a3, 0x68($s1)
/* 328258 802BF0E8 3C0140A0 */  lui       $at, (0x40A00000 >> 16)
/* 32825C 802BF0EC 44811000 */  mtc1      $at, $f2
/* 328260 802BF0F0 3C013F19 */  lui       $at, (0x3F19999A >> 16)
/* 328264 802BF0F4 3421999A */  ori       $at, $at, (0x3F19999A & 0xFFFF)
/* 328268 802BF0F8 44812000 */  mtc1      $at, $f4
/* 32826C 802BF0FC 24042081 */  addiu     $a0, $zero, 0x2081
/* 328270 802BF100 E622001C */  swc1      $f2, 0x1C($s1)
/* 328274 802BF104 46021080 */  add.s     $f2, $f2, $f2
/* 328278 802BF108 0000282D */  daddu     $a1, $zero, $zero
/* 32827C 802BF10C E6240014 */  swc1      $f4, 0x14($s1)
/* 328280 802BF110 46041083 */  div.s     $f2, $f2, $f4
/* 328284 802BF114 4600140D */  trunc.w.s $f16, $f2
/* 328288 802BF118 44028000 */  mfc1      $v0, $f16
/* 32828C 802BF11C 00000000 */  nop
/* 328290 802BF120 A622008E */  sh        $v0, 0x8E($s1)
/* 328294 802BF124 00021400 */  sll       $v0, $v0, 16
/* 328298 802BF128 00021403 */  sra       $v0, $v0, 16
/* 32829C 802BF12C 44821000 */  mtc1      $v0, $f2
/* 3282A0 802BF130 00000000 */  nop
/* 3282A4 802BF134 468010A0 */  cvt.s.w   $f2, $f2
/* 3282A8 802BF138 46020083 */  div.s     $f2, $f0, $f2
/* 3282AC 802BF13C E6220018 */  swc1      $f2, 0x18($s1)
/* 3282B0 802BF140 C6220064 */  lwc1      $f2, 0x64($s1)
/* 3282B4 802BF144 C644002C */  lwc1      $f4, 0x2C($s2)
/* 3282B8 802BF148 8622008E */  lh        $v0, 0x8E($s1)
/* 3282BC 802BF14C 46041081 */  sub.s     $f2, $f2, $f4
/* 3282C0 802BF150 44823000 */  mtc1      $v0, $f6
/* 3282C4 802BF154 00000000 */  nop
/* 3282C8 802BF158 468031A0 */  cvt.s.w   $f6, $f6
/* 3282CC 802BF15C C624001C */  lwc1      $f4, 0x1C($s1)
/* 3282D0 802BF160 46061083 */  div.s     $f2, $f2, $f6
/* 3282D4 802BF164 46022100 */  add.s     $f4, $f4, $f2
/* 3282D8 802BF168 2406FFFC */  addiu     $a2, $zero, -0x4
/* 3282DC 802BF16C E7A00030 */  swc1      $f0, 0x30($sp)
/* 3282E0 802BF170 0C053B6E */  jal       sfx_play_sound_at_npc
/* 3282E4 802BF174 E624001C */   swc1     $f4, 0x1C($s1)
/* 3282E8 802BF178 3C040001 */  lui       $a0, (0x10006 >> 16)
/* 3282EC 802BF17C 0C037FB7 */  jal       suggest_player_anim_allow_backward
/* 3282F0 802BF180 34840006 */   ori      $a0, $a0, (0x10006 & 0xFFFF)
/* 3282F4 802BF184 0C038024 */  jal       enable_player_shadow
/* 3282F8 802BF188 00000000 */   nop
/* 3282FC 802BF18C 8E420000 */  lw        $v0, 0x0($s2)
/* 328300 802BF190 3C030040 */  lui       $v1, (0x400000 >> 16)
/* 328304 802BF194 00431025 */  or        $v0, $v0, $v1
/* 328308 802BF198 AE420000 */  sw        $v0, 0x0($s2)
/* 32830C 802BF19C 24020003 */  addiu     $v0, $zero, 0x3
/* 328310 802BF1A0 080AFD25 */  j         .L802BF494
/* 328314 802BF1A4 AEA20070 */   sw       $v0, 0x70($s5)
.L802BF1A8:
/* 328318 802BF1A8 3C040001 */  lui       $a0, (0x10007 >> 16)
/* 32831C 802BF1AC 0C037FB7 */  jal       suggest_player_anim_allow_backward
/* 328320 802BF1B0 34840007 */   ori      $a0, $a0, (0x10007 & 0xFFFF)
/* 328324 802BF1B4 8EA20070 */  lw        $v0, 0x70($s5)
/* 328328 802BF1B8 24420001 */  addiu     $v0, $v0, 0x1
/* 32832C 802BF1BC AEA20070 */  sw        $v0, 0x70($s5)
.L802BF1C0:
/* 328330 802BF1C0 C622001C */  lwc1      $f2, 0x1C($s1)
/* 328334 802BF1C4 44800000 */  mtc1      $zero, $f0
/* 328338 802BF1C8 00000000 */  nop
/* 32833C 802BF1CC 4600103E */  c.le.s    $f2, $f0
/* 328340 802BF1D0 00000000 */  nop
/* 328344 802BF1D4 45000006 */  bc1f      .L802BF1F0
/* 328348 802BF1D8 3C040001 */   lui      $a0, (0x10008 >> 16)
/* 32834C 802BF1DC 0C037FB7 */  jal       suggest_player_anim_allow_backward
/* 328350 802BF1E0 34840008 */   ori      $a0, $a0, (0x10008 & 0xFFFF)
/* 328354 802BF1E4 8EA20070 */  lw        $v0, 0x70($s5)
/* 328358 802BF1E8 24420001 */  addiu     $v0, $v0, 0x1
/* 32835C 802BF1EC AEA20070 */  sw        $v0, 0x70($s5)
.L802BF1F0:
/* 328360 802BF1F0 C62C001C */  lwc1      $f12, 0x1C($s1)
/* 328364 802BF1F4 44800000 */  mtc1      $zero, $f0
/* 328368 802BF1F8 00000000 */  nop
/* 32836C 802BF1FC 4600603E */  c.le.s    $f12, $f0
/* 328370 802BF200 00000000 */  nop
/* 328374 802BF204 4500000C */  bc1f      .L802BF238
/* 328378 802BF208 00000000 */   nop
/* 32837C 802BF20C 0C038D3D */  jal       player_check_collision_below
/* 328380 802BF210 27A50040 */   addiu    $a1, $sp, 0x40
/* 328384 802BF214 8FA20040 */  lw        $v0, 0x40($sp)
/* 328388 802BF218 E7A00024 */  swc1      $f0, 0x24($sp)
/* 32838C 802BF21C 18400009 */  blez      $v0, .L802BF244
/* 328390 802BF220 E640002C */   swc1     $f0, 0x2C($s2)
/* 328394 802BF224 3C040001 */  lui       $a0, (0x10009 >> 16)
/* 328398 802BF228 0C037FB7 */  jal       suggest_player_anim_allow_backward
/* 32839C 802BF22C 34840009 */   ori      $a0, $a0, (0x10009 & 0xFFFF)
/* 3283A0 802BF230 080AFC91 */  j         .L802BF244
/* 3283A4 802BF234 00000000 */   nop
.L802BF238:
/* 3283A8 802BF238 C640002C */  lwc1      $f0, 0x2C($s2)
/* 3283AC 802BF23C 460C0000 */  add.s     $f0, $f0, $f12
/* 3283B0 802BF240 E640002C */  swc1      $f0, 0x2C($s2)
.L802BF244:
/* 3283B4 802BF244 C620001C */  lwc1      $f0, 0x1C($s1)
/* 3283B8 802BF248 C6220014 */  lwc1      $f2, 0x14($s1)
/* 3283BC 802BF24C 46020001 */  sub.s     $f0, $f0, $f2
/* 3283C0 802BF250 3C02800B */  lui       $v0, %hi(gCameras)
/* 3283C4 802BF254 24421D60 */  addiu     $v0, $v0, %lo(gCameras)
/* 3283C8 802BF258 E620001C */  swc1      $f0, 0x1C($s1)
/* 3283CC 802BF25C C6400028 */  lwc1      $f0, 0x28($s2)
/* 3283D0 802BF260 C642002C */  lwc1      $f2, 0x2C($s2)
/* 3283D4 802BF264 C6440030 */  lwc1      $f4, 0x30($s2)
/* 3283D8 802BF268 26440028 */  addiu     $a0, $s2, 0x28
/* 3283DC 802BF26C E4400060 */  swc1      $f0, 0x60($v0)
/* 3283E0 802BF270 E4420064 */  swc1      $f2, 0x64($v0)
/* 3283E4 802BF274 E4440068 */  swc1      $f4, 0x68($v0)
/* 3283E8 802BF278 8622008E */  lh        $v0, 0x8E($s1)
/* 3283EC 802BF27C 10400007 */  beqz      $v0, .L802BF29C
/* 3283F0 802BF280 26450030 */   addiu    $a1, $s2, 0x30
/* 3283F4 802BF284 8E260018 */  lw        $a2, 0x18($s1)
/* 3283F8 802BF288 0C00A7D7 */  jal       add_vec2D_polar
/* 3283FC 802BF28C 8E27000C */   lw       $a3, 0xC($s1)
/* 328400 802BF290 9622008E */  lhu       $v0, 0x8E($s1)
/* 328404 802BF294 080AFD24 */  j         .L802BF490
/* 328408 802BF298 2442FFFF */   addiu    $v0, $v0, -0x1
.L802BF29C:
/* 32840C 802BF29C 8FA20040 */  lw        $v0, 0x40($sp)
/* 328410 802BF2A0 0440007C */  bltz      $v0, .L802BF494
/* 328414 802BF2A4 3C03FFBF */   lui      $v1, (0xFFBFFFFF >> 16)
/* 328418 802BF2A8 3463FFFF */  ori       $v1, $v1, (0xFFBFFFFF & 0xFFFF)
/* 32841C 802BF2AC 3C040001 */  lui       $a0, (0x10002 >> 16)
/* 328420 802BF2B0 8E420000 */  lw        $v0, 0x0($s2)
/* 328424 802BF2B4 34840002 */  ori       $a0, $a0, (0x10002 & 0xFFFF)
/* 328428 802BF2B8 00431024 */  and       $v0, $v0, $v1
/* 32842C 802BF2BC 0C037FB7 */  jal       suggest_player_anim_allow_backward
/* 328430 802BF2C0 AE420000 */   sw       $v0, 0x0($s2)
/* 328434 802BF2C4 C62C0038 */  lwc1      $f12, 0x38($s1)
/* 328438 802BF2C8 C62E0040 */  lwc1      $f14, 0x40($s1)
/* 32843C 802BF2CC 8E260060 */  lw        $a2, 0x60($s1)
/* 328440 802BF2D0 8E220000 */  lw        $v0, 0x0($s1)
/* 328444 802BF2D4 8E270068 */  lw        $a3, 0x68($s1)
/* 328448 802BF2D8 34420040 */  ori       $v0, $v0, 0x40
/* 32844C 802BF2DC 0C00A7A5 */  jal       dist2D
/* 328450 802BF2E0 AE220000 */   sw       $v0, 0x0($s1)
/* 328454 802BF2E4 864200B2 */  lh        $v0, 0xB2($s2)
/* 328458 802BF2E8 3C013F00 */  lui       $at, (0x3F000000 >> 16)
/* 32845C 802BF2EC 44811000 */  mtc1      $at, $f2
/* 328460 802BF2F0 3C014100 */  lui       $at, (0x41000000 >> 16)
/* 328464 802BF2F4 44814000 */  mtc1      $at, $f8
/* 328468 802BF2F8 3C013F80 */  lui       $at, (0x3F800000 >> 16)
/* 32846C 802BF2FC 44815000 */  mtc1      $at, $f10
/* 328470 802BF300 C6260064 */  lwc1      $f6, 0x64($s1)
/* 328474 802BF304 44822000 */  mtc1      $v0, $f4
/* 328478 802BF308 00000000 */  nop
/* 32847C 802BF30C 46802120 */  cvt.s.w   $f4, $f4
/* 328480 802BF310 46022102 */  mul.s     $f4, $f4, $f2
/* 328484 802BF314 00000000 */  nop
/* 328488 802BF318 C622003C */  lwc1      $f2, 0x3C($s1)
/* 32848C 802BF31C E628001C */  swc1      $f8, 0x1C($s1)
/* 328490 802BF320 3C014080 */  lui       $at, (0x40800000 >> 16)
/* 328494 802BF324 44814000 */  mtc1      $at, $f8
/* 328498 802BF328 46023181 */  sub.s     $f6, $f6, $f2
/* 32849C 802BF32C C622001C */  lwc1      $f2, 0x1C($s1)
/* 3284A0 802BF330 E62A0014 */  swc1      $f10, 0x14($s1)
/* 3284A4 802BF334 46021080 */  add.s     $f2, $f2, $f2
/* 3284A8 802BF338 E6280018 */  swc1      $f8, 0x18($s1)
/* 3284AC 802BF33C E7A60024 */  swc1      $f6, 0x24($sp)
/* 3284B0 802BF340 460A1083 */  div.s     $f2, $f2, $f10
/* 3284B4 802BF344 4600140D */  trunc.w.s $f16, $f2
/* 3284B8 802BF348 44028000 */  mfc1      $v0, $f16
/* 3284BC 802BF34C 00000000 */  nop
/* 3284C0 802BF350 A622008E */  sh        $v0, 0x8E($s1)
/* 3284C4 802BF354 00021400 */  sll       $v0, $v0, 16
/* 3284C8 802BF358 00021403 */  sra       $v0, $v0, 16
/* 3284CC 802BF35C 46040000 */  add.s     $f0, $f0, $f4
/* 3284D0 802BF360 44824000 */  mtc1      $v0, $f8
/* 3284D4 802BF364 00000000 */  nop
/* 3284D8 802BF368 46804220 */  cvt.s.w   $f8, $f8
/* 3284DC 802BF36C 2402000A */  addiu     $v0, $zero, 0xA
/* 3284E0 802BF370 E7A00030 */  swc1      $f0, 0x30($sp)
/* 3284E4 802BF374 8623008E */  lh        $v1, 0x8E($s1)
/* 3284E8 802BF378 C622001C */  lwc1      $f2, 0x1C($s1)
/* 3284EC 802BF37C 44832000 */  mtc1      $v1, $f4
/* 3284F0 802BF380 00000000 */  nop
/* 3284F4 802BF384 46802120 */  cvt.s.w   $f4, $f4
/* 3284F8 802BF388 46043183 */  div.s     $f6, $f6, $f4
/* 3284FC 802BF38C 46061080 */  add.s     $f2, $f2, $f6
/* 328500 802BF390 46080003 */  div.s     $f0, $f0, $f8
/* 328504 802BF394 E6200018 */  swc1      $f0, 0x18($s1)
/* 328508 802BF398 E622001C */  swc1      $f2, 0x1C($s1)
/* 32850C 802BF39C 080AFD25 */  j         .L802BF494
/* 328510 802BF3A0 AEA20070 */   sw       $v0, 0x70($s5)
.L802BF3A4:
/* 328514 802BF3A4 26240038 */  addiu     $a0, $s1, 0x38
/* 328518 802BF3A8 C624003C */  lwc1      $f4, 0x3C($s1)
/* 32851C 802BF3AC C620001C */  lwc1      $f0, 0x1C($s1)
/* 328520 802BF3B0 8E260018 */  lw        $a2, 0x18($s1)
/* 328524 802BF3B4 46002100 */  add.s     $f4, $f4, $f0
/* 328528 802BF3B8 C6220014 */  lwc1      $f2, 0x14($s1)
/* 32852C 802BF3BC 8E27000C */  lw        $a3, 0xC($s1)
/* 328530 802BF3C0 46020001 */  sub.s     $f0, $f0, $f2
/* 328534 802BF3C4 26250040 */  addiu     $a1, $s1, 0x40
/* 328538 802BF3C8 E624003C */  swc1      $f4, 0x3C($s1)
/* 32853C 802BF3CC 0C00A7D7 */  jal       add_vec2D_polar
/* 328540 802BF3D0 E620001C */   swc1     $f0, 0x1C($s1)
/* 328544 802BF3D4 8622008E */  lh        $v0, 0x8E($s1)
/* 328548 802BF3D8 9623008E */  lhu       $v1, 0x8E($s1)
/* 32854C 802BF3DC 1440002C */  bnez      $v0, .L802BF490
/* 328550 802BF3E0 2462FFFF */   addiu    $v0, $v1, -0x1
/* 328554 802BF3E4 0C038048 */  jal       enable_player_static_collisions
/* 328558 802BF3E8 00000000 */   nop
/* 32855C 802BF3EC 0C038061 */  jal       enable_player_input
/* 328560 802BF3F0 00000000 */   nop
/* 328564 802BF3F4 0C039761 */  jal       set_action_state
/* 328568 802BF3F8 0000202D */   daddu    $a0, $zero, $zero
/* 32856C 802BF3FC 0C00EA18 */  jal       enable_npc_shadow
/* 328570 802BF400 0220202D */   daddu    $a0, $s1, $zero
/* 328574 802BF404 0C03BCFC */  jal       partner_clear_player_tracking
/* 328578 802BF408 0220202D */   daddu    $a0, $s1, $zero
/* 32857C 802BF40C 3C040001 */  lui       $a0, (0x10002 >> 16)
/* 328580 802BF410 34840002 */  ori       $a0, $a0, (0x10002 & 0xFFFF)
/* 328584 802BF414 0000282D */  daddu     $a1, $zero, $zero
/* 328588 802BF418 00A0302D */  daddu     $a2, $a1, $zero
/* 32858C 802BF41C 00A0382D */  daddu     $a3, $a1, $zero
/* 328590 802BF420 8E220000 */  lw        $v0, 0x0($s1)
/* 328594 802BF424 3C088007 */  lui       $t0, %hi(gGameStatusPtr)
/* 328598 802BF428 8D08417C */  lw        $t0, %lo(gGameStatusPtr)($t0)
/* 32859C 802BF42C 2403FFF7 */  addiu     $v1, $zero, -0x9
/* 3285A0 802BF430 3C01802C */  lui       $at, %hi(world_sushie_IsRiding)
/* 3285A4 802BF434 AC20FE8C */  sw        $zero, %lo(world_sushie_IsRiding)($at)
/* 3285A8 802BF438 00431024 */  and       $v0, $v0, $v1
/* 3285AC 802BF43C 34420200 */  ori       $v0, $v0, 0x200
/* 3285B0 802BF440 2403FFBF */  addiu     $v1, $zero, -0x41
/* 3285B4 802BF444 00431024 */  and       $v0, $v0, $v1
/* 3285B8 802BF448 AE220000 */  sw        $v0, 0x0($s1)
/* 3285BC 802BF44C A100007D */  sb        $zero, 0x7D($t0)
/* 3285C0 802BF450 A2800000 */  sb        $zero, 0x0($s4)
/* 3285C4 802BF454 A2800003 */  sb        $zero, 0x3($s4)
/* 3285C8 802BF458 AFA00010 */  sw        $zero, 0x10($sp)
/* 3285CC 802BF45C AFA00014 */  sw        $zero, 0x14($sp)
/* 3285D0 802BF460 0C0446D2 */  jal       set_player_imgfx_all
/* 3285D4 802BF464 AFA00018 */   sw       $zero, 0x18($sp)
/* 3285D8 802BF468 0220202D */  daddu     $a0, $s1, $zero
/* 3285DC 802BF46C 0000282D */  daddu     $a1, $zero, $zero
/* 3285E0 802BF470 00A0302D */  daddu     $a2, $a1, $zero
/* 3285E4 802BF474 00A0382D */  daddu     $a3, $a1, $zero
/* 3285E8 802BF478 AFA00010 */  sw        $zero, 0x10($sp)
/* 3285EC 802BF47C AFA00014 */  sw        $zero, 0x14($sp)
/* 3285F0 802BF480 0C00F4B9 */  jal       npc_set_imgfx_params
/* 3285F4 802BF484 AFA00018 */   sw       $zero, 0x18($sp)
/* 3285F8 802BF488 080AFD26 */  j         .L802BF498
/* 3285FC 802BF48C 24020001 */   addiu    $v0, $zero, 0x1
.L802BF490:
/* 328600 802BF490 A622008E */  sh        $v0, 0x8E($s1)
.L802BF494:
/* 328604 802BF494 0000102D */  daddu     $v0, $zero, $zero
.L802BF498:
/* 328608 802BF498 8FBF0064 */  lw        $ra, 0x64($sp)
/* 32860C 802BF49C 8FB60060 */  lw        $s6, 0x60($sp)
/* 328610 802BF4A0 8FB5005C */  lw        $s5, 0x5C($sp)
/* 328614 802BF4A4 8FB40058 */  lw        $s4, 0x58($sp)
/* 328618 802BF4A8 8FB30054 */  lw        $s3, 0x54($sp)
/* 32861C 802BF4AC 8FB20050 */  lw        $s2, 0x50($sp)
/* 328620 802BF4B0 8FB1004C */  lw        $s1, 0x4C($sp)
/* 328624 802BF4B4 8FB00048 */  lw        $s0, 0x48($sp)
/* 328628 802BF4B8 D7B40068 */  ldc1      $f20, 0x68($sp)
/* 32862C 802BF4BC 03E00008 */  jr        $ra
/* 328630 802BF4C0 27BD0070 */   addiu    $sp, $sp, 0x70
.size func_JP_802BE348, . - func_JP_802BE348
