#include "common.h"

#include "entity/model/HiddenPanel_topSide.vtx.inc.c"
#include "entity/model/HiddenPanel_bottomSide.vtx.inc.c"
#include "entity/model/HiddenPanel_bottomSideDark.vtx.inc.c"
#include "entity/model/HiddenPanel_topSide2.vtx.inc.c"
#include "entity/model/HiddenPanel_unused1.vtx.inc.c"
#include "entity/model/HiddenPanel_unused2.vtx.inc.c"

#include "entity/model/gfx/HiddenPanel/renderTop.gfx.inc.c"
#include "entity/model/gfx/HiddenPanel/renderTopAlt.gfx.inc.c"
#include "entity/model/gfx/HiddenPanel/renderBottom.gfx.inc.c"
#include "entity/model/gfx/HiddenPanel/renderHole.gfx.inc.c"
#include "entity/model/gfx/HiddenPanel/render.gfx.inc.c"
#include "entity/model/gfx/HiddenPanel/renderAlt.gfx.inc.c"
